### ISSUE TITLE
Documentation site  - tooling and design

### ISSUE THREAD

**Issue by trallard** [nebari-dev/nebari#1]
- Need to discuss the look of the site and the tooling that will allow us to achieve what we want

## TODO 

- [x] Gather requirements
- [x] Identify tools
- [x] Decide and design
- [x] Implement

WIP from @kcpevey https://www.figma.com/file/7G2YapYjayeMyi2zdDcl5d/Nebari_mock_up_v1?node-id=0%3A1

**Comment by kcpevey** [comment]
Plan is to use [docusaurus](https://docusaurus.io/). 
[Documentation design doc](https://www.notion.so/quansightlabs/Nebari-documentation-overhaul-0ba9f5489fe44a30aac8c3c97f778c58)
