### ISSUE TITLE
CI/CD Refactor 

### ISSUE THREAD

**Issue by iameskild** [nebari-dev/nebari#1005]
# Nebari CI/CD Pipeline Improvements

General notes and ideas
- can we create custom image for the running
    - custom AMI for CI-Run?
- benchmark the size of docker images
  - reducing the size much more might be difficult given the required packages
  - initial tests with Docker Slim were unsuccessful 
- multi-stage docker image builds
  - look at `centos` git branch for initial attempt 
- only trigger workflow if they are touched  

Test order, only proceed if previous step was successful
- lint
  - docker lint (hadolint ?) 
  - python lint (black/flake8/etc ?)
  - terraform lint (find one ?)
- docker 
  - build images / push to registry
  - is there a way to use cached/pre-existing docker images during the CI process (to save time)
     - diff the dockerfiles and related files
- python
  - pytests (stages)
  - test providers (`qhub init`, `qhub render`)
- kubernetes local test
- (docs)

Integration tests
- terraform infrastructure
  - full integration tests
    - review - why are they failing so often...
    - what are the actions we should take if these tests fail?
  

Next steps
- Review the action triggers
  - avoid duplicates (push and pull requests)
- Review `Test Provider` workflow   
  - is there another way to implement?
  - add concurrency?

Resources
- https://docs.aws.amazon.com/toolkit-for-visual-studio/latest/user-guide/tkv-create-ami-from-instance.html
- https://github.com/wagoodman/dive
- https://docs.github.com/en/actions/using-jobs/using-concurrency

**Comment by iameskild** [comment]
Hey @magsol, @viniciusdc, @HarshCasper and I had a discussion around CI/CD pipeline improvements for qhub. We'll use this issue to track what needs to be done. Let us know if you have any other ideas, we're all happy to pick up this discussion again next week.

**Comment by magsol** [comment]
This is awesome, thank you so much for putting this together! Yeah let's see what Gonzalo has to say when we meet with him today and go from there.

**Comment by magsol** [comment]
Potential option for documentation link checker https://github.com/lycheeverse/lychee

**Comment by magsol** [comment]
Security considerations with GitHub Actions https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

**Comment by goanpeca** [comment]
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run

https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-a-workflow-based-on-the-conclusion-of-another-workflow

**Comment by viniciusdc** [comment]
I think the major points to get this working in a future release are:
- Decoupling docker images into base and custom configurations
- Custom testing classes suit 
- Enhances to pytest during qhub deployment (tests between stages)

**Comment by iameskild** [comment]
@iameskild to update the current state of the CI/CD then we can decide on what needs to be changed / updated.

**Comment by trallard** [comment]
@iameskild  we have another issue #1128 - I am going to close this as there are items that are now out to date and favour the other one for tracking tasks and discussions
