### ISSUE TITLE
[enhancement] Allow qhub users to customize their docker images

### ISSUE THREAD

**Issue by iameskild** [nebari-dev/nebari#1045]
Tracking issue.

This is a feature that was implemented but perhaps not well documented.
https://github.com/Quansight/qhub/blob/v0.3.14/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/.github/workflows/image.yaml

A few qhub users have recently asked how to add apt packages to the jupyterlab environments. Allowing them to customize the underlying qhub docker images would given end-users this ability along with more control and freedom to make other changes. 

A few items to consider:
- wholesale changes might break functionality
  - perhaps creating a "base" image from which they can build on top of would get around this issue
- which registry would these new images get stored to

**Comment by costrouc** [comment]
The tricky parts that we need to consider here:
  - user makes changes to the docker images
  - need some process to kick off the docker image build
  - that image build needs to be uploaded somewhere
  - then qhub needs to be redeployed when this image has been built

Within enterprise environments these steps could be tricky to pull off. But for CI/CD focused deployments using github/gitlab we should be able to automate this. We've had some of the parts done in the past but the tricky part was getting this to work with all the different cloud providers.

**Comment by trallard** [comment]
@iameskild  if I remember correctly you had some thoughts/proposals around this? 

Are you still interested in moving this forward?

**Comment by iameskild** [comment]
@trallard I'm still very much interesting in working on this! I have a few ideas that I would like to flesh out. I will get to this, I just can't promise when 😅

**Comment by iameskild** [comment]
@trallard this the other issue that is related the [RFD](https://github.com/nebari-dev/governance/issues/22) I recently opened.

**Comment by trallard** [comment]
Will close this issue in favour of the RFD currently being discussed
