### ISSUE TITLE
Compare Various Workflow Automation Solutions for potential integration into Nebari

### ISSUE THREAD

**Issue by Adam-D-Lewis** [nebari-dev/nebari#1098]
### Feature description

Currently long running computations require a browser window to be kept open for the duration of the computation. Some prototype work has been done to enable ‘background’ and ‘batch’ processes to be run on QHub. 

### Value and/or benefit

This feature would enhance this and make it easily accessible to scientists and engineers using the platform.

**Comment by Adam-D-Lewis** [comment]
There are a few possible options that I've considered: [jupyterhub-ssh](https://github.com/yuvipanda/jupyterhub-ssh), [kbatch](https://github.com/kbatch-dev/kbatch), or just let whatever solution we come up with https://github.com/Quansight/qhub/issues/1100 and/or https://github.com/Quansight/qhub/issues/1099 handle this as well.

Kbatch and jupyterhub-ssh could both solve this potentially.  Kbatch has the advantage that it can run on custom docker images, allowing users access to dependencies that aren't available through conda, but the user does not have access to all the jupyter user's files.  Instead, kbatch allows you to pass in a single file or directory only up to 1 MiB in size (uses ConfigMap under the hood).  Jupyterhub-ssh doesn't have that limitation, allowing access to all of the jupyter user's files by default.  Both Kbatch and jupyterhub-ssh can allow users access to the conda envs in conda-store, and both could run notebooks via [papermill](https://papermill.readthedocs.io/en/latest/).

How jupyterhub-ssh would work currently
-------------------------------------------------------------
- Create Jupyter API token
- Open terminal in jupyterlab (from within Qhub)
- run `ssh -o User=<username> <qhub-url> -p 8022` and enter token as password
- run `nohup <my-command> &`
  - this logs stdout to nohup.log and job will continue to run even if ssh terminal is closed.
  
The above isn't too complex, but it might be nice to wrap that in a thin CLI tool similar to kbatch's cli tool.  I'm not particular on the name, but let's say it's "qrunner" for the sake of this example.  The user could pip install qrunner, then do something like
- `qrunner configure --url="<qhub-url>" --token="<JUPYTERHUB_TOKEN>"`
- `qrunner run <my-command> --output my-command-output.log --conda-env my-env`
which simply runs the command prefaced by `nohup conda run -n my-env`, and directs the stdout to `my-command-output.log`.

**Comment by Adam-D-Lewis** [comment]
Other options to consider:
- https://github.com/Quansight/jhub-client
- https://argoproj.github.io/argo-workflows/ 
- https://argoproj.github.io/argo-events/

**Comment by Adam-D-Lewis** [comment]
Yason
=====
- last non-trivial commit was May 31, 2019
- looked similar to jupyterflow, but Yason only runs notebooks so I think we'd prefer Jupyterflow over Yason.

**Comment by Adam-D-Lewis** [comment]
Jupyterflow
=========
CLI tool that will launch an environment similar to jupyter user pod via an Argo workflow
Can specify simple dependencies (a bit clunky, but works)
Seems stagnant for a year (last commit Mar 1, 2021)
Can schedule workflows via cron syntax in workflow file
Has option to override cpu, memory, nodeSelector, etc.
Uses same image as jupyteruser by default, so we'd need to override either:
	- 1) volume mount (include conda envs mount also)
	- 2) container image (include conda store image)
No helm chart, so some custom work needed here
	- deploy argo workflows CRD somehow
	- some work to expose Argo Workflows Web UI?
- jupyterflow package has various dependencies
- no reporting except what you get by default with Argo Workflows

Jupyterflow Example Usage
------------------------------------------
```yaml
# workflow.yaml
jobs:
- papermill input.ipynb
- python train.py softmax 0.5
- python train.py softmax 0.9
- python train.py relu 0.5
- python train.py relu 0.9
- python output.py

# Job index starts at 1.
dags:
- 1 >> 2
- 1 >> 3
- 1 >> 4
- 1 >> 5
- 2 >> 6
- 3 >> 6
- 4 >> 6
- 5 >> 6
```
then `jupyterflow run -f workflow.yaml`

**Comment by Adam-D-Lewis** [comment]
Hera / Cooler
==========
- These are unrelated, but similar projects that are both like a python SDK for Argo Workflows.
- They both seem a bit young, without great documentation, so less experienced users may have a tough time using them.
- I'd like to look more into these though, as I think they could potentially fit for our use case.

**Comment by iameskild** [comment]
# Argo Workflow

I played around with Argo Workflow today and got a few sample workflows to run using the `argo` CLI. This was fairly trivial once you have a Kubernetes cluster up and running (I was doing so on QHub deployed on Minikube). 

Working with Argo Workflow requires an `argo-server` running on the cluster (installed from a `kubectl apply` command), and then to interact with it, you'll need the aforementioned `argo` CLI. Argo does seem to have a [`argo-helm` repo](https://github.com/argoproj/argo-helm/tree/master/charts/argo-workflows) which might be useful if/when we want to integrate it into QHub.

From skimming the docs for many of the tools listed above, it seems like many of them either require or will play nicely with Argo Worklow.
- Kedro has a page dedicated to ["Deployments with Argo Workflow"](https://kedro.readthedocs.io/en/stable/10_deployment/04_argo.html)
- Yason is tool that requires either Papermill or Argo Workflow, [see prerequisites](https://yason.readthedocs.io/en/latest/#prerequisites).
- Jupyterflow is another tool that seems to require Argo Workflow, [see install docs](https://jupyterflow.com/jupyterhub/#install-argo-workflow-engine).

The gap that exists with Argo Workflow is how to enable users to launch these workflows from JupyterLab. Yason or Jupyterflow might be possible solutions. My main concern around these two tools is that they both seem to be maintained by individuals.

In the same vain as Hera, Argo Workflow seems to have an [existing Python SDK](https://github.com/argoproj/argo-workflows/tree/master/sdks/python).

**Comment by Adam-D-Lewis** [comment]
I'm curious to learn more about the visualizations/reporting in Argo Workflows. I'm also not clear on how authentication/authorization would work.  Maybe we don't need to worry about it just yet though.

**Comment by dharhas** [comment]
So it sounds like Argo is a strong contender for the base layer of our integrated workflow solution and then on top of it we could potentially have multiple client side tools leveraging it.

- something simple like reviving/forking jupyterflow and connecting it to conda-store for environments
- papermill
- other tools like mentioned above

@trallard

**Comment by trallard** [comment]
Argo is a really versatile orchestrator engine - not only it integrates well with other pipeline/Ml tools but opens up loads of possibilities for CI driven ML workflows. I think is it a good bet in terms of flexibility and extensibility for Qhub and its users

**Comment by trallard** [comment]
@dharhas @Adam-D-Lewis  are we planning to explore more options?

**Comment by dharhas** [comment]
Well, I don't think we need to explore more options per se but the current integrations are not fully complete. i.e.

1. kbatch - this is integrated and works but requires specifying a docker image and also does not have the user volumes mounted so it isn't very straightforward to use
2. argo workflows - this is integrated on the backend but we do not yet understand the best way to use it from user space (i.e python or jupyter)

The above should probably opened as new issues and this can be closed.

**Comment by iameskild** [comment]
Argo-Workflows has been integrated. This can be closed 🎉
