### ISSUE TITLE
[ENH] - Enable users to schedule computations via UI with optional reporting

### ISSUE THREAD

**Issue by Adam-D-Lewis** [nebari-dev/nebari#1099]
### Feature description

Once a user develops a script or Jupyter notebook that does a particular computation, there is often a need to rerun these computations on a schedule and send notifications or results to a list of people. This feature would have a UI and framework that allows the user to do this with a few clicks.

### Value and/or benefit

-

**Comment by iameskild** [comment]
kbatch has already been added but in order to use it to schedule jobs, we opened [this PR](https://github.com/kbatch-dev/kbatch/pull/40). Once the PR is merged, kbatch will need to cut a new release and then we can update the version here.

**Comment by iameskild** [comment]
Superceded by #1755
