### ISSUE TITLE
[bug] Nebari Logout should also log out of conda-store and grafana

### ISSUE THREAD

**Issue by danlester** [nebari-dev/nebari#1120]
If the user clicks Logout within the /hub/home page of Nebari, they are logged out of JupyterHub and Keycloak but not Conda Store or Grafana (and maybe others).

They should be logged out.

Those services should have a /logout endpoint that accepts a redirect_uri query parameter, and then they need to be added to the `final_logout_uri` chain in Terraform (see `input_vars.py` how this is already done for Keycloak and tf_extensions).

**Comment by pavithraes** [comment]
@viniciusdc suggested we can solve the grafana portion with https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/auth-proxy/

**Comment by pavithraes** [comment]
Closing in favour of #2067 :)
