### ISSUE TITLE
[ENH] - Adding Conda-Store, JupyterHub, Traefik, Keycloak Grafana Dashboards

### ISSUE THREAD

**Issue by costrouc** [nebari-dev/nebari#1127]
### Feature description

Currently the Grafana dashboards for these services are already added but the metrics are not being fetched. In order to fix this we need to add the prometheus scraping operators to get the configuration. Simlar to the example [here](https://github.com/prometheus-operator/prometheus-operator/blob/main/example/user-guides/getting-started/example-app-service-monitor.yaml). The catch is that this requires a custom resource definition. CRDs cannot be used and defined within the same step https://github.com/hashicorp/terraform-provider-kubernetes/issues/1367. Unless this issue is resolved this is complex to solve.

The most promising plan would be to use the [kubectl provider](https://registry.terraform.io/providers/gavinbunney/kubectl/latest/docs) 

### Value and/or benefit

Users can see monitoring from all their services.

**Comment by Adam-D-Lewis** [comment]
Adding a note in case it's useful.  Though a CRD sounds like a potentially better solution, we did have a workaround in the Prometheus config in the past (https://github.com/Quansight/qhub/pull/797/files).

**Comment by Adam-D-Lewis** [comment]
@costrouc When adding kubectl provider, we'll need to add credentials, right?

```
provider "kubectl" {
  host                   = var.eks_cluster_endpoint
  cluster_ca_certificate = base64decode(var.eks_cluster_ca)
  token                  = data.aws_eks_cluster_auth.main.token
  load_config_file       = false
}
```

I see these outputs are output in stage 2, but we don't have a way to get them from stage 2 to stage 7, do we?
