### ISSUE TITLE
[BUG] - kubespawner_overrides end up influencing future profile launches

### ISSUE THREAD

**Issue by costrouc** [nebari-dev/nebari#1201]
### OS system and architecture in which you are running QHub

Linux

### Expected behavior

Clicking on any profile within kubespawner should not influence other launches.

### Actual behavior

See above.

### How to Reproduce the problem?

See above.

**Comment by costrouc** [comment]
See:
 -  https://github.com/jupyterhub/kubespawner/issues/546
 - https://github.com/jupyterhub/jupyterhub/issues/3592

So should potentially rename this issue upgrade QHub to use latest jupyterhub 2.2.0+ version.

**Comment by viniciusdc** [comment]
@costrouc did we fix this already? (I think not), based on your previous comment this should be closed and a new issue for bumping the jupyterhub version needs to be created is that correct?

**Comment by iameskild** [comment]
We recently upgrade JupyterHub to v3.1 so I believe we can close this issue for now. Feel free to reopen this if the issue still persists.
