### ISSUE TITLE
Add `dev` flag to qhub CLI

### ISSUE THREAD

**Issue by iameskild** [nebari-dev/nebari#1226]
_This is a follow up from a discussion that @costrouc, @tonyfast, @viniciusdc and I had a few weeks ago._

During the qhub development and testing process, developers often relying on little "tricks" in order to work on or test particular sections of the code. At this point, we have accrued a decent amount of "tech debt" with all of these little "tricks", see [`qhub/utils.py`](https://github.com/Quansight/qhub/blob/main/qhub/utils.py). Here is a list a few annoyances that this `dev` flag might address:
- setting the `qhub_version` in the `qhub-config.yaml` to version used during development or to some other desired version
  - currently relying exporting `QHUB_GH_BRANCH` to set this version
- setting the docker image tags to some desired version 
  -  currently relying exporting `QHUB_GH_BRANCH` to set these tags
- setting the qhub-dask to some desired version
  - currently handled manually
- setting the kubernetes version to some desired version 
  - currently relying on `QHUB_K8S_VERSION`
- for the gitops workflow, it would be nice to preset the version of qhub or branch of qhub to install from 
  - currently relying exporting `QHUB_GH_BRANCH` to set this branch

These are just a few of the things that can be handled with a `dev` flag.

**Comment by costrouc** [comment]
I agree having a feature like this would be useful and help to separate development based additions to qhub.

**Comment by trallard** [comment]
@iameskild  I believe this was now added in the new CLI, do we need to keep this open?

**Comment by iameskild** [comment]
@trallard the associated [PR](https://github.com/nebari-dev/nebari/pull/1610) is still open but I just linked the two :)
