### ISSUE TITLE
[ENH] - Enable long running computations without requiring a browser window to be kept open

### ISSUE THREAD

**Issue by Adam-D-Lewis** [nebari-dev/nebari#1231]
### Feature description

Currently long running computations require a browser window to be kept open for the duration of the computation. Some prototype work has been done to enable ‘background’ and ‘batch’ processes to be run on QHub. 

### Value and/or benefit

This feature would enhance this and make it easily accessible to scientists and engineers using the platform.

**Comment by Adam-D-Lewis** [comment]
Some of this discussion is contained in https://github.com/Quansight/qhub/issues/1098#issuecomment-1075704820

**Comment by viniciusdc** [comment]
Hi @Adam-D-Lewis, just out of curiosity could you provide an example of a long-running computation? (sorry for this strange question, just want to be sure I am on the same page). 

About this,
> Currently long running computations require a browser window to be kept open for the duration of the computation
have you experienced this?

**Comment by iameskild** [comment]
I think we can close this now since we have a few possible solutions, namely Jupyter-Scheduler. @Adam-D-Lewis if you feel differently, feel free to reopen this issue.
