### ISSUE TITLE
[ENH] Update CI/CD workflows to work within community contributors' PRs

### ISSUE THREAD

**Issue by viniciusdc** [nebari-dev/nebari#1301]
Some of our actions require extra secrets to be set in order to work (e.g. Kubernetes tests and cloud providers). Due to this, in the scenario where a new contributor forks the repo, any changes to the future PR will not fail the mentioned test, blocking some pipelines and the reviewing process.

### Task
- Review current test structure to avoid such scenario

### Success criteria 
- The contributor should be able to open a PR to `Quansight/qhub.git@main` from a fork, and the tests should all run, without requiring extra configurations.

**Comment by aktech** [comment]
This was fixed in #1563
