### ISSUE TITLE
[ENH] Re-enable `QHUB_SECRETS` 

### ISSUE THREAD

**Issue by viniciusdc** [nebari-dev/nebari#1303]
We need to re-enable this tooling cited in the [docs](https://docs.qhub.dev/en/stable/source/installation/configuration.html?highlight=qhub_#omitting-sensitive-values). Which was originally created to solve #13.

**Comment by trallard** [comment]
Did we ever consider using sops? 
I've used it before and it's a pretty decent way to handle secrets.

**Comment by viniciusdc** [comment]
But I am really open, and I think the other would be as well, to add something as sops, due to its huge compatibility to a variety of resource (such as Vault)

**Comment by trallard** [comment]
superseded by #787
