### ISSUE TITLE
[ENH] Add helm chart validator 

### ISSUE THREAD

**Issue by viniciusdc** [nebari-dev/nebari#1313]
Recently we ended up having some issues with outdated helm charts and/or missing charts that impacted our deployment greatly. 

I suggest we add some kind of tracking system to have an `index` maintained/generated on the fly for each helm chart been used in the project -- except the ones present as sub-requirements for services.  Then based on this index add a pipeline/pytest to validate the installations.

this addition is not "necessary" as we would encounter all these issues doing the deployments directly or by using the integration tests, though we gain some pre-caution system to spot such issues more easily.

**Comment by viniciusdc** [comment]
related to #1679

**Comment by trallard** [comment]
Is the linked PR then meant to close this issue @viniciusdc?
