### ISSUE TITLE
Bitnami update breaks post `v0.4.0` releases 

### ISSUE THREAD

**Issue by iameskild** [nebari-dev/nebari#1319]
The [recent decision by [bitnami](https://github.com/bitnami/charts/issues/10539) to remove older helm charts from their default index.yaml has essentially broken qhub deploy for all of our post v0.4.0 releases. At this point, I believe it makes sense to cherry-pick [the most recent PR](https://github.com/Quansight/qhub/pull/1308) (which resolves this issue going-forward) and cut a new release asap. I’d be happy to handle this on Wednesday (June 8th).

**Comment by trallard** [comment]
Backport to `0.4.1` and `0.4.0`
