### ISSUE TITLE
[MAINT] Validate Kubernetes APIs calls 

### ISSUE THREAD

**Issue by viniciusdc** [nebari-dev/nebari#1324]
We've been recently upgrading some outdated Kubernetes API calls from the current providers and resources, but I noticed the following message in all of our current deployments on GCP:

> This cluster will not be scheduled for an automatic upgrade to v1.22, the next minor version, because your API clients have used deprecated APIs in the last 30 days that are no longer available in this version. Once the cluster reaches end of life on v1.21, it would then be automatically upgraded to v1.22, but upgrading the cluster before it’s migrated to updated APIs could cause it to break. [Learn more](https://cloud.google.com/kubernetes-engine/docs/deprecations/apis-1-22?_ga=2.21615804.-667931447.1631627336)

The respectively deprecated APIs seems to be targeting this resource:
> /apis/extensions/v1beta1/ingresses

We need to look over the main code and:
- Inspect the current provider's pins to check for an outdated version that is still using that `v1beta1` API
- Inspect helm charts that might be using an outdated version that uses the same API

Note: the current GCP deployments are still using the `v0.4.1` version, which does not include some of the recent helm chart updates, which means that we might have already fixed this for `v0.4.2`, though a good inspection is needed to verify.

**Comment by iameskild** [comment]
If we regularly upgrade Kubernetes and the relevant terraform providers, this shouldn't be an issue. The most recent example of this is #1849.
