### ISSUE TITLE
[ENH] - Add `--dry-run` option to qhub installation

### ISSUE THREAD

**Issue by viniciusdc** [nebari-dev/nebari#1368]
### Feature description

The Terraform Provision and Terraform Apply steps in the `qhub deploy` could be executed as a `dry run,` just like running the [terraform plan](https://www.terraform.io/docs/commands/plan.html) command.

The dry run would refresh the state file (if present) and generate a deployment plan based on the provided qhub infrastructure but not apply the plan. 

### Value and/or benefit

The benefits of doing so would be:

- Generating the qhub full infrastructure model and exporting/importing it to proper locations if needed -- infra cost might be able to use this for better predictions
- CI testing, we could then mimic the installation process and run these (without deploying an instance) into different architectures, like Windows, Linux, and macOS. This would help cathing situations such as https://github.com/Quansight/qhub/issues/1367
- We would also be able to inspect the outputted plan and compare it with a pre-defined test template to assert versions, providers, and config maps are all well-defined and present.

### Anything else?

https://github.com/Quansight/qhub/issues/93 initially proposed this

**Comment by trallard** [comment]
There is a `dry-run` flag now in the CLI, is this issue still relevant? it seems it is now not applicable

see https://github.com/nebari-dev/nebari/blob/784ab8147ef01a6eaa443c047dd9666e3722c49a/nebari/cli/main.py#L231

**Comment by trallard** [comment]
ok since the other issue has more information I am going to close this as a duplicate and carry on with the discussion there
