### ISSUE TITLE
Does the GCP kubernetes API upgrade affect us?

### ISSUE THREAD

**Issue by iameskild** [nebari-dev/nebari#1415]
The GCP console has a warning message that we might need to investigate further:

> This cluster will not be scheduled for an automatic upgrade to v1.22, the next minor version, because API clients in your cluster have used APIs in the last 30 days that are removed in this version. Once the cluster reaches end of life on v1.21, it could then be automatically upgraded to v1.22, but upgrading the cluster before it’s migrated to updated APIs could cause it to break.

Potentially affected resources:
- `/apis/networking.k8s.io/v1beta1/ingressclasses`
- `/apis/extensions/v1beta1/ingresses`
- `/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions`

**Comment by viniciusdc** [comment]
Yes, this will probably affect us in the future. I guess that our helm chart for traefik is outdated. The deprecation is due to [this](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122)

**Comment by iameskild** [comment]
Hey @amjad489, thanks for the feedback! I have not yet run into this, could you please share your `qhub-config.yaml` file and any logs that you've captured?

**Comment by iameskild** [comment]
@amjad489 I believe I'm experiencing the same issue you are. See this issue #1488 for more details and this PR #1489 for a possible resolution :)

**Comment by trallard** [comment]
Closing as this was fixed in #1489
