### ISSUE TITLE
Open PR to update any `qhub` instances/references in CI/CD (not to be merged until after transferring the repo)

### ISSUE THREAD

**Issue by trallard** [nebari-dev/nebari#1453]
Targets 

- [x] https://github.com/Quansight/qhub-integration-test
- [x] https://github.com/Quansight/qhub

open against https://github.com/Quansight/qhub/tree/2022.10.1

**Comment by trallard** [comment]
Also, the repos from which we deploy Quansight's QHub's instances (which I cannot remember now)

**Comment by iameskild** [comment]
Mostly completed:
- https://github.com/Quansight/qhub/pull/1480
- https://github.com/Quansight/qhub-integration-test/pull/36

**Comment by trallard** [comment]
- TODO: Update paths in CI/CD files

**Comment by trallard** [comment]
Are there any outstanding items here @viniciusdc  @iameskild ?

**Comment by iameskild** [comment]
Just updating the paths in the CI/CD files.

**Comment by trallard** [comment]
After migration: Update integration tests 🤔

**Comment by viniciusdc** [comment]
I think we can close this once #1498 is merged, right? We can then address IT in another place as that would be internal for a while... and as @aktech commented, we can still use the same paths/pointers to the old repo for some time (though we will definitely move it under the next few days)

**Comment by iameskild** [comment]
@viniciusdc besides updating the IT README and transferring it to the nebari-dev org, it has been cleaned up. See this [PR](https://github.com/Quansight/qhub-integration-test/pull/37).

**Comment by viniciusdc** [comment]
wonderful, did you clear each one of the integration tests repo (providers)? or did they already have the nebari-config.yaml files?

**Comment by viniciusdc** [comment]
> @viniciusdc besides updating the IT README and transferring it to the nebari-dev org, it has been cleaned up. See this [PR](https://github.com/Quansight/qhub-integration-test/pull/37).

wonderful, did you clear each one of the integration tests repo (providers)? or did they already have the nebari-config.yaml files?

**Comment by iameskild** [comment]
> > @viniciusdc besides updating the IT README and transferring it to the nebari-dev org, it has been cleaned up. See this [PR](https://github.com/Quansight/qhub-integration-test/pull/37).
> 
> wonderful, did you clear each one of the integration tests repo (providers)? or did they already have the nebari-config.yaml files?

At the moment, those repos contain both `qhub-config.yaml` and the new `nebari-config.yaml`.

**Comment by iameskild** [comment]
Done 🎉
