### ISSUE TITLE
END-GAME -  For `qhub` change the cirun config to have a different repo `quansight/qhub` → `nebari-dev/nebari`

### ISSUE THREAD

**Issue by trallard** [nebari-dev/nebari#1459]

**Comment by aktech** [comment]
Cirun is working on this repo now: https://github.com/nebari-dev/nebari/actions/runs/3329555513/jobs/5506925312

**Comment by viniciusdc** [comment]
Based on the above comment, I will be closing this as completed, c.c. @trallard
