### ISSUE TITLE
[ENH] - Submit workflows to Argo-Workflow from JupyterLab server

### ISSUE THREAD

**Issue by iameskild** [nebari-dev/nebari#1495]
### Feature description

At the moment, there is no easy way to submit workflows to Argo-Workflow other than using their UI. It would be a better user experience if we could submit workflows from within the JupyterLab pod. 

### Value and/or benefit

This allows users to submit their workflows where they work. 

### Anything else?

See https://github.com/Quansight/qhub/issues/1230 for more details.

**Comment by kcpevey** [comment]
Hera can be used to submit workflows from the jupyterlab server (via python instead of the yaml UI). I've got some examples and I'm working on adding them to nebari documentation because the process is NOT straightforward.

**Comment by dcmcand** [comment]
We can use the scheduler functionality to run notebooks using argo-workflows currently. If there are other use cases needed, please open more specific tickets.
