### ISSUE TITLE
[BUG] - CDSDashboards env box showing all available namespaces

### ISSUE THREAD

**Issue by viniciusdc** [nebari-dev/nebari#1497]
### OS system and architecture in which you are running QHub

Linux

### Expected behavior

- User should only be able to view-select environment based on his permission level, this is:
  - user-namespace, 
  - nebari-git,
  -  global and 
  - group namespaces 

### Actual behavior

With the recent changes made after `v0.4.5` release, it's now possible to visualize all available dashboard environments, including environments on other user namespaces.

### How to Reproduce the problem?

Login in with two different users on a Nebari deployment, and create two dashboard environments (can be a copy of the built-in one) into the user's respective namespaces

### Integrations

dashboards

**Comment by iameskild** [comment]
We have recently dropped support for CDS Dashboards. Closing.
