### ISSUE TITLE
[ENH] - Support AKS-managed Azure Active Directory RBAC

### ISSUE THREAD

**Issue by TomAugspurger** [nebari-dev/nebari#1500]
### Feature description

Some organizations have policies in place requiring certain features be enabled on AKS. For example, this subscription has a policy requiring that [AKS-managed Azure Active Directory integration](https://learn.microsoft.com/en-us/azure/aks/managed-aad#azure-ad-authentication-overview) be enabled. Trying to deploy qhub within this subscription fails with

```
[terraform]: │ Error: creating Cluster: (Managed Cluster Name "qhpc-dev" / Resource Group "qhpc-dev"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=403 -- Original Error: Code="RequestDisallowedByPolicy" Message="Resource 'qhpc-dev' was disallowed by policy.  Policy" Message="Resource 'qhpc-dev' was disallowed by policy. Policy identifiers: '[
```

If I were using terraform directly, I would set the flag [`azure_rbac_enabled = true`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#azure_rbac_enabled) in the `azurerm_kubernetes_cluster` config.

Reading https://docs.qhub.dev/en/stable/source/installation/configuration.html?highlight=terraform#terraform-overrides, I couldn't tell if I could override arbitrary pieces of the terraform config. It looks like only specific things are allowed (e.g. `azure.terraform_overrides.private_cluster_enabled: true`. I wasn't sure if I could target something like `azure.terraform_overrides.kubernetes.azure_rbac_enabled: true`

So this feature request would be for a way to override specific values at any point in the terraform config, or a specific config option for this to plumb all the way down to terraform.

### Value and/or benefit

Unsure.

**Comment by iameskild** [comment]
Hi @TomAugspurger, thanks for the enhancement request! Doubling checking real quick, it sounds like you're right, passing the desired variable to `terraform_overrides` will likely not have the effect you're hoping for. 

As for how this might be implemented, we would likely need to add `managed` and `azure_rbac_enabled` as optional keys in the `azure` section of the `qhub-config.yaml` which would then propagate to the terraform scripts. Does that sound reasonable to you?

**Comment by TomAugspurger** [comment]
Yeah, perhaps. Thought it might be good to verify that this will actually fix the problem. If I get a chance today I'll test out manually modifying `stages/02-infrastructure/azure/modules/kubernetes/main.tf` and rerunning `qhub deploy`. Would you expect that to work, or would my local changes perhaps to the terraform source be overwritten?

**Comment by iameskild** [comment]
@TomAugspurger after you make the desired changes directly to the terraform scripts, you can ensure your changes are not overwritten by passing `--disable-render`:

```bash
qhub deploy -c qhub-config.yaml --disable-render
```

**Comment by pavithraes** [comment]
This was a niche feature, please feel free to re-open if needed. :)
