### ISSUE TITLE
[RELEASE] `2022.10.1` - first CalVer release 🎉

### ISSUE THREAD

**Issue by iameskild** [nebari-dev/nebari#1504]
# Release Checklist

## Release details

Scheduled release date - TBD

Release captain responsible - @iameskild 

## Starting point - a new release is out

- [x] Create *this* issue to track and discuss the upcoming release.
- [x] Use the previous release issue for any final release-specific discussions, then close.
  - This can be a good time to debrief and discuss improvements to the release process.

## Looking forward - planning

- [x] [Create milestone for next release](https://github.com/nebari-dev/nebari/milestones) (if it doesn't already exist) and link it back here.
- [x] Triage `bugs` to determine what be should included in the release and add it to the milestone.
- [x] What new features, if any, will be included in the release and add it to the milestone.
  - This will be, in large part, determined by the roadmap.
  - Is there a focus for this release (i.e. UX/UI, stabilitation, etc.)?

## Pre-release process

- [x] Decide on a date for the release.
  - What outstanding issues need to be addressed?
  - Has documentation been updated appropriately?
  - Are there any breaking changes that should be highlighted?
  - Are there any upstream releases we are waiting on?
  - [Do we need to update the `dask` versions in the `nebari-dask`?](https://github.com/conda-forge/nebari-dask-feedstock/blob/main/recipe/meta.yaml#L13-L16)
  - Will there be an accompanying blog post?
- [x] Prepare for the release.
  - [x] Announce build freeze.
  - [x] Release Candidate (RC) cycle.
    - [x] Perform end-to-end testing. [Use the Testing Checklist template.](https://github.com/nebari-dev/nebari/issues/new?assignees=&labels=type%3A+release+%F0%9F%8F%B7&template=testing-checklist.md&title=Testing+checklist+for+<version>)
      - For minor releases, relying on the end-to-end integration tests might suffice.
      - #1522 
    - [x] [Cut RC via GHA release workflow (w/ "This is a pre-release" checked).](https://github.com/nebari-dev/nebari/releases/new)
    - [x] End-user validation.
      - If possible, pull in volunteers to help test.
      - (Repeat steps if necessary)
  - [x] [Update `RELEASE.md` notes.](https://github.com/nebari-dev/nebari/blob/main/RELEASE.md)

## Cut the official release

*These steps must be actioned in the order they appear in this checklist.*
- [x] [Tag, build and push docker images](https://github.com/nebari-dev/nebari-docker-images/releases/new)
- [x] [Update and cut release for `nebari-dask` meta package on Conda-Forge.](https://github.com/conda-forge/nebari-dask-feedstock)
- [x] [Cut PyPI release via GHA release workflow.](https://github.com/nebari-dev/nebari/releases/new)
    - Copy release notes from `RELEASE.md`.
- [ ] [Merge automated release PR for `nebari` on Conda-Forge.](https://github.com/conda-forge/nebari-feedstock)

**Comment by iameskild** [comment]
Blocked until complete switch over from QHub --> Nebari

**Comment by trallard** [comment]
Notes on the checklist items 

- [ ] Update..... `nebari-dask` meta package should point to the `nebari-dask` 

Also should this not be updated in the Docker images? (see https://github.com/nebari-dev/nebari-docker-images/blob/main/dask-worker/environment.yaml)
And if so we might need to change the order: update and release `nebari-dask` -> update Docker images -> tag and push Docker images

- [ ] Merge automated PR for `nebari`

This checklist still references `qhub` all over the place so we need a PR to fix this (we have #1451 for this)

**Comment by iameskild** [comment]
RC1 is available on PyPI: https://pypi.org/project/nebari/2022.10.1rc1/
