### ISSUE TITLE
[DOC] - Install Nebari commands don't work on https://www.nebari.dev/docs/get-started/installing-nebari/#how-to-install-nebari

### ISSUE THREAD

**Issue by Adam-D-Lewis** [nebari-dev/nebari#1534]
The conda and mamba install commands listed at https://www.nebari.dev/docs/get-started/installing-nebari/#how-to-install-nebari don't work currently.  I'm assuming because the package is still listed as qhub on conda-forge?
`conda install nebari -c conda-forge`
`mamba install nebari`

**Comment by alibama** [comment]
Hey Adam - see if this fixes it for you?  
https://github.com/nebari-dev/nebari/issues/1524

**Comment by iameskild** [comment]
Thanks for the reminder @Adam-D-Lewis!

cc @viniciusdc

**Comment by viniciusdc** [comment]
@Adam-D-Lewis, the conda command does not work because the package is still under staged. We still need to publish that on conda-forge. I already opened a PR for that, but the win_64 build is currently failing. I hope to get this fixed by today

**Comment by viniciusdc** [comment]
This now can be closed, `nebari` is now available at conda via the conda-forge channel.
