### ISSUE TITLE
[BUG] - matplotlib widget doesn't work in notebook - model not found

### ISSUE THREAD

**Issue by kalpanachinnappan** [nebari-dev/nebari#1539]
### OS system and architecture in which you are running Nebari

GCP K8s cluster

### Expected behavior

```
%matplotlib widget
import matplotlib.pyplot as plt

plt.plot([1,2,3], [1,2,3])
plt.show()
```

the above should show a plot.

### Actual behavior

get an error:

```
Error displaying widget: model not found
```
<img width="432" alt="Screen Shot 2022-11-11 at 6 29 46 PM" src="https://user-images.githubusercontent.com/118010469/201452491-85b5fa46-5fae-4278-a458-7419b18706c6.png">

### How to Reproduce the problem?

1. add `ipympl` package to the default `dashboard` conda environment
2. run the following in a notebook using the default `dashboard` conda environment:

   ```
   %matplotlib widget
   import matplotlib.pyplot as plt

   plt.plot([1,2,3], [1,2,3])
   plt.show()
   ```

### Command output

```bash session
%matplotlib widget
import matplotlib.pyplot as plt

plt.plot([1,2,3], [1,2,3])
plt.show()
```
```


### Versions and dependencies used.

- needed to install `ipympl` first in the `dashboard` conda environment

### Compute environment

GCP

### Integrations

conda-store

### Anything else?

_No response_

**Comment by dharhas** [comment]
@iameskild ipympl may be a jupyterlab extension that needs to be installed in the jlab docker image similar to other lab extensions. Something to check into.

**Comment by iameskild** [comment]
Hi @kalpanachinnappan, I was able to reproduce this issue and as far as I can tell this appears like an upstream issue:
- https://github.com/matplotlib/ipympl/issues/456
- https://github.com/matplotlib/ipympl/issues/473

@dharhas the [ipympl doc](https://matplotlib.org/ipympl/installing.html#jupyterlab-3)s have a call out to use the jupyterlab extension for jupyterlab < 3.0 but this might still be the case and definitely worth testing.

**Comment by dharhas** [comment]
I think my comment is still relevant. I'm pretty sure that the ipympl package needs to be in the conda environment that jlab is served from and not the conda envs being used as kernels. In local settings those are typically the same but not in JupyterHub.

**Comment by iameskild** [comment]
@dharhas I was in agreement :)

**Comment by iameskild** [comment]
I added `ipympl` to the base `nebari-jupyterlab` image and successfully test it locally. This also didn't require pinning the jupyterlab version 💪 

Here is a PR for to get this working:
https://github.com/nebari-dev/nebari-docker-images/pull/39

**Comment by kalpanachinnappan** [comment]
That's great @iameskild, thank you!! 
Let me know the new version of the base image, and I'll test it out in our cluster.
