### ISSUE TITLE
[BUG] - scaling issues in GCP K8s cluster

### ISSUE THREAD

**Issue by kalpanachinnappan** [nebari-dev/nebari#1540]
### OS system and architecture in which you are running Nebari

GCP K8s cluster

### Expected behavior

K8s cluster is online and nodes are scaling as expected.

### Actual behavior

2 scaling issues seen in GCP K8s Engine page:

<img width="638" alt="Screen Shot 2022-11-11 at 6 35 40 PM" src="https://user-images.githubusercontent.com/118010469/201452742-f4a87ce4-682c-415a-ac1f-0b2569353c32.png">

<img width="613" alt="Screen Shot 2022-11-11 at 6 35 20 PM" src="https://user-images.githubusercontent.com/118010469/201452746-c3d612ad-3b3c-427d-9b79-2d9faae9b0f5.png">

<img width="616" alt="Screen Shot 2022-11-11 at 6 35 25 PM" src="https://user-images.githubusercontent.com/118010469/201452749-cbba17d3-22d8-40b9-bf79-0314b025cdaa.png">

### How to Reproduce the problem?

Create a Nebari K8s cluster in GCP using default `nebari-config.yaml`.

### Versions and dependencies used.

- `1.23.8-gke.1900` ([link](https://cloud.google.com/kubernetes-engine/docs/release-notes))
- Nebari version `v2022.10.1`

### Compute environment

GCP

**Comment by iameskild** [comment]
Hi @kalpanachinnappan, thanks for brining this to our attention. 

I have not seen this issue before and I am having a difficult time recreating it. 

Have you had a chance to test the autoscaler on your cluster? To do this you can try having multiple users launch JupyterLab servers at the same time. Or can scale the `worker` node pool by creating a dask cluster and launching 5-10 dask workers ([this gist](https://gist.github.com/iameskild/1a45cbd114595fa371d2d127448c5e33) may be helpful in that regard). In either instance, using `kubectl` or `k9s` you should the autoscaler bring new nodes online.

Lastly, is it possible to get access to the GCP logs (from the `LOGS` button)?

**Comment by kalpanachinnappan** [comment]
@iameskild Thank you for looking into this!

Interesting, I checked back on my K8s cluster and the scaling warnings are gone now 🤔 

I went back in time in Logs though, I've attached them here.

"not backed by a controller" logs: [nebari-k8s-scaling-warnings_2.csv](https://github.com/nebari-dev/nebari/files/10024313/nebari-k8s-scaling-warnings_2.csv)

"failing scheduling predicate" logs: [nebari-k8s-scaling-warnings.csv](https://github.com/nebari-dev/nebari/files/10024336/nebari-k8s-scaling-warnings.csv)

**Comment by iameskild** [comment]
@kalpanachinnappan thanks for the logs! Based on another conversation we had, this seems to no longer be an issue for you. I tried looking through the logs but nothing jumped out. I'm going to close this for now but if this comes up again we can do a deeper RCA 👍
