### ISSUE TITLE
[DOC] - Update QHub HPC section in `README.md`

### ISSUE THREAD

**Issue by pavithraes** [nebari-dev/nebari#1542]
Ref: https://github.com/nebari-dev/nebari#qhub-hpc

- [ ] Rename it to Nebari HPC
- [ ] Update/remove the image "High-level illustration of Nebari architecture"
- [ ] Remove/update link to "blog post" (As noted by @vfdev-5 in #1553)

**Comment by trallard** [comment]
I am working on an update for the README so will add this to the PR
