### ISSUE TITLE
[BUG] - <title> failed to get ip?

### ISSUE THREAD

**Issue by alibama** [nebari-dev/nebari#1546]
### OS system and architecture in which you are running Nebari

unbuntu on aws

### Expected behavior

couldnt get the ip = 

i'm wondering if it's because the load balancer is in aws west and my ec2 controlling it is in aws east?

Attempt 10 failed to get IP for ab2a183a14bd14b0ab79c9217b685ca8-1799603242.us-west-2.elb.amazonaws.com...
ERROR: After stage directory=stages/04-kubernetes-ingress unable to connect to ingress host=ab2a183a14bd14b0ab79c9217b685ca8-1799603242.us-west-2.elb.amazonaws.com port=80

### Actual behavior

didn't find an ip 

### How to Reproduce the problem?

vanilla init on aws ubuntu 20

**Comment by alibama** [comment]
closing this = needed to set cname to load balancer

**Comment by iameskild** [comment]
Hi @alibama, thanks for following up :)

**Comment by dharhas** [comment]
does this need to be clarified in docs?

**Comment by pavithraes** [comment]
> does this need to be clarified in docs?

Yes it does! Re-opening and moving to the docs repo. Thanks,`@dharhas` and `@alibama`. :)
