### ISSUE TITLE
[ENH] - Connect to external data sources

### ISSUE THREAD

**Issue by iameskild** [nebari-dev/nebari#1547]
### Feature description

At the moment it is relatively simple to connect to object storage (S3/GCS) but it would be extremely useful to also connect to other external data sources such as data warehouses (RedShift/BigQuery). 

### Value and/or benefit

Data scientists often connect to data warehouses to pull data for their analyzes and models.

### Anything else?

It is also important to be able to access to these external data sources in an easily manageable manner (either through Keycloak or other means).

**Comment by iameskild** [comment]
To get access to external data sources (such as BigQuery), service-account credentials are needed. There are a few ways in which these credentials can be added to user pods, I have listed them below in increasing order of difficulty which is also in increasing order of security.
1. Add the the service-account credentials in a shared folder (i.e. `/shared/analyst`). This solution is already available and simply requires generating those credentials and saving them in the shared folder appropriately.
    - Pros: 
      - Very easy to get started
    - Cons:
      - Anyone with access to this folder can clobber these credentials (this can be prevented by modifying the file permission)
      - Not very secure - viewable by anyone who has access to to this shared folder
2. Add service-account credentials as a Kubernetes Secret and mount secret to each user pod.
    - Pros:
      - Moderately simple to implement
    - Cons:
      - Less secure - potentially viewable in the filesystem if users know where to look
3. Add service-account credentials via annotations and add them to each user pod
    - Pros:
      - With some additional dev work, different credentials can be added for users in different Keycloak groups.
    - Cons:
      - Less secure - potentially viewable in the filesystem if users know where to look
4. Integrate a secret management tool like [Hashicorp Vault](https://www.vaultproject.io/) or [Mozilla SOPS](https://github.com/mozilla/sops) 
    - Pros:
      - Highly secure secret management
      - Enables administrators to define who gets access to which credentials
    - Cons:
      - Much heavier lift to integrate

**Comment by trallard** [comment]
- Example from 2i2c infra on using sops: https://compass.2i2c.org/en/latest/engineering/secrets.html#secrets-sops
- How to rotate/change secrets with sops: https://infrastructure.2i2c.org/en/latest/topic/access-creds/secrets.html?highlight=secrets
- sops basic usage: https://github.com/mozilla/sops#examples and https://github.com/mozilla/sops#usage
-

**Comment by iameskild** [comment]
Blocked until we decide on a secret management strategy.

**Comment by dcmcand** [comment]
Closing. Once secrets management is in place, users can import data using the data providers sdk directly in their notebooks
