### ISSUE TITLE
[BUG] - keycloak root password not working

### ISSUE THREAD

**Issue by alibama** [nebari-dev/nebari#1548]
### OS system and architecture in which you are running Nebari

unbuntu on aws

### Expected behavior

i see the root login and password, and went to https://<root-dns>/auth/admin and type in root + the 1-time password and get rejected.... it took me a couple of time to get the install script to work = is there a chance i have the wrong password and if so how to i reset it?

### Actual behavior

not logging in

### How to Reproduce the problem?

vanilla aws ubuntu install

**Comment by iameskild** [comment]
Hi @alibama, I'm sorry to hear you're running into issues. Did you reuse the same `nebari-config.yaml` for all subsequent deployments? 

Along with storing the `initial_root_password` in the `nebari-config.yaml`, this password is also printed to the terminal screen at the end of the deployment. Have had a chance to try this one?

**Comment by alibama** [comment]
no - i deleted the nebari-config for subsequent deployments - since i was having issues i just started over each time?

also the root password in nebari config is the same one that's been printed to the screen and doesn't work

**Comment by alibama** [comment]
i solved it by running destroy and re-initializing

**Comment by iameskild** [comment]
Hi @alibama, thanks for following up on this. It's too bad that you needed to redeploy to get around this issue. Besides instances in which the user changes the `root` user password manually ([docs for reference](https://nebari-docs.netlify.app/docs/how-tos/configuring-keycloak#change-keycloak-root-password)) and then forgets this new password, I have not come across this issue. If this happens again, feel free to reopen this issue or create a new one.
