### ISSUE TITLE
Sunset `qhub.dev`

### ISSUE THREAD

**Issue by pavithraes** [nebari-dev/nebari#1552]
### Context

We can plan to remove the `docs` folder from this repo, and redirect `qhub.dev` to `nebari.dev`, after all the i[mportant docs pages are moved to `nebari.dev`](https://github.com/nebari-dev/nebari-docs/issues?q=is%3Aissue+is%3Aopen+label%3Aold-doc-migration+).

Timeline: By Q1 2023

### Value and/or benefit

One source of truth for documentation. :)

**Comment by pmeier** [comment]
This should also remove the [`noxfile.py`](https://github.com/nebari-dev/nebari/blob/develop/noxfile.py), since we are only using it for the docs.

**Comment by pmeier** [comment]
In general, we need to purge the docs from multiple parts of the repo. For example

https://github.com/nebari-dev/nebari/blob/051767be9debb0c4ea6c34ac8e804abdc43e80f8/pyproject.toml#L102-L103
