### ISSUE TITLE
[DOC] README.md bad links

### ISSUE THREAD

**Issue by vfdev-5** [nebari-dev/nebari#1553]
### Preliminary Checks

- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/nebari-dev/nebari/discussions

### Summary

In this README.md section: https://github.com/nebari-dev/nebari#cloud-cloud-providers
the following links lead nowhere:

- [High-level illustration of Nebari architecture](https://github.com/nebari-dev/nebari/blob/main/docs/source/images/nebari-cloud_architecture.png)
- For more details, check out the release [blog post](https://www.quansight.com/post/announcing-nebari).

### Steps to Resolve this Issue

> How can the problem be solved? Are there any additional steps required? Do any other pages need to be updated?

FIx links

**Comment by pavithraes** [comment]
Thanks for reporting! We have #1542 to track this, I've added a to-do item for the blog post link there. :)
