### ISSUE TITLE
[DOC] - Add/Update docstrings

### ISSUE THREAD

**Issue by pavithraes** [nebari-dev/nebari#1571]
### Preliminary Checks

- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/nebari-dev/nebari/discussions

### Summary

We need to review the codebase and add/update docstrings where relevant.

These will be available in our API docs. :)

### Steps to Resolve this Issue

TBD

**Comment by Adam-D-Lewis** [comment]
I believe this is out of date, closing.  Feel free to re-open if this issue and add more details if this issue is still relevant.
