### ISSUE TITLE
[ENH] - Increase Usability of k8s Namespaces to Have Separate Destinations for CI Environments

### ISSUE THREAD

**Issue by MaxTechniche** [nebari-dev/nebari#1586]
### Feature description

Figure out a good way to utilize namespaces in Kubernetes (and possible integration into keycloak?), in order to have separate "environments" for CI/CD, e.g. development, testing, production.

Possible separate urls; one for each namespace? (Maybe needs a separate request?)
- dev namespace (nebari.dev.---.com)
- test namespace (nebari.test.---.com)
- prod namespace (nebari.---.com)

### Value and/or benefit

Instead of needing to create or spin up an entirely new k8s cluster if we want to have some separation between our environments, we just have to declare the namespace it uses and can therefore use resources available to that namespace.

I'm not sure how Nebari currently integrates/uses namespaces. I've tried to do some testing with k8s deployments, but in my limited research/knowledge I've had very little success and it was difficult trying to setup up something that uses a different namespace.
With better integration, it will be easier or more straight forward to separate environments using k8s namespaces.

**Comment by dharhas** [comment]
@trallard @costrouc This is something we've talked about needing before and we need to think through an approach.

**Comment by trallard** [comment]
Thanks for the ping Dharhas!

This is something we have on our radar for future implementation and the next step for the team would be to scope the requirements and solutions through a RFD (request for discussions). To follow up on this and start the discussion, @MaxTechniche, what would a full delivery workflow look like in your case? 


Within GitHub we can leverage the use of [deployment environments](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#about-environments) (and the equivalent in GitLab), reduce the need of a `develop` -> `main` merging strategy and keep a "manual" approval/deployment for production. So basically, the `staging` nebari deployment would be promoted to `production` once everything has been tested and checked accordingly.

**Comment by iameskild** [comment]
Closed by https://github.com/nebari-dev/governance/issues/41
