### ISSUE TITLE
[DOC] - Deployment on AWS suggestions for improvement

### ISSUE THREAD

**Issue by rsignell-usgs** [nebari-dev/nebari#1598]
### Preliminary Checks

- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/nebari-dev/nebari/discussions

### Summary

The first time we ran the guided init for AWS, we set only the two AWS credential variables as directed.
We got all the way through the questions and then received the error that GITHUB_USERNAME was not defined:
 ![2022-12-06_13-57-33](https://user-images.githubusercontent.com/1872600/206005203-1c9eeb84-a4ff-4381-8243-6aa55d669f01.png)

We then looked at the code where that error was coming from and it looked like we would need to specify GITHUB_TOKEN as well, using a personal access token.  We figured we might as well set the `AWS_REGION=us-east-1` for good measure.

The 2nd time we ran the guided init, it worked, though the config file generated specified `us-west-2` for some reason.  So we edited the config and changed it to `us-east-1` before proceeding to the `nebari deploy` step.    The nebari deploy then went find.

Notes on running the guided init:
* it was confusing to be asked for the `client_id` and `client_secret` twice during the guided init.  We were thinking we did something wrong. 
* it should be mentioned that the github user running the terraform deploy must have the ability to create repositories. 

### Steps to Resolve this Issue

We set the additional env vars as described above.

@jkellndorfer

**Comment by iameskild** [comment]
@rsignell-usgs thanks for bringing this to our attention. I've opened a PR to fix this: #1605
