### ISSUE TITLE
[ENH] - Specify k8s version and release channel for GCP

### ISSUE THREAD

**Issue by alimanfoo** [nebari-dev/nebari#1608]
### Feature description

When deploying a new instance of nebari on GCP, I'd like to be able to specify both the k8s version and the [release channel](https://cloud.google.com/kubernetes-engine/docs/concepts/release-channels). 

Currently the k8s version can be specified in the nebari config, but not the release channel IIRC. This should be doable in terraform via the [release_channel](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#release_channel) attribute.

Also I'm fairly sure the k8s version given in the nebari config is ignored during deployment. E.g., from a recent deployment I have different values in nebari config (1.23.13-gke.900) from what I ended up getting in the running cluster (1.23.12-gke.1600).

### Value and/or benefit

If the release channel is not specified, the default release channel is used, which is the "regular" channel. However, this can result in k8s upgrades which then remove some k8s API functions that a nebari deployment relies on. This can lead to a state where you cannot run redeployment of an existing nebari service, because the deploy command fails due to k8s API changes. It also generates errors for a running deployment where components like traefik are trying to use API functions that have been removed.

To ensure long-term stability of a nebari deployment, it would be preferable to be able to specify the "stable" channel, or even to specify "no channel" which will give you a static GKE version. 

### Anything else?

This happened to us with a service initially deployed using qhub 0.3. When k8s 1.22 was released into the regular channel, our cluster was upgraded, but several API functions were removed in this upgrade and we could no longer redeploy the service. This forced us to build a new service from scratch and migrate users over.

**Comment by pavithraes** [comment]
@alimanfoo Thanks for this issue!

> Also I'm fairly sure the k8s version given in the nebari config is ignored during deployment. E.g., from a recent deployment I have different values in nebari config (1.23.13-gke.900) from what I ended up getting in the running cluster (1.23.12-gke.1600).

Thanks for sharing, we may want to track this in a separate bug report. :/

**Comment by iameskild** [comment]
Hi @alimanfoo, we recently decided to pin the GKE cluster and part of that required setting the `release_channel = UNSPECIFIED`. I think you make a good suggestion that we should expose `release_channel` as an option for the GKE cluster.
