### ISSUE TITLE
Add custom button/link on JupyterHub launch screen

### ISSUE THREAD

**Issue by kcpevey** [nebari-dev/nebari#1656]
### Context

@iameskild has done a bit of research on this and it looks like [Jupyter_app_launcher](https://jupyter-app-launcher.readthedocs.io/en/latest/index.html) will give us the functionality we need. We just need add an additional button on the existing Jupyterlab launch screen. 

![image](https://user-images.githubusercontent.com/15659110/219435551-475b906f-7ebe-4af8-bf46-c955f5fde064.png)

### Value and/or benefit

For our usecase, this will be an nbgitpuller link which will clone a repo into nebari, though there are a wide variety of usecases for this functionality. 

### Anything else?

The outcome here should be a pattern to follow, successfully launching this on a nebari instance, and a tutorial explaining to others how to do it on their own. 

Ultimately, we may want to use this functionality to ship easy-access examples to users when the [examples folder is deprecated](https://github.com/nebari-dev/nebari/issues/1558).

**Comment by ppwadhwa** [comment]
@kcpevey It seems that we can easily add a button, and we can create a link with nbgitpuller, but it doesn't seem possible to combine this ability right now.  Or at least, I could not get it to work locally.  

@iameskild and I met today to discuss this.  He had not been able to get these 2 to work together either.  We tried the following:

1.  Adding a button, and trying to open the link produced by nbgitpuller.  It will not open either in the nebari hub, or from the local jupyter instance.  Changing the address a bit did not help this. We could get it to open up another jupyter lab session in a jupyter lab window, but not grab the git repo.
2. There is an example on jupyter app launcher that will run a streamlit app. It has some args that you can specify a command to run.  We tried to open the webpage from there.  It will attempt to open a new window from a new port, but still no github repo.  
3. The same command line approach as #2, but instead I tried to see if it would clone the repo.  It does not and it freezes.  
4. We also tried to see if there was a way to open a jupyter notebook from the terminal, thus giving us a command we could potentially use in a shell script, but it is not possible at the moment.  https://github.com/jupyterlab/jupyterlab/issues/5056

We could open a notebook from a button, which if the user runs through it, they can have an intro to nebari that can clone or update repos and open them up?    Any other thoughts on a direction to take?

@iameskild did I miss anything?

**Comment by pavithraes** [comment]
@iameskild @aktech  Do you know if the work in https://github.com/nebari-dev/jhub-apps will supersede this issue?

**Comment by kcpevey** [comment]
Yes, I will close this since the App Launcher will provide equivalent functionality.
