### ISSUE TITLE
Meta issue - `conda-store-ui` integration

### ISSUE THREAD

**Issue by iameskild** [nebari-dev/nebari#1670]
The latest version of `jupyterlab-conda-store==0.2.7` is now ready for testing.

Please add your feedback to this issue.

Thank you :)

**Comment by iameskild** [comment]
![image](https://user-images.githubusercontent.com/42120229/222575249-445068cd-4335-4975-a2f9-117ba8f4eae3.png)

One issue I've encountered is that I can only see the `global` namespace.

**Comment by iameskild** [comment]
A user who is only a member of the `analyst` group doesn't not have the access to create conda environments. This has been the default behavior for some time; they can nagivate to the `/conda-store` endpoint but they won't be able to login and do anything. 

With this new UI, they will still see the `Conda-Store` menu dropdown but if they try and create an environment, they will get hit with a `request not authorized` error message. There might not be a simple way for us to hide the `Conda-Store` menu dropdown but I thought I would call it out here.

**Comment by dharhas** [comment]
Two points:

1. I really don't like the 'analyst', 'developer' groupings. I know why it was done historically but I don't think it is explained anywhere and I think it we need to change it. That is a larger issue than what we are discussing here.
2. In terms of permissions, even an 'analyst' should be able to see the global and nebari-git namespaces in read-only format and be able to make personal environments.

**Comment by dharhas** [comment]
Also, "Global" is a shared environment and should be visible in the "Shared Environments" section. Above that section it should show personal environments. Also why are the 'nebari-git' envs missing?

**Comment by kcpevey** [comment]
Suggestion: Add a little info button next to `nebari-git` that says in a dialog "These environments are managed by the nebari-config.yml" 

And maybe another info button next to my name dropdown that says "These environments are visible only to you"

**Comment by kcpevey** [comment]
When I click on an enivornment, it never loads, just spins. 
![image](https://user-images.githubusercontent.com/15659110/223473220-63c05745-1c0a-4690-a0cd-8f1d4c5a4ae8.png)

When I click on a different one and come back to that environment, it loads everything except "Builds" and "Logs"
![image](https://user-images.githubusercontent.com/15659110/223473562-e8d9f330-c1ed-4d7d-ab12-24a64f6d3278.png)

**Comment by kcpevey** [comment]
When you aren't logged in, it should actually tell you "you aren't logged in - Log in to see environments"

**Comment by kcpevey** [comment]
Why are some installed versions listed, but others missing? 
![image](https://user-images.githubusercontent.com/15659110/223474526-fd26341a-b3e2-464c-b5d2-0a9546c48c9b.png)

**Comment by kcpevey** [comment]
Visually, we need a header above the person environment dropdown to match the `SHARED ENVIRONMENTS`. Something like `PRIVATE ENVIRONMENTS` above my namespace

![image](https://user-images.githubusercontent.com/15659110/223476037-9e66c78e-5b71-4088-a686-031b96bdc07d.png)


Other minor ui issue: https://github.com/Quansight/conda-store-ui/issues/232

**Comment by kcpevey** [comment]
If you have two channels, and you grab a channel to re-order them, the channel jumps 2 inches away from where you are "grabbing" on the screen. It works, it just sits 2 inches away from you mouse.
