### ISSUE TITLE
[ENH] - Add logging/error reporting from Argo workflows

### ISSUE THREAD

**Issue by ericdatakelly** [nebari-dev/nebari#1685]
### Feature description

It's very difficult for a user with standard permissions to debug when using Argo workflows because no information is returned to the user except whether the task succeeded or failed.  I'd like to be able to see logs, error messages, and stack traces associated with the tasks that were run.  The Argo UI provides a 'logs' button, so that might be the place to display them.

### Value and/or benefit

The value is in helping the average user accomplish their work efficiently.  Even if my solution runs on my local machine, when I move it to an Argo/Hera workflow and deploy it, it can fail.  To debug, I usually need to coordinate with an admin who can view the task and tell me what's happening with it.

**Comment by pavithraes** [comment]
Addition of loki (#1686) will fix this :)

**Comment by viniciusdc** [comment]
log aggregation is now supported on nebari (`>= 2024.2.1`)

**Comment by kcpevey** [comment]
@viniciusdc are the logs being pushed to the Argo UI logs or do users need to navigate through grafana to see the argo logs?
