### ISSUE TITLE
[ENH] - Addition of loki for grafana/prometheus stack to have a log aggregation solution

### ISSUE THREAD

**Issue by costrouc** [nebari-dev/nebari#1686]
### Feature description

See the following for details on how this installation would happen https://grafana.com/docs/loki/latest/installation/helm/. In addition to the regular prometheus helm chart this will now need to be deployed within the monitoring directory.

### Value and/or benefit

Currently there is not an easy way to expose logs to users without kubernetes credentials which often require cloud credentials. This makes logs not approachable to regular users of the system.

**Comment by viniciusdc** [comment]
Currently exploring this tool, following their docs on how to install it on existing Kubernetes clusters by using the[ helm installation process](https://grafana.com/docs/loki/latest/installation/helm/install-scalable/) using MinIO for storage. Without much intervention from the user after installation, the grafana operator that comes with the Loki chart seems to already set up the necessary dashboards (by mounting the config maps for them) and DatasSource -- wich then shows up under grafana exploring tab (to execute the queries)

**Comment by viniciusdc** [comment]
completed by #2156
