### ISSUE TITLE
[ENH] - Deploy Nebari to Azure with OIDC-based authentication

### ISSUE THREAD

**Issue by iameskild** [nebari-dev/nebari#1694]
### Feature description

At the moment, to deploy Nebari to Azure, we expect user-based authentication. This requires setting all of the following environments variables `ARM_SUBSCRIPTION_ID`, `ARM_TENANT_ID`, `ARM_CLIENT_ID`, and `ARM_CLIENT_SECRET`. 

We ensure that these environment variables are included in our `nebari init` ([here](https://github.com/nebari-dev/nebari/blob/3a19b60a9556bfdfcd0efea731bfac80e479a658/nebari/utils.py#L126)) and `nebari deploy` (inherited from how the Terraform `azurerm` provider) commands.

If a user (or our integration tests) wanted to deploy Nebari using an Azure federated workflow (OIDC), they would not currently be able. 

### Value and/or benefit

This increases the ways in which users can deploy. This particular method is also more secure than relying on user-based cloud credentials.

### Anything else?

I've been attempting to get the Nebari integration tests on Azure working recently and I have run into multiple issues and decided to open this issue to document my findings. As far as I can tell, the following changes are likely needed to get this work:
- Make passing `ARM_CLIENT_SECRET` optional -- the other three environment variables are still required for OIDC authentication albeit for a service principal instead for the user.
- Document that `ARM_USE_OIDC=true` will be required instead.
- If you want to a `remote` terraform state, this storage location of which will likely need to be passed to the provider backend for all subsequent stages, something like this

```terraform
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=3.22.0"
    }
  backend = "azurerm"
  config = {
    resource_group_name  = "resource_group_name"
    storage_account_name = "storage_account_name"
    container_name       = "container_name"
    key                  = "terraform.tfstate"
  }
```

**Comment by iameskild** [comment]
This is currently blocking us from running integration tests on Azure, so long as we use OIDC credentials. If we want to get around this, we will need to add the four Azure specific credentials to the GitHub secrets (avoiding OIDC) altogether.

**Comment by Adam-D-Lewis** [comment]
Azure deployment test uses OIDC, closing
