### ISSUE TITLE
[BUG] - local deploy cannot guaranteed be done without having access to a domain

### ISSUE THREAD

**Issue by pmeier** [nebari-dev/nebari#1707]
### Describe the bug

Related to #1703. TL;DR: our guide tells users to fix `/etc/hosts`, but the deployed cluster doesn't see this change. There are three ways to achieve that:

1. Have access to a domain and create a DNS entry for `--domain=...` to point to `172.18.1.100`. This is what we do for `github-actions.nebari.dev` to get our CI going:
   https://github.com/nebari-dev/nebari/blob/daecbcf37497b1b8b4e3f0f52667ababf3c023ad/.github/workflows/kubernetes_test.yaml#L95
2. Use a service like [nip.io](https://nip.io/) and set something like `--domain=172.18.1.100.nip.io` during `nebari init`. With this users no longer need to have a domain available, but still need to have access to the internet. Plus, we add an external dependency, since our guide then depends on nip.io being available.
3. Instead of using an URL, users could also use the IP directly, i.e. `--domain=172.18.1.100`. It is not as pretty as having an URL, but probably good enough for local deploy. The major advantage is that this can be done even without internet access making it the most reliable and easiest to use option of the three. Doing this, the user also doesn't need to fix `/etc/hosts`.

Regardless of what we decide we want to use, 2. and 3. (as well as our current docs) make an assumption that doesn't hold in 100% of the cases: the cluster IP is fixed at `172.18.1.100`. 

However, we don't know that. It should work most of the time, but I know for example that it doesn't work for @costrouc. Maybe he can fill in some details on when this won't be true?

Internally, we only know the correct IP after stage 4:

https://github.com/nebari-dev/nebari/blob/daecbcf37497b1b8b4e3f0f52667ababf3c023ad/nebari/deploy.py#L102-L104

Meaning, setting it upfront during `nebari init --domain` is not guaranteed to work.

### Expected behavior

I think we should allow setting no domain upfront and instead of asking the user to set up their DNS (when `--disallow-prompt` is not set)

https://github.com/nebari-dev/nebari/blob/daecbcf37497b1b8b4e3f0f52667ababf3c023ad/nebari/deploy.py#L128-L131

just use the IP we get from the load balancer.

### OS and architecture in which you are running Nebari

Linux

### How to Reproduce the problem?

Follow the [local deployment how-to](https://www.nebari.dev/docs/how-tos/nebari-local) in an environment where the load balancer doesn't use `172.18.1.100` as IP.

### Compute environment

None

**Comment by pmeier** [comment]
Looking through our workflow, we actually don't need the domain before stage 04. Meaning, we could accept an empty string in case of a local deployment to mean "just use the load balancer ip". Shouldn't be terribly hard to implement if we want that.

**Comment by costrouc** [comment]
> I think we should allow setting no domain upfront and instead of asking the user to set up their DNS (when --disallow-prompt is not set)

Does this mean that you suggest we just make the "domain" optional? And if so we just use what the cloud/docker/kind gives up? This could make a lot of sense and we just tell the user hey this is your url set the domain if you want something different?

**Comment by pmeier** [comment]
> Does this mean that you suggest we just make the "domain" optional?

Yes, in case we are doing a local deploy. It doesn't really make sense for cloud deploy, does it?

> And if so we just use what the cloud/docker/kind gives up?

Yes. My idea is, in case no domain is supplied, we skip

https://github.com/nebari-dev/nebari/blob/9915a6d19a5388a5fc0730465b31a6fc60b35b8b/nebari/deploy.py#L107-L131

and just use

https://github.com/nebari-dev/nebari/blob/9915a6d19a5388a5fc0730465b31a6fc60b35b8b/nebari/deploy.py#L104-L105

going forward. The last messages after a successful deploy tell the user how to reach the cluster and thus we don't need to do anything there.

**Comment by pmeier** [comment]
Summary after an offline discussion with @costrouc 

> It doesn't really make sense for cloud deploy, does it?

This is unnecessarily strict. If you are doing a cloud deploy, the load balancer will give us the publicly accessible IP as well. Meaning, we can make the domain optional in all cases, which is nice.

**Comment by pmeier** [comment]
Closing due to https://github.com/nebari-dev/nebari/pull/1803#issuecomment-1601618265 and #1833 was landed.
