### ISSUE TITLE
[ENH] - Use human-readable cloud providers during guided init

### ISSUE THREAD

**Issue by pmeier** [nebari-dev/nebari#1708]
### Feature description

Instead of using the short forms used for the machines, use the human readable versions for the cloud providers during `--guided-init`:

https://github.com/nebari-dev/nebari/blob/daecbcf37497b1b8b4e3f0f52667ababf3c023ad/nebari/cli/init.py#L331-L335

https://github.com/nebari-dev/nebari/blob/daecbcf37497b1b8b4e3f0f52667ababf3c023ad/nebari/schema.py#L26-L32

### Value and/or benefit

I'm not super well-versed in the space yet, but `"do"` was not obvious to me. Compare

```python
from nebari.cli.init import ProviderEnum, enum_to_list

for provider in enum_to_list(ProviderEnum):
    print(f"- {provider}")
```

```
- local
- existing
- do
- aws
- gcp
- azure
```

to a possible

```
- local
- existing
- DigitalOcean
- Amazon Web Services (AWS)
- Google Cloud Platform (GCP)
- Microsoft Azure
```

On top of being more readable, the latter also does not "leak" `nebari` internals to the user.

**Comment by pavithraes** [comment]
Thanks for reporting, added to the issue where we're gathering CLI improvements. :)

**Comment by shashvatshah9** [comment]
Picking up this issue.

**Comment by pavithraes** [comment]
Update: We initially expected the extension mechanism work to cover this, but this is still an issue.

**Comment by exitflynn** [comment]
picking this up :cowboy_hat_face:
