### ISSUE TITLE
[ENH] - Add option for output path to nebari init

### ISSUE THREAD

**Issue by pmeier** [nebari-dev/nebari#1712]
### Feature description

`nebari deploy` and `nebari destroy` have the `-o` / `--output` flags to work in another directory than the current. `nebari init` is missing this option.

### Value and/or benefit

Consistency with `nebari deploy` and `nebari destroy`

**Comment by babueverest** [comment]
I am working on this issue.

**Comment by dcmcand** [comment]
Closed as part of https://github.com/nebari-dev/nebari/pull/1833
