### ISSUE TITLE
[ENH] - Use pathlib everywhere

### ISSUE THREAD

**Issue by pmeier** [nebari-dev/nebari#1713]
### Feature description

Right now we are using both `os.path` and `pathlib`, e.g.

https://github.com/nebari-dev/nebari/blob/daecbcf37497b1b8b4e3f0f52667ababf3c023ad/nebari/render.py#L78

https://github.com/nebari-dev/nebari/blob/daecbcf37497b1b8b4e3f0f52667ababf3c023ad/nebari/render.py#L25

We should decide for one with a strong personal preference for `pathlib` on my side.

### Value and/or benefit

```
❯ python -c "import this" | sed '15q;d'
There should be one-- and preferably only one --obvious way to do it.
```

Although Python is giving us two ways here, we shouldn't make the same mistake. It is really annoying if one always has to check if the input is a path or a string.

**Comment by babueverest** [comment]
I am working on this issue.

**Comment by pmeier** [comment]
Sorry for not leaving a comment here, but I'm mostly dine with this already. @babueverest could you pick something else so we don't duplicate work?

**Comment by babueverest** [comment]
@pmeier Sounds good. I shall work on something else :)

**Comment by trallard** [comment]
@pmeier what is the status of this issue? can you please mark this accordingly with the labels to send a clear message to contributors?
