### ISSUE TITLE
[ENH] - also expand ~ in paths

### ISSUE THREAD

**Issue by pmeier** [nebari-dev/nebari#1714]
### Feature description

We are currently using `.resolve()` to make the path absolute:

https://github.com/nebari-dev/nebari/blob/daecbcf37497b1b8b4e3f0f52667ababf3c023ad/nebari/render.py#L33

However, this does not expand a `~` into `/home/$USER`, but rather treats it as a regular directory name in CWD:

```pycon
>>> from pathlib import Path
>>> Path("~/foo").resolve()
PosixPath('/home/philip/git/nebari-dev/nebari/~/foo')
>>> Path("~/foo").expanduser().resolve()
PosixPath('/home/philip/foo')
```

### Value and/or benefit

Support `~` in the `-o` / `--output` flags.

**Comment by trallard** [comment]
I am +1 on unifying the behaviour across all of nebari, it will help with standardisation and predictability.
