### ISSUE TITLE
[ENH] - Allow theme logo to pull image from local file

### ISSUE THREAD

**Issue by iameskild** [nebari-dev/nebari#1717]
### Feature description

Users can modify the theme of their Nebari deployment (specifically the home page) by modifying the `nebari-config.yaml`, specifically `theme.jupyterhub`. One of the items you can modify is the logo that appears on the top-left of the page.

Currently, it only accepts URLs but it would be nice to allow users to use a local png/jpg as well. 

### Value and/or benefit

This would give users additional flexibility.

**Comment by viniciusdc** [comment]
Thanks, @iameskild, for opening this issue. I will give quick feedback on my part to serve as a potential direction.

Indirectly speaking, you can add local paths to the theme.jupyterhub field in the YAML, the only problem is that when jupyterhub attempts to load the image, it will try to look into its Pod filesystem (which does not contain any reference to the host path). 

So right now, if you want to do something like that, you will need to build your custom image of jupyterhub [from ours](https://github.com/nebari-dev/nebari-docker-images/blob/main/Dockerfile.jupyterhub) and include the path and logo into the container, only then it will be able to be fully loaded.

I completely agree that this is troublesome and goes against all the easy capabilities already offered in the same section of the config yaml. To achieve the desired capabilities we mainly need a way to mount/push the given image into the cluster during deployment. 

Something that might be interesting to explore if we can pass a path currently registered in the shared space. We could ssp the logo image into the shared PVC and test if Jupyterhub can access the given logo path (this can be tested without redeploying as we can change the jupytehrub `configmap` with the logo location) - I am almost sure jupyterhub has access to the shared PVC, but not sure at what level.

If the above does not work, here's a possible direction:
1. Update our Pydantic schema  to work as a filter for URL and path-like expressions for the logo field;
2. If a path-like expression is given to nebari, during the `services` stage we could:
   - Mount the image into the Kubernetes cluster using it as a secret, with `kubectl add secret`
   - In the jupyterhub setting, we make a *switch* to create a mount from the secret into the Pod, making the logo available at the given path.

**Comment by Adam-D-Lewis** [comment]
We're open to this idea, but no action is planned on this so I'll close for now.
