### ISSUE TITLE
[BUG] - Dask dashboard freezes intermittently

### ISSUE THREAD

**Issue by pavithraes** [nebari-dev/nebari#1730]
### Describe the bug

On running computes with ~20 medium workers, the Dask JupyterLab extension plots freezes after one computation, until refreshed by re-arranging or closing+reopening.

The browser-based dashboard works fine throughout.

### Expected behavior

-

### OS and architecture in which you are running Nebari

GCP

### How to Reproduce the problem?

TBD

### Compute environment

None

**Comment by dcmcand** [comment]
fixed with gateway api improvements

**Comment by dcmcand** [comment]
closed by #1750
