### ISSUE TITLE
[MAINT] Bring back `environment-dev.yml`

### ISSUE THREAD

**Issue by pavithraes** [nebari-dev/nebari#1738]
We removed `environment-dev.yml` in https://github.com/nebari-dev/nebari/pull/1624#issuecomment-1404107813

We're using it in our contributors guide: https://www.nebari.dev/docs/community/code-contributions#create-a-virtual-environment, because it was a convenient way to get a development env setup.

If folks have an alternative idea for contributing workflow, please let me know :)

cc @iameskild

**Comment by iameskild** [comment]
Given that we are pinning specific versions of our dependencies in our `pyproject.toml`, keeping the (conda) dependencies in an `environment-dev.yaml` in sync with the (pip) dependencies is a little tricky. For example `kubernetes` is the name of the package on PyPI but `python-kubernetes` on conda and the latest version available on each aren't guaranteed to match.

I propose that we the following developer workflow:

```
# assuming you have the nebari repo cloned and in the root directory
conda create -n nebari-dev pip -y # create a new env called `nebari-dev` and install `pip`
pip install -e.[dev]
```

I'm happy to hear what others think.

**Comment by pavithraes** [comment]
@iameskild I didn't realize that an editable install will also install the required dependencies, but of course makes sense that it does. Thanks! I'll update the docs!

**Comment by pavithraes** [comment]
Closing as complete. :)
