### ISSUE TITLE
[DOC] - Release Notes sync does not work 

### ISSUE THREAD

**Issue by Adam-D-Lewis** [nebari-dev/nebari#1751]
### Preliminary Checks

- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/nebari-dev/nebari/discussions

### Summary

https://www.nebari.dev/docs/references/release/ is out of date. 

https://github.com/nebari-dev/nebari/blob/develop/RELEASE.md and https://github.com/nebari-dev/nebari/releases/tag/2023.4.1 are up to date.

### Steps to Resolve this Issue
- Perhaps https://github.com/nebari-dev/nebari/blob/develop/.github/workflows/release-notes-sync.yaml can be expanded to update the release notes in the nebari docs repo.

**Comment by iameskild** [comment]
I believe this has now been fixed here: https://github.com/nebari-dev/nebari/pull/1753
