### ISSUE TITLE
Upgrade JupyterHub to 2.0 or greater

### ISSUE THREAD

**Issue by iameskild** [nebari-dev/nebari#1763]
This issue will act as a central place for us to discuss and document what it would take to upgrade JupyterHub to version 2.0 or greater; [JupyterHub 4.0](https://github.com/jupyterhub/jupyterhub/issues/4350) was just released earlier this year . We are currently running on quite an old version (1.5) and sooner or later this will likely cause us issues. 

[Z2JH has documented](https://z2jh.jupyter.org/en/stable/administrator/upgrading/upgrade-1-to-2.html) what is required to upgrade from `1.*` to `2.*`.

**Comment by Adam-D-Lewis** [comment]
https://jupyterhub.readthedocs.io/en/latest/reference/changelog.html#id75 could be useful as well

One problem I already see is all our jupyterhub services are admins at the moment and we'll need to change that

**Comment by Adam-D-Lewis** [comment]
Looks like we'll have to drop support for CDSDashboards. https://github.com/ideonate/cdsdashboards/issues/96

**Comment by Adam-D-Lewis** [comment]
Managed to build an image with jupyterhub 3 that didn't throw any errors on startup of the hub pod on nebari at least
https://github.com/nebari-dev/nebari-docker-images/commit/78ecfe04038a6d1e5a7b679ba3f67ed7dffb8dc5

**Comment by Adam-D-Lewis** [comment]
The docker image change from a base Ubuntu image to a base debian-bullseye image.  This may force us to change our image, but not sure yet - https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/2.0.0/images/hub/Dockerfile.

**Comment by Adam-D-Lewis** [comment]
Seeing this error, looks like I'll need to upgrade jupyterlab image as well - jupyterhub version 3.1.1 != jupyterhub-singleuser version 1.5.0. This could cause failure to authenticate and result in redirect loops!

**Comment by Adam-D-Lewis** [comment]
These services will need to be adjusted in order to work in the latest jupyterhub.

services = concat([
    "dask-gateway"
    ],
    (var.monitoring-enabled ? ["monitoring"] : []),
    (var.prefect-enabled ? ["prefect"] : []),
    (var.kbatch-enabled ? ["kbatch"] : [])
  )

**Comment by Adam-D-Lewis** [comment]
Okay, I seem to have a working version of Nebari with Jupyterhub 3.  I tested the dashboards in grafana, running a small dask cluster on a small computation, creating a conda environment in conda store, creating users manually in keycloak.  Only thing that doesn't work is CDSDashboards and idk a way around that til we get a replacement built.

**Comment by Adam-D-Lewis** [comment]
Related Issue that should probably be included in this PR: https://github.com/nebari-dev/nebari/issues/1854
