### ISSUE TITLE
[BUG] - Contributor workflow comment trigger does not work properly

### ISSUE THREAD

**Issue by pmeier** [nebari-dev/nebari#1769]
### Describe the bug

By commenting `/bot run tests` as a maintainer on a PR, we should be able to trigger some workflows that are usually not run for regular contributors. This is done through this workflow

https://github.com/nebari-dev/nebari/blob/6b38c8c3215b3ce7683b4c83fe2ecb9aa79c34ac/.github/workflows/contributor.yaml#L1-L5

The trigger works fine until it comes to checking the permissions of the user sending the comment. We currently check for these roles

https://github.com/nebari-dev/nebari/blob/6b38c8c3215b3ce7683b4c83fe2ecb9aa79c34ac/.github/workflows/contributor.yaml#L31

They are correct according to the [documentation](https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads?actionType=created#issue_comment):

> `author_association` string Required
>
> How the author is associated with the repository.
>
> Can be one of: `COLLABORATOR`, `CONTRIBUTOR`, `FIRST_TIMER`, `FIRST_TIME_CONTRIBUTOR`, `MANNEQUIN`, `MEMBER`, `NONE`, `OWNER`

However, [I](https://github.com/nebari-dev/nebari/actions/runs/4855218498/jobs/8653525858#step:5:6) and @iameskild as well, are listed as `CONTRIBUTOR`, although we should have `MAINTAINER` permissions.

### Expected behavior

Being able to trigger contributor tests as maintainer.

### OS and architecture in which you are running Nebari

GitHub repository

### How to Reproduce the problem?

Comment `/bot run tests` on a PR, e.g. #1725. Curious to see what the bot spits out for people with elevated permissions.

### Compute environment

None

**Comment by pmeier** [comment]
There is this discussion https://github.com/orgs/community/discussions/18690 where people seem to have the same issue. @aktech Do you have any additional insights on this since your comment?

**Comment by pmeier** [comment]
Looking at my settings, I'm listed as "moderator"

![Screenshot from 2023-05-02 14-23-37](https://user-images.githubusercontent.com/6849766/235665197-93f193bd-0b22-4a77-9c0d-cf785f65a4b8.png)

Meaning, maybe GHA is not wrong here, but our permissions are setup wrong?

**Comment by aktech** [comment]
Hey @pmeier (and @iameskild) you'd need to change your Organisation visibility to Public, for it to identify both of you as `MEMBER` as described in the comment I made [there](https://github.com/orgs/community/discussions/18690#discussioncomment-4232389).

<img width="985" alt="Screenshot 2023-05-02 at 2 45 00 pm" src="https://user-images.githubusercontent.com/5647941/235669779-371c239a-fdf4-4923-8887-5d11681b6757.png">

<img width="988" alt="Screenshot 2023-05-02 at 2 44 49 pm" src="https://user-images.githubusercontent.com/5647941/235669743-2b379be1-1c41-4d2a-86b7-ed6bc348299f.png">

Here is mine:

<img width="998" alt="Screenshot 2023-05-02 at 2 45 19 pm" src="https://user-images.githubusercontent.com/5647941/235669839-b2e50c98-f332-4493-8a83-02e2f23202ec.png">

**Comment by aktech** [comment]
You can change the toggle here (next to your username): https://github.com/orgs/nebari-dev/people


<img width="1406" alt="Screenshot 2023-05-02 at 3 07 39 pm" src="https://user-images.githubusercontent.com/5647941/235675258-dc0a4f9c-9d94-4364-9336-cdc099c4e370.png">
