### ISSUE TITLE
[BUG] - Inconsistent Nebari Docs / Unclear messaging on upgrading nebari

### ISSUE THREAD

**Issue by Adam-D-Lewis** [nebari-dev/nebari#1790]
We haven't used the `nebari upgrade` command much.  Mainly it was used for updating from 0.3.x to 0.4 which had many breaking changes.  There has been a little bit of use otherwise, but not much.  I believe the docs, nebari cli docs, and the upgrade.py code are conflicting now.  E.g. the CLI docs for `nebari upgrade` are below:
```
(devneb) [balast@x1-carbon]: ~>$ nebari upgrade -h
                                                                                             
 Usage: nebari upgrade [OPTIONS]                                                             
                                                                                             
 Upgrade your nebari-config.yaml from pre-0.4.0 to 0.4.0.                                    
 Due to several breaking changes that came with the 0.4.0 release, this utility is available 
 to help                                                                                     
 update your nebari-config.yaml to comply with the introduced changes.                       
 See the project RELEASE.md for details. 
 ```
 but that isn't true.  I think `nebari upgrade` should be the officially supported way for people to upgrade.   
 
 https://www.nebari.dev/docs/how-tos/nebari-upgrade shows the correct way to upgrade, but it's only for the pre 0.4 version https://www.nebari.dev/docs/how-tos/nebari-upgrade#upgrade-nebari-from-pre-040-to-040, while the other section is wrong https://www.nebari.dev/docs/how-tos/nebari-upgrade#minor-upgrade-to-nebari.  Pam was working on a PR to fix these docs, and a lot of these same comments and observations have been made there, but she left Quansight and the PR didn't get merged (https://github.com/nebari-dev/nebari-docs/pull/288)

Also, you can see where we've relied on the upgrade command by looking at some of the classes in https://github.com/nebari-dev/nebari/blob/1f6286311a6663f520295a205806840187a10071/nebari/upgrade.py#L363.  As a developer coming back to Nebari after a while off, I saw this file and assumed we were still using it (since there are more than just a 0.4 upgrade class), and I figured out the rest of the info afterwards.

**Comment by kcpevey** [comment]
Also note that release 2023.5.1 now makes it important to use this command while upgrading. This is captured in the [release notes](https://github.com/nebari-dev/nebari/blob/develop/RELEASE.md#release-202351---may-5-2023) but needs to be added to the documentation as well.

**Comment by kcpevey** [comment]
```
[terraform]: │ Error: rendered manifests contain a resource that already exists. Unable to continue with update: CustomResourceDefinition "clusterworkflowtemplates.argoproj.io" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "argo-workflows"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "dev"
[terraform]: │ 
[terraform]: │   with module.argo-workflows[0].helm_release.argo-workflows,
[terraform]: │   on modules/kubernetes/services/argo-workflows/main.tf line 6, in resource "helm_release" "argo-workflows":
[terraform]: │    6: resource "helm_release" "argo-workflows" {
```

**Comment by iameskild** [comment]
This looks complete to me, @Adam-D-Lewis feel free to reopen this if you think otherwise.
