### ISSUE TITLE
Explore upgrading Keycloak to version 21.x

### ISSUE THREAD

**Issue by iameskild** [nebari-dev/nebari#1808]
We are currently running on keycloak version 15.0.2 and this might be an issue for local Nebari deployments on M1 Macs, likely due to the change in architecture and the lack of keycloak support for this new architecture at that time. 

As someone running developing on an M1 Mac, I have performed simple tests with both versions (15.0.2 and 21.1.1) and only the later version worked for me. 

Also see #1405

**Comment by Adam-D-Lewis** [comment]
Superceded by https://github.com/nebari-dev/nebari/issues/2495
