### ISSUE TITLE
[BUG] - AWS `worker` node group failed to scale up

### ISSUE THREAD

**Issue by iameskild** [nebari-dev/nebari#1809]
### Describe the bug

When trying to launch a dask cluster (with 0 active `worker` nodes), the auto-scaler failed to scale from 0 -> 1 node. I went to the AWS console and manually scaled to one node and then the additional worker nodes started to spin up. 

The error message I saw on the `dask-scheduler` while it was waiting on the scale-up was:

```
didn't match pod's node affinity/selector
```

### Expected behavior

The AWS auto-scaler should scale up the nodes when requested.

### OS and architecture in which you are running Nebari

Ubuntu Linux - via GitHub Actions

### How to Reproduce the problem?

This issue appears to be intermittent so it's hard to say when it will happen and when it will work. 

### Compute environment

AWS

### Integrations

Dask

**Comment by Adam-D-Lewis** [comment]
Haven't seen this recently, closing
