### ISSUE TITLE
[BUG] - AWS EKS user and worker node groups fail to scale to 0 nodes

### ISSUE THREAD

**Issue by Adam-D-Lewis** [nebari-dev/nebari#1811]
# Description
AWS EKS user and worker node groups fail to scale to 0 nodes

**Comment by Adam-D-Lewis** [comment]
I think the cluster autoscaler won't scale down if a pod from a deployment is scheduled on it.  AWS EKS includes a few add-ons by default that some deployments.  Specifically the coredns and ebs-csi-controller deployments.  Pods from those deployments were scheduled on the worker and user pods.  This may be part of the reason the worker and user node groups didn't scale down.

**Comment by Adam-D-Lewis** [comment]
We could patch the problematic add-on deployments in the nebari/template/stages/03-kubernetes-initialize/main.tf module

**Comment by iameskild** [comment]
@Adam-D-Lewis is this a priority for you? Should we assign someone to work on this?

**Comment by Adam-D-Lewis** [comment]
Not a priority because of the workaround

**Comment by viniciusdc** [comment]
Hi @Adam-D-Lewis, I assume #2353 fixed this issue right? can we mark this as completed?
