### ISSUE TITLE
[BUG] - project name validation

### ISSUE THREAD

**Issue by pmeier** [nebari-dev/nebari#1813]
### Describe the bug

During `nebari init --guided-init` we are checking the project name in two places:

1. When putting it in with

   https://github.com/nebari-dev/nebari/blob/8bd56f90b84c7686f45459ae8f7cf690721bd60a/nebari/schema.py#L519
2. While rendering the config with
   
   https://github.com/nebari-dev/nebari/blob/8bd56f90b84c7686f45459ae8f7cf690721bd60a/nebari/initialize.py#L360-L363
   

Unfortunately, these methods diverge:

1. https://github.com/nebari-dev/nebari/blob/8bd56f90b84c7686f45459ae8f7cf690721bd60a/nebari/schema.py#L520-L529
2. https://github.com/nebari-dev/nebari/blob/8bd56f90b84c7686f45459ae8f7cf690721bd60a/nebari/utils.py#L41

Some differences (not exhaustive):
- 1. allows numbers while 2. doesn't
- 1. allows a maximum of 16 characters, while 2. allows arbitrary lengths
- 1. has extra rules depending on the cloud provider, while 2. does not
- 2. doesn't allow underscores or hyphens, while 1. does (it is not mentioned in the docstring, but it does)

### Expected behavior

If a project name passes the initial validation, there should be no errors down the line. 

### OS and architecture in which you are running Nebari

-

### How to Reproduce the problem?

-

### Compute environment

None

**Comment by pavithraes** [comment]
@iameskild - Potential solution could be to check project name separately for each cloud provider. This is also blocked by the extension mechanism work.

**Comment by kenafoster** [comment]
I've created two related issues around project naming conventions

https://github.com/nebari-dev/nebari/issues/2001
https://github.com/nebari-dev/nebari/issues/2002
