### ISSUE TITLE
[BUG] - Infracost CI and DO tests failing

### ISSUE THREAD

**Issue by pavithraes** [nebari-dev/nebari#1817]
_Originally reported by @pmeier on Quansight Slack_

`@Adam-D-Lewis` triggered some tests on `@pmeier`'s PR through the comment and the infracost jobs on AWS and Azure both fail because no credentials can be retrieved. Since Adam should have all the permissions, we need to figure out why this fails?

Refs:
- https://github.com/nebari-dev/nebari/actions/runs/5038088999/jobs/9035348504?pr=1778
- https://github.com/nebari-dev/nebari/actions/runs/5038088999/jobs/9035348581?pr=1778

The DO provider tests failing as well: https://github.com/nebari-dev/nebari/actions/runs/5016789600/jobs/8994092014#step:11:424

**Comment by kcpevey** [comment]
I'm seeing the same thing on my PR https://github.com/nebari-dev/nebari/pull/1665

**Comment by pmeier** [comment]
I need functioning CI for PRs like #1773 or #1778 since they are large scale refactorings.

**Comment by kcpevey** [comment]
I'm guessing its related to our recent changes to our credentials infra. @iameskild or @costrouc might know more?

**Comment by pmeier** [comment]
> As for Infracost, I personally don't think it's worth the maintenance burden of keeping integrated. As Dharhas said, it was hastily added so its utility at this moment is relatively limited.

Let me send a PR for that.

**Comment by pmeier** [comment]
@dharhas I talked to @iameskild offline and we interpreted your https://github.com/nebari-dev/nebari/issues/1817#issuecomment-1557262871 differently. Do you mean we should just kill the CI jobs or rip it out completely? Currently it is part of our CLI

https://github.com/nebari-dev/nebari/blob/41116257ad07c094b29cf363fe52776573c063ee/nebari/cli/main.py#L385

However, it is marked "experimental"

https://github.com/nebari-dev/nebari/blob/41116257ad07c094b29cf363fe52776573c063ee/nebari/cli/main.py#L420

and thus we can likely purge it without BC concerns.

**Comment by pmeier** [comment]
There is #1820 to remove the infracost capabilities. Re-labeling as `needs: investigation`, since the DO issue is not resolved yet.

**Comment by pmeier** [comment]
@iameskild Did you fix the DO token as discussed in yesterday's community meeting? If so, I'm still seeing the same failures on my PR: https://github.com/nebari-dev/nebari/actions/runs/5067342709/jobs/9098287246?pr=1778 Maybe we should open an RFD regarding dropping DO from our supported provider list as @trallard suggested.

**Comment by iameskild** [comment]
@pmeier the DO API token has been updated and the CI is passing 🎉

**Comment by pmeier** [comment]
In that case #1820 actually closed this issue.
