### ISSUE TITLE
[ENH] - Allow setting region during init

### ISSUE THREAD

**Issue by pmeier** [nebari-dev/nebari#1824]
### Feature description

We currently hard-code the following regions based on the cloud provider the user selects:

https://github.com/nebari-dev/nebari/blob/1413b9535be3458bac745f3014a886efbe16ab15/nebari/initialize.py#L217-L218

https://github.com/nebari-dev/nebari/blob/1413b9535be3458bac745f3014a886efbe16ab15/nebari/initialize.py#L228-L230

https://github.com/nebari-dev/nebari/blob/1413b9535be3458bac745f3014a886efbe16ab15/nebari/initialize.py#L239-L240

https://github.com/nebari-dev/nebari/blob/1413b9535be3458bac745f3014a886efbe16ab15/nebari/initialize.py#L260-L261

However, similar to the deploy target, the region has no good default value. Worse, `nebari init` doesn't even give you the option to set the region and one has to manually edit the yaml afterwards.

1. We should expose a `--region` option on `nebari init`
2. The option should be required in case a new cloud provider, i.e. not `"local"` or `"existing"` is used as deploy target.

For the guided init, we should add a question for the region (preferably a populated list) that will be displayed if the user selects one of the cloud providers.

### Value and/or benefit

Less frustration due to failed deploys and time needed manually editing the config yaml.

**Comment by pavithraes** [comment]
@iameskild - Can be added to the "Advanced Configuration" section of guided init

**Comment by pmeier** [comment]
I don't think it falls under "advanced". We don't want a default value in case the user specifies a cloud provider. However, since most people will not open the advanced settings, we'll need to have a default if we put it there.
