### ISSUE TITLE
Redirect `qhub.dev` to `nebari.dev`

### ISSUE THREAD

**Issue by pavithraes** [nebari-dev/nebari#1826]
#1801 removes our old docs currently hosted at `qhub.dev`, we need to add a redirect from `qhub.dev` to `nebari.dev`. :)

@costrouc Pinging you because I believe you manage these domains, but please feel free to tag more folks as you see fit!

**Comment by costrouc** [comment]
We did the following steps https://developers.cloudflare.com/fundamentals/get-started/basic-tasks/manage-domains/redirect-domain/ we will revisit to see if things worked

**Comment by pmeier** [comment]
Redirects properly for me now:

```
❯ curl -v qhub.dev
*   Trying 188.114.96.3:80...
* Connected to qhub.dev (188.114.96.3) port 80 (#0)
> GET / HTTP/1.1
> Host: qhub.dev
> User-Agent: curl/8.1.2
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Date: Wed, 31 May 2023 20:22:16 GMT
< Transfer-Encoding: chunked
< Connection: keep-alive
< Cache-Control: max-age=3600
< Expires: Wed, 31 May 2023 21:22:16 GMT
< Location: https://nebari.dev
< Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=VrMFVy8D9owenIUtR2c5vCFBXvqbR0ZLA2lrPxYgvGNpMftmERUlutGtPau5GjWuQ5byqm4J%2B%2FxuinvJ3wOtEc4vpr6IdYsn%2F7irxvOmY%2Fnas69Bsw%2Bx8G7fIQ%3D%3D"}],"group":"cf-nel","max_age":604800}
< NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< Server: cloudflare
< CF-RAY: 7d01ed8efac52c7a-FRA
< alt-svc: h3=":443"; ma=86400
< 
* Connection #0 to host qhub.dev left intact
```

**Comment by pmeier** [comment]
> We did the following steps https://developers.cloudflare.com/fundamentals/get-started/basic-tasks/manage-domains/redirect-domain/ we will revisit to see if things worked

At first we tried the "single" redirect rule, but it didn't work right away. We got impatient and tried the bulk one instead and that worked, albeit still after 30 minutes or so. Since then I have reverted to the single redirect rule and it still redirects just fine.
