### ISSUE TITLE
Support K8s 1.25

### ISSUE THREAD

**Issue by Adam-D-Lewis** [nebari-dev/nebari#1849]
This issue will be used to track issues regarding supporting k8s 1.25.

**Comment by Adam-D-Lewis** [comment]
I deployed on GCP with k8s version 1.25 with most optional features disabled and it succeeded initially, but when I tried to launch user pods, they were never scheduled despite a user node being available.  We've suspected that JHub was preventing us from launching successfully on 1.25. So I'll try to upgrade JHub.  Those efforts will be tracked in https://github.com/nebari-dev/nebari/issues/1763.

**Comment by Adam-D-Lewis** [comment]
Managed to build an image with jupyterhub 3 that didn't throw any errors on startup of the hub pod on nebari at least
https://github.com/nebari-dev/nebari-docker-images/commit/78ecfe04038a6d1e5a7b679ba3f67ed7dffb8dc5

**Comment by iameskild** [comment]
This is the same issue I ran into while testing the upgrade a few weeks ago. Did you try 1.25 alongside your JupyterHub upgrade?

**Comment by Adam-D-Lewis** [comment]
Yeah, k8s 1.25 works after upgrading to jupyterhub 3
