### ISSUE TITLE
[ENH] - Add code-based authentication features

### ISSUE THREAD

**Issue by pavithraes** [nebari-dev/nebari#1853]
### Feature description

Users can login with a specific code to join certain groups/roles. Ideally, we can make this a part of our Keycloak authentication/registration system.

Additionally, it'll be nice to have a system for people to add a new code later to access a different role.

For example: a specific code gives them access to GPU instances, and another code allows them to create sharable environments, etc.

### Value and/or benefit

This is useful in tutorial settings where we open registrations for anyone on the internet, but can restrict only tutorial participants by sharing the "code" at the event.

### Anything else?

A few cases to note:
- We'd like people to use any username, so they know they're not sharing personal emails with us.
- We need to look into a workflow for folks who forget their passwords -- we can't rely on emails we don't collect emails

Alternatively, we can ask for real emails and have a privacy policy that states that their emails will be deleted after the event.

**Comment by kcpevey** [comment]
usecase:
* token based - allowed to register based on token with given user groups
* authenticate based on allowed domains (i.e. .mil email address) 


keycloak can't set expiration but if we have a keycloak token we can programatically check the creation date and run something that autodelete. would need something else to evict them from jupyter and conda-store and dask clusters. 

time based and end date based expirations


web based fast api server to create users + cron job to clean up expired users

could be standalone but it makes sense for this to be an extension

Let keycloak validate their registered username/email. Consider adding some additional validation. 

Consider adding email server to allow keycloak to send a confirmation email to newly registered users.

**Comment by kcpevey** [comment]
We've created a space for this work to be completed: https://github.com/nebari-dev/nebari-registration

**Comment by kcpevey** [comment]
The registration mechanism is now in beta and lives [here](https://github.com/MetroStar/nebari-self-registration/). Specific enhancement requests should be opened as issues over there.
