### ISSUE TITLE
CDS Dashboards Deprecation

### ISSUE THREAD

**Issue by Adam-D-Lewis** [nebari-dev/nebari#1854]
- CDSDashboard deployment needs to be removed from the repo
- Nebari Documentation needs to replace the CDS Dashboard sections with a statement that CDS Dashbaords is not compatible with the latest Nebari and the reasons why plus a link to our new effort with an approx timeline of availability. Also why we are making this breaking change
- Release notes and upgrade command should have similar warnings/descriptions
- Separately the next Nebari release that is going to happen early July should have a depreciation warning mentioning a summarized version of the above and say that this is likely to happen in the following release. (https://github.com/nebari-dev/nebari/issues/1855)

**Comment by iameskild** [comment]
CDS Dashboards was removed in #1856
