### ISSUE TITLE
CDS Dashboards Deprecation Warning for 2023.7.1 release

### ISSUE THREAD

**Issue by Adam-D-Lewis** [nebari-dev/nebari#1855]
CDS Dashboards Deprecation Warning for 2023.7.1 release
- Separately the next Nebari release that is going to happen early July should have a depreciation warning mentioning a summarized version of the above and say that this is likely to happen in the following release.

**Comment by iameskild** [comment]
This warning message was added to the RELEASE notes and as part of the nebari upgrade command output.
