### ISSUE TITLE
Automated Testing Requirements

### ISSUE THREAD

**Issue by aktech** [nebari-dev/nebari#1872]
### Context

This is related to #1862 we need to write a bunch of tests (notebooks potentially) that we can run on a deployment to make sure it works. 

- [ ] GPU Availability
- [ ] Ability to spin up JupyterLab
- [ ] Preemptible
- [ ] ...

### Value and/or benefit

This will help us guarantee something works and its quicker and reproducible to test it automatically via CI.

**Comment by aktech** [comment]
from @pmeier (for testing GPU)

- https://pytorch.org/docs/stable/generated/torch.cuda.is_available.html?highlight=is_available#torch.cuda.is_available
- https://github.com/pytorch/vision/blob/a6dea861f5a221e526eeec2170ee094c0e5fa912/.github/scripts/setup-env.sh#L81-L83
- https://github.com/pytorch/vision/blob/a6dea861f5a221e526eeec2170ee094c0e5fa912/.github/scripts/setup-env.sh#L75-L79

**Comment by iameskild** [comment]
@aktech it looks like testing GPUs, preemptible instances and the basics of the JupyterLab server are being tested. We can start adding other tests now. Should we start by trying to replace all of our cypress test as a next step?

**Comment by aktech** [comment]
> Should we start by trying to replace all of our cypress test as a next step?

That sounds like a good idea, there is no need to have multiple frameworks (cypress/playwright) at this point unless they add some value.

**Comment by pavithraes** [comment]
Blocked by #1653

**Comment by iameskild** [comment]
I think we can close this in favor of: https://github.com/nebari-dev/nebari/issues/1862.
