### ISSUE TITLE
[ENH] - Missing env vars for Argo

### ISSUE THREAD

**Issue by kcpevey** [nebari-dev/nebari#1875]
### Feature description

Nebari currently sets the `ARGO_TOKEN` as an env var on startup, but addition env vars are required for Argo to work. 

```
os.environ['ARGO_HTTP1'] = "true"
os.environ['ARGO_SECURE'] = "true"
os.environ['KUBECONFIG'] = '/dev/null'
os.environ['HERA_TOKEN'] = os.environ['ARGO_TOKEN'] 
os.environ['GLOBAL_CONFIG_HOST'] = f"https://{os.environ['ARGO_SERVER'].rsplit(':')[0]}{os.environ['ARGO_BASE_HREF']}/"  # trailing slash required for proper urljoin inside of hera
os.environ['GLOBAL_CONFIG_NAMESPACE'] = os.environ['ARGO_NAMESPACE']
```

### Value and/or benefit

Setting these for the user will allow for a lower barrier to entry, minimized setup, and I believe was the original intent of setting the Argo token for the users. 

### Anything else?

A minimal functioning example for testing:

```
import os
from hera.shared import global_config

os.environ['ARGO_HTTP1'] = "true"
os.environ['ARGO_SECURE'] = "true"
os.environ['KUBECONFIG'] = '/dev/null'
os.environ['HERA_TOKEN'] = os.environ['ARGO_TOKEN'] 
os.environ['GLOBAL_CONFIG_HOST'] = f"https://{os.environ['ARGO_SERVER'].rsplit(':')[0]}{os.environ['ARGO_BASE_HREF']}/"  # trailing slash required for proper urljoin inside of hera
os.environ['GLOBAL_CONFIG_NAMESPACE'] = os.environ['ARGO_NAMESPACE']

global_config.host = os.environ['GLOBAL_CONFIG_HOST']
global_config.token = os.environ['HERA_TOKEN'] 


from hera.workflows import Steps, Workflow, script

@script()
def echo(message: str):
    print(message)


with Workflow(
    generate_name="hello-world-hera-",
    entrypoint="steps",
    namespace=os.environ['GLOBAL_CONFIG_NAMESPACE'],
) as w:
    with Steps(name="steps"):
        echo(arguments={"message": "Hello world!"})

w.create()
```

**Comment by iameskild** [comment]
After having tried using Hera on Nebari a few times, I'm not sure we need all of these env vars. I have been able to get away with using only:

```
ARGO_BASE_HREF
ARGO_SERVER
ARGO_TOKEN
ARGO_NAMESPACE
```

Let me know if you think there are situations where we need them but otherwise I think we can close this issue.

**Comment by kcpevey** [comment]
I went back though with various combinations and it looks like the global config is the only missing piece. It turns out that even though there are env vars for the global config, they don't get picked up properly and you have to set `global_config` parameters for things to work correctly. 

So in addition to what's already existing, you'll need to add the following to your workflows

```
from hera.shared import global_config
global_config_host = f"https://{os.environ['ARGO_SERVER'].rsplit(':')[0]}{os.environ['ARGO_BASE_HREF']}/"
global_config.host = global_config_host
global_config.token = os.environ['ARGO_TOKEN'] 
```

These missing pieces aren't env vars so I'll close this.
