### ISSUE TITLE
[ENH] - Move hidden login files to a single directory

### ISSUE THREAD

**Issue by kcpevey** [nebari-dev/nebari#1899]
### Feature description

Every time you log into nebari, a hidden directory is created with the `.bash_logout`, `.bashrc`, and `.profile` in the home directory. From the Jupyter UI you can't see any of these hidden directories, but from vs code... 

![image](https://github.com/nebari-dev/nebari/assets/15659110/e4040b0c-287c-4b46-811d-c810c6235baf)

I've been on this deployment for a little over a month and I already have 184 of these. It makes using VS Code pretty frustrating when you have to scroll past all of these. 

I propose that we store these files in a SINGLE hidden directory off of home. 

### Value and/or benefit

Happy VS Code users.

**Comment by iameskild** [comment]
I'm not sure why this file is being created...
There might be a setting in code-server (VScode) that allows us to hide specific files/folders:

```
files.exclude": {
  "**/.DS_Store": false,
   ...
}
```

Another option might include running a script that clears this file everything the user logs in (this results in a single file being present after each login).

**Comment by kcpevey** [comment]
>There might be a setting in code-server (VScode) that allows us to hide specific files/folders:

The filename a date and a hash, its not constant. I guess you could exclude files that start with the year, but that seems dangerous. 

>Another option might include running a script that clears this file everything the user logs in (this results in a single file being present after each login).

That could work with some regex, but I think we need to understand what is creating this file and why is it being created.

**Comment by bmwoodruff** [comment]
I have been using Nebari with the POSSEE genai-numpy project, and I have the same issue. The new folder that gets created with every login causes a problem for me on both VS code and JupyterLab, provided you make hidden files visible on JupyterLab (I always prefer to have hidden files visible). Placing these folders in a single directory would be great. The folders and files are owned by root, with group permission root, so there's no way a user without root access can do anything to them.

**Comment by kcpevey** [comment]
I think the first step here is to explore why these files exist in the first place. If we don't actually use or need them for any reason, then it would be best just to avoid writing them in the first place.

**Comment by Adam-D-Lewis** [comment]
This is an implementation detail caused by the way kubernetes mounts configmaps.  We were then copying those extra files to the home directory from the init container.  I've opened a [PR](https://github.com/nebari-dev/nebari/pull/2578/files#diff-f5c371f9d5d639924719243ab242f08d94fd68a1f5c004f4f7582f5c9b816efbL51) that fixes this going forwards.  You'd still need to ask an admin to delete the accumulated files for you.
