### ISSUE TITLE
[BUG] - Nebari deploy in AWS overwrites the node group desired_size value

### ISSUE THREAD

**Issue by sblair-metrostar** [nebari-dev/nebari#1901]
### Describe the bug

Nebari deployments in AWS will overwrite the current value of a node group/ASG desired size value regardless of the autoscaled size. The autoscaling group desired size value is expected to change in response to the cluster autoscaler, so may not always reflect the default value set by the Nebari terraform stage potentially resulting in nodes getting terminated for unrelated Nebari changes.

This behavior risks interrupting jobs and cycling core components such as Keycloak and Jupyter.

### Expected behavior

The desired_size parameter should be ignored in the same manner as the [Terraform EKS module](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/666603b6e531140d5d8fbd777cd90a7fbb8247dd/modules/eks-managed-node-group/main.tf#L383).

``` terraform
resource "aws_eks_node_group" "main" {
# ...
  lifecycle {
    create_before_destroy = true
    ignore_changes = [
      scaling_config[0].desired_size,
    ]
  }
}
```

### OS and architecture in which you are running Nebari

Ubuntu Linux, x64

### How to Reproduce the problem?

1. Deploy Nebari to AWS
2. Manually change the desired size of an autoscaling group to a non-default value or allow the autoscaler to do the same in response to workload
3. Run `nebari deploy ...` again, observe the terraform plan changing the value back

### Versions and dependencies used.

Nebari: 2023.7.2
Kubernetes: 1.24

### Compute environment

None

**Comment by iameskild** [comment]
Thanks for reporting this @sblair-metrostar!
