### ISSUE TITLE
Resolve the divergence of `main` and `develop` branches

### ISSUE THREAD

**Issue by pavithraes** [nebari-dev/nebari#1912]
### Context

The git history of `main`and `develop` branches have diverged, causing several merge conflicts in #1876. 

Release branch used to be squash merged into `main`, which likely what caused the divergence. We need to be able to push to the *protected* release branches to resolve these.

Steps to resolve:

* Temporarily remove branch protection for release branches to allow us to fix the conflict
* Update (rewrite?) the git history of `main` to match `develop`? 
* Update release documentation to ensure we use "merge commits" while merge release branches into main

### Value and/or benefit

This is currently blocking our release process, and the update will ensure we have a more stable workflow.

**Comment by trallard** [comment]
I am +1 on bringing these branches in sync. 

Then for merging strategy it seems we need 

- squash merge in develop
- merge commit in main 


Correct?

**Comment by pavithraes** [comment]
@trallard Yes, that's correct. :)

@eskild and I just realized merge commits are disabled on Nebari, but since we'll need that for all merges into `main` moving forward I think we can enable it?

**Comment by iameskild** [comment]
This should now be resolved by merging #1949
