### ISSUE TITLE
[ENH] - Generalized terraform modules for cloud primitives: object storage, share filesystem

### ISSUE THREAD

**Issue by costrouc** [nebari-dev/nebari#1918]
### Feature description

We should support python functions to generate cross cloud primitives for storage.

See https://github.com/nebari-dev/nebari/blob/develop/src/_nebari/stages/tf_objects.py which shows how we can dynamically generate terraform resoruces. Eventually I'd like to see more of nebari start to use this since it would allow easier abstraction.

### Value and/or benefit

Easier abstraction of functions within nebari. Easier cross platform support.

**Comment by Adam-D-Lewis** [comment]
No plans for this, closing for now
