### ISSUE TITLE
[BUG] - Nebari validate doesn't fail with a non-zero exit code on schema validation error

### ISSUE THREAD

**Issue by sblair-metrostar** [nebari-dev/nebari#1919]
### Describe the bug

Running `nebari validate` in a Gitlab pipeline doesn't fail the stage as expected on schema validation issues. It does for other issues such as a [missing AWS cli in the environment ](#1917), so this appears to be specific to schema checks.

Example 1: Schema validation failure passes (not expected)
![image](https://github.com/nebari-dev/nebari/assets/70233904/3f72c67e-f7a8-4c84-a47f-0291f8d3685f)

Example 2: Missing AWS executable fails (expected)
![image](https://github.com/nebari-dev/nebari/assets/70233904/5dedb814-42f4-43d9-96d6-eaf9d6a8aa50)

### Expected behavior

`nebari validate` should exit with a non-zero status on all invalid configurations

### OS and architecture in which you are running Nebari

Ubuntu Linux, x64

### How to Reproduce the problem?

Run `nebari validate` against an AWS environment with 1 or more required AWS environment variable/credentials missing.

### Versions and dependencies used.

Kubernetes: 1.24
Nebari: 2023.7.2.dev

### Compute environment

AWS

**Comment by costrouc** [comment]
This could be resolved by a single line of adding a sys.exit call or calling the typer failure function (I think it's called abort).

**Comment by sblair-metrostar** [comment]
> This could be resolved by a single line of adding a sys.exit call or calling the typer failure function (I think it's called abort).

@costrouc Looks like `typer.Abort()` is already being called but not raised. Was able to confirm that raising it [fixes the issue](https://github.com/nebari-dev/nebari/blob/33ae48909685b10d759f8eaf402deddcae658511/src/_nebari/subcommands/validate.py#L44).

**Comment by sblair-metrostar** [comment]
The fix for this was merged with [PR 1915](https://github.com/nebari-dev/nebari/pull/1915), should be able to close this issue.
