### ISSUE TITLE
[BUG] - Nebari init fails with --auth-provider custom

### ISSUE THREAD

**Issue by sblair-metrostar** [nebari-dev/nebari#1934]
### Describe the bug

Running `nebari init ... --auth-provider custom` throws an error, "No registered Authentication type called custom". The --help content says this should be a valid option.

![image](https://github.com/nebari-dev/nebari/assets/70233904/db77424a-c278-46e2-b0e3-34e26f4750cc)

### Expected behavior

Option 1. `--auth-provider custom` should work without error
Option 2. `custom` should be removed from the list of available options

### OS and architecture in which you are running Nebari

Ubuntu Linux, x64

### How to Reproduce the problem?

`nebari init local --project-name foobar --auth-provider custom`

![image](https://github.com/nebari-dev/nebari/assets/70233904/124e6b37-e7df-4701-b461-fa04e0a11e93)

### Versions and dependencies used.

Nebari: 2023.7.2.dev

### Compute environment

None

**Comment by iameskild** [comment]
@costrouc @viniciusdc is it safe to remove `custom` as an option? I thought there were folks who still used it, perhaps I'm misremembering.

**Comment by iameskild** [comment]
As I look at this more, I think the custom auth type can probably be removed. As for the attempt-fixes, we might be able to repurpose it as a way to by pass having the user accept the y for image upgrades, etc.

**Comment by sblair-metrostar** [comment]
> As I look at this more, I think the custom auth type can probably be removed. As for the attempt-fixes, we might be able to repurpose it as a way to by pass having the user accept the y for image upgrades, etc.

Agreed. According to [this code](https://github.com/nebari-dev/nebari/blob/f6d6a1b340d9cf3d6e64f5f83d518cd02489ebb2/src/_nebari/upgrade.py#L306), custom authenticators were deprecated some time ago. I'll work on a PR to remove that option from the CLI so we can close this out.

**Comment by iameskild** [comment]
Thanks for following up @sblair-metrostar. I think we can move forward with removing this as an option in the CLI.
