### ISSUE TITLE
[BUG] - Nebari project_name validation is inconsistent, doesn't allow numbers

### ISSUE THREAD

**Issue by sblair-metrostar** [nebari-dev/nebari#1947]
### Describe the bug

The `nebari init` project-name validation message says the value must "_begin with a letter and consist of letters, numbers, dashes, or underscores._" However, actually including numbers results in a validation error. Also, the `nebari init` and `nebari validate` messaging around this is inconsistent.

### Expected behavior

1. (Preferred) Numbers should be permitted in the `project_name` yaml field and `--project-name` init argument as indicated by the validation message.
2. The validation message should be updated to remove numbers as valid content.

### OS and architecture in which you are running Nebari

Ubuntu Linux, x64

### How to Reproduce the problem?

``` bash
nebari init local --project-name foobar123
```
![image](https://github.com/nebari-dev/nebari/assets/70233904/78a4cd84-cbab-411f-8411-7dd1fac2ba1f)

``` bash
cat project-name-with-numbers.yaml
project_name: foobar123

nebari validate -c project-name-with-numbers.yaml
```
![image](https://github.com/nebari-dev/nebari/assets/70233904/fa170296-151c-4a53-a621-2c5c92d082d3)

### Versions and dependencies used.

Nebari: 2023.7.2

### Compute environment

None

### Anything else?

Unclear which, if any, cloud providers take issue with numbers in resource names, but I've tested this locally with AWS by adding `0-9` to the relevant locations in the regex and had no problems on deployment. Would very much appreciate having this option, even if the enforcement has to vary by cloud.

**Comment by pavithraes** [comment]
@sblair-metrostar Thanks for this issue, and for including enough context+details! I think #1813 is tracking the same issue? If you agree, please free to close this. :)

**Comment by sblair-metrostar** [comment]
> @sblair-metrostar Thanks for this issue, and for including enough context+details! I think #1813 is tracking the same issue? If you agree, please free to close this. :)

Agreed, and apologies for missing the duplicate. The details on #1813 probably need updated as the specifics have changed a bit with the extensions rewrite.
