### ISSUE TITLE
[MAINT] - Integrate latest conda-store versions

### ISSUE THREAD

**Issue by pavithraes** [nebari-dev/nebari#1948]
### Feature description

Once we have new conda-store releases, we need to update their versions on Nebari, test it, and include it in an upcomming Nebari release.

### Value and/or benefit

Users get newest conda-store features.

### Anything else?

Note: This is currently blocked by conda-store releases. This issue is to keep track of the work.

**Comment by kcpevey** [comment]
Need this for both local and cloud versions

**Comment by trallard** [comment]
conda-store versions to use:

* conda-store: [2023.9.2](https://pypi.org/project/conda-store/)
* conda-store-UI: [2023.9.3](https://www.npmjs.com/package/@conda-store/conda-store-ui/v/2023.9.3)
* jlab-conda-store: [2023.9.1](https://pypi.org/project/jupyterlab-conda-store/)

**Comment by iameskild** [comment]
@pavithraes can we consider this completed now that we've updated conda-store?

**Comment by iameskild** [comment]
After more testing, we have run into a few conda-store issues that should be resolved before including the newer version of conda-store:

- https://github.com/conda-incubator/conda-store/issues/601
- https://github.com/conda-incubator/jupyterlab-conda-store/issues/25

**Comment by pavithraes** [comment]
Two more issues that need resolution:
- https://github.com/conda-incubator/conda-store/issues/598
- https://github.com/conda-incubator/jupyterlab-conda-store/pull/24

**Comment by iameskild** [comment]
Closed by #2092
