### ISSUE TITLE
[ENH] - Remove ability to easily install python packages globally in pip

### ISSUE THREAD

**Issue by costrouc** [nebari-dev/nebari#1970]
### Feature description

Set the environment variable `PIP_REQUIRE_VIRTUALENV=true` to prevent global pip installs of packages.

I tried this within a docker container and this is the error messages that users would get

```shell
$ docker run -it python bash
root@f5040281fa1e:/# export PIP_REQUIRE_VIRTUALENV=true
root@f5040281fa1e:/# pip install numpy
ERROR: Could not find an activated virtualenv (required).
```

### Value and/or benefit

We want to prevent users from easily installing within `$HOME/.local` in nebari. Since this breaks environments often.

**Comment by dharhas** [comment]
How do we deal with development packages? i.e. things we currently install with `pip install -e .`

**Comment by kcpevey** [comment]
Resolved by https://github.com/nebari-dev/nebari/pull/2191
