### ISSUE TITLE
[BUG] - `PROJECT_ID` env variable is not working for GCP deployment

### ISSUE THREAD

**Issue by fangchenli** [nebari-dev/nebari#1989]
### Describe the bug

According to the doc, the `PROJECT_ID` env variable is required for gcp deployment. But during deployment, terraform throw an error

```
[terraform]: module.terraform-state.module.gcs.google_storage_bucket.static-site: Creating...
[terraform]: ╷
[terraform]: │ Error: project: required field is not set
[terraform]: │
[terraform]: │   with module.terraform-state.module.gcs.google_storage_bucket.static-site,
[terraform]: │   on modules/gcs/main.tf line 1, in resource "google_storage_bucket" "static-site":
[terraform]: │    1: resource "google_storage_bucket" "static-site" {
```

To fix it, another env variable `GOOGLE_PROJECT` also needs to be set to the project id.

### Expected behavior

We need to determine the exact variable or set of variables required for gcp deployment and modify the doc/code accordingly.

### OS and architecture in which you are running Nebari

M1 mac

### How to Reproduce the problem?

Following the nebari deployment doc.

### Versions and dependencies used.

`conda 23.7.3`

`Client Version: v1.28.1`

`2023.7.2.dev43+gf6d6a1b3`

### Compute environment

GCP

### Anything else?

part of #1952

**Comment by iameskild** [comment]
Thanks @fangchenli! I will test as soon as I can and provide some feedback.
