### ISSUE TITLE
[ENH] - explicitly check required GCP API

### ISSUE THREAD

**Issue by fangchenli** [nebari-dev/nebari#1990]
### Feature description

Nebari deployment on GCP requires a set of GCP APIs enabled. Currently, this is not on the Nebari GCP doc, and disabled API will get reported by Terraform. We should explicitly check for the availabilities of those APIs at the beginning of the deployment and only start the deployment when all required APIs are enabled. 

### Value and/or benefit

This check would smooth the deployment process and reduce calls to GCP.

### Anything else?

part of #1952

**Comment by fangchenli** [comment]
Doc update: https://github.com/nebari-dev/nebari-docs/pull/373

**Comment by pavithraes** [comment]
Closing as complete, please feel free to re-open is needed. :)
