### ISSUE TITLE
[ENH] - use cache in CI

### ISSUE THREAD

**Issue by fangchenli** [nebari-dev/nebari#2045]
### Feature description

Currently, it takes over 20 minutes to install Nebari with all its dependencies in CI. We could cache all dependencies or the environment to speed it up.

### Value and/or benefit

To reduce turnover time and make the development experience smoother.

**Comment by iameskild** [comment]
This is a good idea, do you have any more information on what it would take to get the cache setup?

**Comment by fangchenli** [comment]
Closed by #2071 and #2073, cache is no longer needed.
