### ISSUE TITLE
[BUG] - Wrong error raised when an invalid `provider` is given

### ISSUE THREAD

**Issue by fangchenli** [nebari-dev/nebari#2054]
### Describe the bug

The `provider` field is defined in `schema.Main`, but there is a `root_validator` that uses `provider` in another Model.

https://github.com/nebari-dev/nebari/blob/056b420059d5121898cfbf3db6c8da23241f333c/src/_nebari/stages/infrastructure/__init__.py#L515-L520

When an invalid value for `provider` is given, it won't be set when this `root_validator` is called. So, instead of seeing a validation error on the given value. We see a key error from the `root_validator`.

A simple demo:
```python
def test_provider_validation_demo():
    from typing import Optional

    from pydantic import BaseModel, root_validator

    from nebari.schema import ProviderEnum

    class Model1(BaseModel):
        provider: ProviderEnum

    class Model2(BaseModel):
        variable1: Optional[str]

        @root_validator
        @classmethod
        def _validate_provider(cls, values):
            assert "provider" in values, "provider is not set"
            return values

    class Model3(BaseModel):
        variable2: Optional[int]

    config_schema = type("ConfigSchema", (Model1, Model2, Model3), {})
    config_dict = {
        "provider": "fake",
    }
    config = config_schema(**config_dict)
    print(config)
```

In the output of this demo, we can actually see both errors:
```
pydantic.error_wrappers.ValidationError: 2 validation errors for ConfigSchema
provider
  value is not a valid enumeration member; permitted: 'local', 'existing', 'do', 'aws', 'gcp', 'azure' (type=type_error.enum; enum_values=[<ProviderEnum.local: 'local'>, <ProviderEnum.existing: 'existing'>, <ProviderEnum.do: 'do'>, <ProviderEnum.aws: 'aws'>, <ProviderEnum.gcp: 'gcp'>, <ProviderEnum.azure: 'azure'>])
__root__
  provider is not set
assert 'provider' in {'variable1': None, 'variable2': None} (type=assertion_error)
```

But in Nebari, we only see this:
```
  File "/Users/fangchenli/Workspace/nebari/src/_nebari/stages/infrastructure/__init__.py", line 528, in check_provider
    values["provider"] == schema.ProviderEnum.local
KeyError: 'provider'
```

A test affected by this is `test_cli_upgrade.py::test_cli_upgrade_fail_invalid_file`. It's not testing the expected behavior. 

### Expected behavior

When an invalid value for `provider` is given, we should see an appropriate error message.

### OS and architecture in which you are running Nebari

macOS M1

### How to Reproduce the problem?

```python
from nebari.plugins import nebari_plugin_manager

@pytest.fixture
def config_schema():
    return nebari_plugin_manager.config_schema

def test_provider_validation(config_schema):
    config_dict = {
        "project_name": "test",
        "provider": "fake",
    }
    config = config_schema(**config_dict)
```

### Versions and dependencies used.

```
conda --version
conda 23.9.0

kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
```

### Compute environment

None

### Anything else?

We also see this in #1928

**Comment by iameskild** [comment]
Thanks for the thorough issue description. I ran your snippets and got back what you've shown.
