### ISSUE TITLE
[BUG] - Guided Init fails for Digital Ocean ("do") due to bug in init.py

### ISSUE THREAD

**Issue by biztos** [nebari-dev/nebari#2057]
### Describe the bug

When running `nebari init --guided-init` for cloud provider `do` (Digital Ocean), with fully valid inputs, the installer fails with a Python `TypeError` (see Command Output).

A quick look at the source code shows that in `src/_nebari/subcommands/init.py` line 330 will fail if `AWS_SECRET_ACCESS_KEY` is not set in the environment -- which of course it would not be if you're using Digital Ocean:

https://github.com/nebari-dev/nebari/blob/8e181bd923f467e02f9ef62eb8b17e2ec3598df3/src/_nebari/subcommands/init.py#L330

I am not submitting a patch because I do not yet understand why `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` are being set in the first place for a non-AWS provider -- and so I humbly request that a comment be added to this code explaining why this is being done.

### Expected behavior

Guided init should work for Digital Ocean.

### OS and architecture in which you are running Nebari

macOS 13.5.2 (22G91) (M1)

### How to Reproduce the problem?

1. clear any AWS environment variables
2. nebari init --guided-init
3. choose "do" for cloud provider
4. provide valid data for all prompts
5. observe the error (always)

### Command output

```bash session
...private data redacted, error below:

│ /opt/homebrew/lib/python3.11/site-packages/_nebari/subcommands/init.py:654 in guided_init_wizard │
│                                                                                                  │
│   651 │   │   ).unsafe_ask()                                                                     │
│   652 │   │                                                                                      │
│   653 │   │   if not disable_checks:                                                             │
│ ❱ 654 │   │   │   check_cloud_provider_creds(                                                    │
│   655 │   │   │   │   cloud_provider=inputs.cloud_provider,                                      │
│   656 │   │   │   │   disable_prompt=ctx.params.get("disable_prompt"),                           │
│   657 │   │   │   )                                                                              │
│                                                                                                  │
│ /opt/homebrew/lib/python3.11/site-packages/_nebari/subcommands/init.py:330 in                    │
│ check_cloud_provider_creds                                                                       │
│                                                                                                  │
│   327 │   │   │   hide_input=True,                                                               │
│   328 │   │   )                                                                                  │
│   329 │   │   os.environ["AWS_ACCESS_KEY_ID"] = os.getenv("SPACES_ACCESS_KEY_ID")                │
│ ❱ 330 │   │   os.environ["AWS_SECRET_ACCESS_KEY"] = os.getenv("AWS_SECRET_ACCESS_KEY")           │
│   331 │                                                                                          │
│   332 │   # AZURE                                                                                │
│   333 │   elif cloud_provider == ProviderEnum.azure.value.lower() and (                          │
│ in __setitem__:684                                                                               │
│ in encode:758                                                                                    │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: str expected, not NoneType
```

### Versions and dependencies used.

nebari 2023.9.1rc2.dev1+g056b420

### Compute environment

Digital Ocean

**Comment by dcmcand** [comment]
Thanks for the report @biztos . This looks like a simple typo. 

The line `os.environ["AWS_SECRET_ACCESS_KEY"] = os.getenv("AWS_SECRET_ACCESS_KEY")` should say ` os.environ["AWS_SECRET_ACCESS_KEY"] = os.getenv("SPACES_SECRET_ACCESS_KEY")` .

The AWS credentials are set because Digital Ocean Spaces have an s3 compatible api, so this allows us to reuse the s3 code.
