### ISSUE TITLE
[BUG] - Incorrect format for Gitops repo_url in init.py (http instead of https).

### ISSUE THREAD

**Issue by biztos** [nebari-dev/nebari#2058]
### Describe the bug

The following line defines a format for the Gitops repo URL which is incorrect and fails validation when assigned to `inputs.repository`:

https://github.com/nebari-dev/nebari/blob/8e181bd923f467e02f9ef62eb8b17e2ec3598df3/src/_nebari/subcommands/init.py#L776

This causes Guided Init to fail if Gitops is selected.  Changing the format to use `https` instead of `http` appears to fix this.

NOTE: the Guided Init help text also incorrectly refers to `http` instead of `https`.

### Expected behavior

The constructed URL should be valid and initialization should complete.

### OS and architecture in which you are running Nebari

macOS 13.5.2 (22G91) (M1)

### How to Reproduce the problem?

1. `nebari init --guided-init`
2. Give valid responses to prompts.
3. Choose Y for Gitops.
4. Give valid responses to prompts.
5. Observe Python ValidationError.

### Versions and dependencies used.

nebari version 2023.9.1rc2.dev1+g056b420

### Compute environment

None

**Comment by iameskild** [comment]
Hi @biztos! Thanks for sharing this with us. I believe there is an [open PR](https://github.com/nebari-dev/nebari/pull/2039) with this fix 💪
