### ISSUE TITLE
[BUG] - cloud provider initialized without required inputs

### ISSUE THREAD

**Issue by fangchenli** [nebari-dev/nebari#2064]
### Describe the bug

While working on #2056, I discovered that when a `provider` is given but the corresponding provider field is not defined, we are trying to initialize provider objects in https://github.com/nebari-dev/nebari/blob/16866933dcbe9cd1ca08247f0cb245c94f11c6a7/src/_nebari/stages/infrastructure/__init__.py#L527-L546

It works for `local` and `existing` providers because they don't require user inputs. But for all cloud providers, user inputs are mandatory so the current implementation doesn't work.

We haven't seen this before due to the lack of unit test. And, when user run `nebari initialize`, all the required fields for cloud provider got rendered so it won't reach the object initialization code in the `root_validator`. 

The the rendering is here:
https://github.com/nebari-dev/nebari/blob/16866933dcbe9cd1ca08247f0cb245c94f11c6a7/src/_nebari/initialize.py#L112-L176

### Expected behavior

We need to align the render and initialization code to clarify where and how the rendering/information filling is done.

### OS and architecture in which you are running Nebari

macOS M1

### How to Reproduce the problem?

```python
@pytest.fixture
def config_schema():
    return nebari_plugin_manager.config_schema

def test_provider_validation(config_schema):
    config_dict = {
        "project_name": "test",
        "provider": "gcp",
    }
    config = config_schema(**config_dict)
```
After #2056, the initialization of cloud provider object is skipped so the code snippet won't raises an error.

### Compute environment

None

**Comment by iameskild** [comment]
Thanks for digging into this @fangchenli! 

A summary of this would be: we need to decide how we initialize the `nebari-config.yaml`, using the code in `initialize.py` or relying on the pydantic models within the stages themselves.

**Comment by Adam-D-Lewis** [comment]
The affected code is gone.  I'm going to close this since it may no longer be relevant.
