### ISSUE TITLE
[BUG] NFS not mounting to Dask workers

### ISSUE THREAD

**Issue by iameskild** [nebari-dev/nebari#2070]
### Describe the bug

I'm been sometime since I've tried reading/writing from the NFS while using Dask but this was at one point possible.  

### Expected behavior

The dask-workers have access to the data in the user's home directory.

### OS and architecture in which you are running Nebari

Linux

### How to Reproduce the problem?

Try reading a file that exists in home directory while running on a dask worker.

### Compute environment

None

### Anything else?

I believe the solution is to convert the `emptyDir` to `persistentVolumeClaim` here:

https://github.com/nebari-dev/nebari/blob/270aad6e6de7c45542099ec6f0bfc5cd3c2e2957/src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/dask-gateway/files/gateway_config.py#L211C35-L211C84

**Comment by iameskild** [comment]
We need a way to get the pvc claim name from the config file. JupyterHub we can use [ztjh.get_config](https://github.com/nebari-dev/nebari/blob/4db840003c33172c7e6ca321bba8ffb2d7df07df/src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/jupyterhub/03-profiles.py#L17C5-L17C55) but I'm not sure if dask gateway does. 

Needs more investigation.

**Comment by dharhas** [comment]
Do we want to do this though? In early days of Qhub my understanding from @costrouc was that mounting the NFS share to multiple dask workers had performance implications and it was better to disallow it and only use dask-gateway with block storage.

**Comment by iameskild** [comment]
Thanks @dharhas, that's a good point! This probably not something we should continue to explore. Closing for now. 

cc @kcpevey

**Comment by kcpevey** [comment]
I just want to chime in as an end user here. I understand the performance challenges of having a lot of machines trying to read or write to the NFS at one time. Pushing everything to cloud storage is what I would say is the optimal solution from a DevOps standpoint but what about:

* Users who don't have access to a cloud storage account (many gov't users).
* Users who have a dataset (perhaps small) on Nebari who need to use Dask for heavy compute. Forcing cloud storage adds complexity to the workflow that we could simplify with NFS access. 

As a separate point - if we're choosing to not support this functionality, should we clean up these volume mount configurations? [here](https://github.com/nebari-dev/nebari/blob/270aad6e6de7c45542099ec6f0bfc5cd3c2e2957/src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/dask-gateway/files/gateway_config.py#L211-L225)

```
        "worker_extra_pod_config": {"volumes": [{"name": "home", "emptyDir": {}}]},
        "worker_extra_container_config": {
            "securityContext": {"runAsUser": uid, "runAsGroup": gid, "fsGroup": gid},
            "workingDir": f"/home/{username}",
            "volumeMounts": [
                {
                    "mountPath": f"/home/{username}",
                    "name": "home",
                }
            ],
        },
        "environment": {
            "HOME": f"/home/{username}",
        },
```
