### ISSUE TITLE
[BUG] - Incorrect documentation link shown after deployment.

### ISSUE THREAD

**Issue by biztos** [nebari-dev/nebari#2081]
### Describe the bug

After a successful `nebari deploy` you will see the following notice:

> Additional administration docs can be found at https://docs.nebari.dev/en/stable/source/admin_guide/

This link does not work, and the current Nebari docs have no equivalent path.

Please replace with a link to the live Admin Guide, wherever that may be.

The source is in `src/_nebari/deploy.py` line 74:

https://github.com/nebari-dev/nebari/blob/c57d50128a69057e98d8a91b794f7d5cab7673ee/src/_nebari/deploy.py#L74

### Expected behavior

User should be directed to the correct Admin Guide.

### OS and architecture in which you are running Nebari

Alpine Linux

### How to Reproduce the problem?

`nebari deploy -c nebari-config.yaml`

### Command output

```bash session
[terraform]: Nebari deployed successfully
...
Additional administration docs can be found at https://docs.nebari.dev/en/stable/source/admin_guide/
```

### Compute environment

None

**Comment by iameskild** [comment]
Thanks for reporting this @biztos! I updated the link in PR #2039 👍
