### ISSUE TITLE
[BUG] - Newest release of nebari overrides supplied values for existing and local deployment and existing is broken

### ISSUE THREAD

**Issue by costrouc** [nebari-dev/nebari#2086]
### Describe the bug

Existing provider is broken due to https://github.com/nebari-dev/nebari/blob/376ffbaac6b555481eafb9686a76d9def772f548/src/_nebari/stages/infrastructure/__init__.py#L546-L547. Additionally the default values for local and existing are always applied which breaks does not allow local / existing deployments. It is complaining with a kube_context being not and is ignoring my configuration for existing.

### Expected behavior

Should preserve local/existing deployment

### OS and architecture in which you are running Nebari

latest 2023.10.1.

### How to Reproduce the problem?

```
provider: existing
existing:
  kube_context: thisisacontext
```

### Compute environment

None

**Comment by fangchenli** [comment]
relate to #2064
