### ISSUE TITLE
[BUG] - conda-store web interface only shows envs in global, nebari-git and user's namespaces

### ISSUE THREAD

**Issue by rsignell** [nebari-dev/nebari#2098]
### Describe the bug

We upgraded from nebario v2023.1.1 to  v2023.10.1 and along with that, we got the new web interface to conda-store.  

1.  The new interface doesn't seem to allow for creation of environments in namespaces other than `nebari-git`, and the user's `namespace`.  For example, we had most users in a group called `users` and many environments were in the `users` namespace.  But that namespace doesn't appear in any pick list and I can't see how to add it. 
2. I tried to look at the documentation for conda-store web interface to see if I was missing something, but it seems to point to the old web interface
3. The new interface seems like it went in the wrong direction -- it's much easier to see all the packages and make changes via cut-and-paste in the old yaml view (so now every single time I want to edit an environment I toggle on the yaml view first, which is annoying)

### Expected behavior

I want the functionality of the old behavior back!

### OS and architecture in which you are running Nebari

AWS

### How to Reproduce the problem?

any conda-store (e.g. https://nebari.esipfed.org/conda-store)

### Compute environment

AWS

**Comment by dharhas** [comment]
@rsignell-usgs

The old interface is still available at `<url>/conda-store/admin`

The GUI interface should be have all the same features as the old version except for managing namespaces. 

The issue might be that you are not logged in or that the permissions are wrong in keycloak.

**Comment by rsignell** [comment]
@dharhas , okay, thanks.   I think you are right -- I didn't realize I wasn't logged into conda-store.  
But so great to know the old interface is still accessible! 
With the new interface I couldn't figure out how to delete old environment versions or upload environment .yaml files.

**Comment by dharhas** [comment]
Deleting is inside the edit command. I think this should be changed.

I think you can drag and drop a yaml file but I'm not sure. 

The UI needs work. Issues/Feedback welcome
