### ISSUE TITLE
[ENH] - Update Nebari to the 2023.10.1 conda-store release

### ISSUE THREAD

**Issue by kcpevey** [nebari-dev/nebari#2124]
### Feature description

We should update the nebari docker images to include the latest conda-store release, 2023.10.1. 

### Value and/or benefit

Staying up to date with conda-store!

### Anything else?

This is the line where this should be updated: https://github.com/nebari-dev/nebari-docker-images/blob/a1e02f905f3f175d34c43b83430ad51710b49b76/jupyterlab/environment.yaml#L58

**Comment by kcpevey** [comment]
To be clear, this issue is to update the jupyterlab extension version. The standalone react app at `/conda-store` HAS been updated.

**Comment by pavithraes** [comment]
This is done: [nebari-docker-images/pull/99](https://github.com/nebari-dev/nebari-docker-images/pull/99), it will be available in the next release. Adding to the release milestone. :)
