### ISSUE TITLE
[BUG] - KeyValueDict error when deploying to existing infrastructure

### ISSUE THREAD

**Issue by oftheaxe** [nebari-dev/nebari#2128]
### Describe the bug

In 
https://github.com/nebari-dev/nebari/blob/efc291339c113cd244eed4778272e77d8026b0c0/src/_nebari/stages/infrastructure/__init__.py#L170C1-L171C1

line should convert node_selectors to dict, otherwise the JSON serializer produces an error.
`
return config.existing.dict()["node_selectors"]
`

### Expected behavior

To properly convert to dict, so it's JSON serializable.

### OS and architecture in which you are running Nebari

Deploying to existing Kubernetes

### How to Reproduce the problem?

Terraform deployment fails when trying to serialize node_selectors to JSON

### Compute environment

None

### Anything else?

Will resolve https://github.com/orgs/nebari-dev/discussions/2118

**Comment by Adam-D-Lewis** [comment]
Thanks for contributing @oftheaxe.  Would you be interested in contributing a PR to fix this?
