### ISSUE TITLE
[BUG] - 2023.11.1 Upgrade does not remove kbatch from config

### ISSUE THREAD

**Issue by kenafoster** [nebari-dev/nebari#2129]
### Describe the bug

Nebari version 2023.11.1 installed

nebari-config.yaml has version 2023.10.1 and is valid for that version

Ran `nebari upgrade -c nebari-config.yaml` successfully (nebari_version: 2023.11.1 was set in config)

However, the config block below was not removed so I still got 'Extra fields not permitted error' when trying to run nebari deploy after the upgrade

kbatch:
  enabled: true

### Expected behavior

The upgrade command should clean up any config items that are no longer accepted in v2023.11.1

### OS and architecture in which you are running Nebari

Ubuntu 22.04 amd64

### How to Reproduce the problem?

With nebari==2023.11.1 installed, run nebari upgrade then nebari validate on a config file that begins with these two entries:

...
kbatch:
  enabled: true
...
nebari_version: 2023.10.1
...

### Compute environment

None

**Comment by Adam-D-Lewis** [comment]
Closing as won't fix.  Users have likely resolved this themselves by now, and it's unlikely people continue to see this issue now.
