### ISSUE TITLE
[ENH] - Move to JupyterLab 4.x

### ISSUE THREAD

**Issue by aktech** [nebari-dev/nebari#2130]
### Feature description

It's been over 6 months since JupyterLab 4.x was released and we're still on 3.x.  Upgrade JupyterLab to 4.x

### Value and/or benefit

To be able to use latest features and use extensions that are unsupported on JupyterLab < 4.x

### Anything else?

```[tasklist]
### Tasks
- [ ] https://github.com/nebari-dev/nebari/issues/2134
- [ ] https://github.com/nebari-dev/nebari/issues/2135
```

**Comment by aktech** [comment]
Relevant PR: https://github.com/nebari-dev/nebari-docker-images/pull/101

**Comment by aktech** [comment]
Somewhat related: https://github.com/conda-incubator/jupyterlab-conda-store/issues/29

**Comment by dcmcand** [comment]
closed by https://github.com/nebari-dev/nebari-docker-images/pull/101
