### ISSUE TITLE
[META] - Upgrade to JupyterHub 4.x

### ISSUE THREAD

**Issue by aktech** [nebari-dev/nebari#2132]
### Feature description

It's been over 6 months since the release of JupyterHub 4.x. 

### Value and/or benefit

To be able to install App Launcher, we need to upgrade to JupyterHub 4.x

**Comment by pavithraes** [comment]
Will be resolved by #2011

**Comment by dcmcand** [comment]
closed by https://github.com/nebari-dev/nebari-docker-images/pull/103
