### ISSUE TITLE
[BUG] - Use of `exec` with non-literal value in conda_store_config.py

### ISSUE THREAD

**Issue by sblair-metrostar** [nebari-dev/nebari#2136]
### Describe the bug

A line in [conda_store_config.py](https://github.com/nebari-dev/nebari/blob/main/src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/conda-store/config/conda_store_config.py#L176) is being reported as a security vulnerability in our Gitlab pipeline. Need to either replace this code with something safer or assess the necessity and risk in order to triage.

### Expected behavior

No medium or higher vulnerabilities identified in Nebari.

### OS and architecture in which you are running Nebari

Linux, x64

### How to Reproduce the problem?

Run a SAST scan in a Gitlab pipeline with the following:

![image](https://github.com/nebari-dev/nebari/assets/70233904/89cae308-bb14-4e86-99d3-0dc989013dcf)

![image](https://github.com/nebari-dev/nebari/assets/70233904/c990d760-943a-4d9e-966e-115221194590)

### Versions and dependencies used.

Nebari: 2023.9.1rc1

### Compute environment

AWS

**Comment by Adam-D-Lewis** [comment]
Thanks for contributing to Nebari @sblair-metrostar.  The code that is executed would come from the `nebari-config.yaml` file under the `conda_store.extra_config` key so it's not supplied by an external user, but rather the Nebari administrator.  This is expected and I think we can close this issue.  Feel free to reopen if you have additional comments/questions.
