### ISSUE TITLE
[ENH] - Remove non JLab 4 compatible integrations

### ISSUE THREAD

**Issue by kcpevey** [nebari-dev/nebari#2138]
### Feature description

The jupyter-tensorboard integration hasn't been updated since 2020. Its tested on python 3.4, 3.5, and 3.6. I think its safe to say that it won't be updated for JupyterLab 4 compatibility. 

With the next release Nebari will upgrade to JL4, which means this feature will need to be deprecated. 

### Value and/or benefit

Jupyterlab 4 compatible extensions :)

**Comment by kcpevey** [comment]
Side note - I noticed earlier this week that VS Code has an extension for tensorboard so for anyone still interested in this feature, that might be of interest.

**Comment by kcpevey** [comment]
Need to remove tensorboard and nvdashboards

**Comment by dcmcand** [comment]
Closed by https://github.com/nebari-dev/nebari-docker-images/pull/101
