### ISSUE TITLE
Kbatch Pods/Ingress is not installed/available while deploying new Infra on Digital Ocean

### ISSUE THREAD

**Issue by atiframzan89** [nebari-dev/nebari#2140]
### Context

While deploying the new infrastructure on Digital Ocean (using the [link](https://www.nebari.dev/docs/how-tos/nebari-do/)) using nebari the kbatch package/pod/kbatch-proxy is not being installed by default.

While trying to install it through jupyterhub (using below command) run command its still not working because there are no pods / services deployed for kbatch. 
```
kbatch configure --token <JUPYTERHUB_API_TOKEN> \
  --kbatch-url http://kbatch-kbatch-proxy.dev.svc.cluster.local/
```
![nebari-kbatch](https://github.com/nebari-dev/nebari/assets/78168446/d2327da5-18ed-43ec-a043-58b13f33e0d3)

Version Used for this deployment: 2023.11.1

### Value and/or benefit

As per Nebari documentation this by default comes with it.

### Anything else?

https://www.nebari.dev/docs/tutorials/kbatch/

**Comment by dharhas** [comment]
@atiframzan89 We depreciated/removed kbatch in the last release because the upstream project is not maintained. We have a new integration with Jupyter Scheduler that has most of the functionality of kbatch. Were you actively using kbatch?

**Comment by marcelovilla** [comment]
I'm closing this issue as we [removed `kbtach` in version 2023.12.1](https://www.nebari.dev/docs/references/release/#release-2023121---december-15-2023). Feel free to reopen if necessary.
