### ISSUE TITLE
[CI] - DigitalOcean token expired, CI failing

### ISSUE THREAD

**Issue by aktech** [nebari-dev/nebari#2142]
### Describe the bug

The CI has been failing for sometime now for DigitalOcean provider: https://github.com/nebari-dev/nebari/actions/runs/7097435616/job/19317548521

This is most likely due to token expiration.

### Expected behavior

CI Passing

### OS and architecture in which you are running Nebari

NA

### How to Reproduce the problem?

Trigger CI for DO provider

### Compute environment

None

**Comment by dcmcand** [comment]
Fixed by @costrouc
