### ISSUE TITLE
[ENH] - Automate Nebari cluster backups as part of the Gitops CI/CD pipeline

### ISSUE THREAD

**Issue by kalpanachinnappan** [nebari-dev/nebari#2144]
### Feature description

Create a full backup of the Nebari cluster before the `nebari deploy` CI job runs in a CI/CD pipeline, e.g. Gitlab CI. 
The backup should be uploaded to a secure storage (like GCS for Google Cloud).  
This would ensure the team has a backup of the most recent cluster state before Terraform runs during `nebari deploy`. This backup can then be used to restore the cluster in the case the deploy was unsuccessful. 

### Value and/or benefit

- backup data to avoid data loss in case of cluster pipeline problems
- Backup process is part of the Gitops Nebari pipeline

**Comment by viniciusdc** [comment]
will be handled by the backup-restore serivce once its running, before deployed to nebari the binary can also be run in CI/CD, I will be closing and referencing it to #2648
