### ISSUE TITLE
[ENH] - Mechanism to pre-populate Nebari with demo/example content

### ISSUE THREAD

**Issue by dharhas** [nebari-dev/nebari#2179]
### Feature description

We need a mechanism to deploy examples/demos to Nebari for new users to interact with.

Ideally, this would be pulled from a set of git repos on first login but could potentially also be put in a read-only examples folder. The second option is not great since folks trying to run notebooks directly in the shared folder would hit errors.

options to explore include nbgitpuller and gitsync etc

### Value and/or benefit

It gives people a starting point to explore Nebari's features and helps us customize for different use cases.

**Comment by costrouc** [comment]
Several ideas on this:
  - pre-exec hook and run arbitrary bash code https://github.com/nebari-dev/nebari/blob/develop/src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/jupyterhub/03-profiles.py#L297C10-L297C10
  - init containers https://github.com/nebari-dev/nebari/blob/d612e9b5f63db0e810c1fe6fc0cd61b5bfa62641/src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/jupyterhub/03-profiles.py#L55

I think init containers captures what we want to do better. It is possible to have multiple init containers and this is guaranteed to run before the user starts jupyterlab.

**Comment by kcpevey** [comment]
Copying over some brainstorming ideas:
![image](https://github.com/nebari-dev/nebari/assets/15659110/5cf5158f-950b-46d9-9c00-7b3cb9b8ed52)

**Comment by viniciusdc** [comment]
Both of those seem like really compelling ideas, I am leaning towards the `init_container` approach as I we would have more control in case we would like to quickly test something new (just a configmap update) while the use of `nbgitpuller` requires updates in the nebari yaml in case we would like to update the link. 

So far we have:
- bash script or use of  `gitsync` as part of the init container for the jupyterlab pod, this allows further customization as we would have access to `traitlets/python`, username and quick debugging using k9s/configmap updates
  - The downside that I can see right now is the fact those changes would be included in the nebari codebase, so it will require direct update in the jupyter configmap to include this dynamic control.
  - The github repository would be statically linked to the codebase updates as well

- Use of git sync as suggested above on @kcpevey comment; this would allow easy inclusion of any GitHub repo without touching any code, though in case we want to update, this would require an admin to perform a redeployment.
  - The downside that I can foresee, is the management of the github repository after the user interacts with it, and the need of an admin to redeploy when a change is required.

**Comment by dcmcand** [comment]
a bash script that checks for a `.firstrun` file and no-ops if it is present is a way to ensure that the script only runs the first time. If the `.firstrun` file isn't present, then the script runs and creates the file at the end.

**Comment by pavithraes** [comment]
Notes from the Nebari sync:
- Dharhas suggested it'll be nice to have an `examples` section in `nebari-config.yaml` where the admin can specify example repos.

**Comment by dharhas** [comment]
fyi. we will need to use git-lfs after the git clone to pull in datasets.

**Comment by pavithraes** [comment]
From community meeting, the config will look like:

![Image](https://github.com/nebari-dev/nebari/assets/33131404/190f01f8-f1a1-48cf-a0fb-2a542283c1b6)

Instead of `pre_populate_repositories`, use one of the following:
- `default_repositories`
- `initial_repositories`
- `example_repositories`
- `demo_repositories`

cc @dharhas for name preference

Additionally, this features need to be documented and note that the docs should include:
- users may need to run `git-lfs` seperately
- we can only clone public repos
