### ISSUE TITLE
[BUG] - Disable conda-store jupyterlab extension

### ISSUE THREAD

**Issue by kcpevey** [nebari-dev/nebari#2181]
### Describe the bug

* disable extension
* replace with link to react app 

### Expected behavior

.

### OS and architecture in which you are running Nebari

.

### How to Reproduce the problem?

.

### Command output

```bash session
.
```

### Versions and dependencies used.

.

### Compute environment

None

**Comment by dcmcand** [comment]
extension was remove in https://github.com/nebari-dev/nebari-docker-images/commit/238837e66dfae6b02a1f4b0f90bc051c4d83366d
