### ISSUE TITLE
[ENH] - Make name of "nebari" menu item more generic

### ISSUE THREAD

**Issue by kcpevey** [nebari-dev/nebari#2216]
### Feature description

![image](https://github.com/nebari-dev/nebari/assets/15659110/7985e5d6-d79d-48d9-92ee-c44a9017a8a8)

It would be nice if the "Nebari" top menu was more generic. I have a usecase where the deployment is named and themed for a specific project. End users don't know and don't need to know that the underlying package is "nebari" and it would likely cause confusion. 

I propose we change this menu name to be something generic like `Services` or `Extras`. 

### Value and/or benefit

End users with custom theme applied will not be confused by the nebari menu.

**Comment by krassowski** [comment]
Maybe `Tools`? Of note, making `overrides.json` a templated file (https://github.com/nebari-dev/nebari/issues/2247) would allow for customization of the name.

**Comment by pavithraes** [comment]
From release planning meeting:
- Dharhas suggests adding Nebari docs item to the Help menu 
- Rename "Nebari" to "Nebari Services", and move it before "Help"
  - Rename "Hub Control Panel" to "Home"
  - Add "Stop Server" option that stops the machine?
- Top left "Jupyter" Favicon -> Nebari logo that goes to the home
- In "File", hide "Hub Control Panel" and "Logout"?

We'll need more input from UX designers and the community :)

A portion of these will be included in the next release, but we'll keep the issue open and tackle the rest in the release after next.

xref: #2217

**Comment by krassowski** [comment]
> Top left "Jupyter" Favicon -> Nebari logo that goes to the home

Let me know if you need help with this one. The others should be just adjusting the `overrides.json`

**Comment by marcelovilla** [comment]
@krassowski I'll take care of the other ones that involve only adjusting the `overrides.json` file but we would appreciate you taking care of changing the logo!
