### ISSUE TITLE
[ENH] - Programmatically added example repos cannot be deleted

### ISSUE THREAD

**Issue by kcpevey** [nebari-dev/nebari#2218]
### Feature description

If I try to delete a repo that was programmatically created via 
```
jupyterlab:
  initial_repositories:
    - <path/to/folder>: <github/repository/url>
```

I get a permission error: `rm: cannot remove 'examples/jatic-i3-demo': Permission denied`

### Value and/or benefit

This is an issue since the only way to get an updated example repo is to remove the repo folder. If I can't remove the folder, I can't pull an updated copy of the examples.

**Comment by dharhas** [comment]
@viniciusdc

**Comment by viniciusdc** [comment]
uhm, that's strange. I've tested the manual removal of the folders before, and it worked out, I might have missed something. Could you share the results of `ls -la` to check if the permissions are being propagated correctly?

**Comment by viniciusdc** [comment]
The bash code needs to be updated to correctly bind the user permissions to the newly created folders and subfolders, as it looks like it's only doing it for the cloned repo files/folders, disregarding the permissions of the parent directories. This is a straightforward fix, I will have a PR tomorrow morning. 

Side note: the docs will also need to be updated, as I forgot to mention that removing the `.firstrun` file will trigger the clone/pull action to run again, thus updating the head of the repo
