### ISSUE TITLE
EKS 1.26 end of standard support, June 2024

### ISSUE THREAD

**Issue by sblair-metrostar** [nebari-dev/nebari#2225]
### Context

Need to upgrade EKS to 1.29 (current as of January 2024) before June 2024.

https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html

### Value and/or benefit

Saves additional costs associated with extended support.

https://aws.amazon.com/blogs/containers/amazon-eks-extended-support-for-kubernetes-versions-pricing/

**Comment by Adam-D-Lewis** [comment]
BTW, Only version 1.28 is supported on Azure atm.

**Comment by Adam-D-Lewis** [comment]
I looked at upgrading to from 1.26 to 1.27 via Azure Console and it looks like the user-scheduler is using a deprecated API. 
![image](https://github.com/nebari-dev/nebari/assets/23342526/d6eaa480-586d-44a5-9609-e34793e5d1a1)

**Comment by Adam-D-Lewis** [comment]
I went ahead with the upgrade to 1.27 and the upgrade failed due to my cloud Quotas not being high enough, but after I fixed that things seemed to work fine.  I then upgraded to 1.28 and things seemed to work fine as well.

**Comment by Adam-D-Lewis** [comment]
Based on that, I think supporting at least up through k8s 1.28 will be very straight forward.

**Comment by dcmcand** [comment]
I have run 1.29 locally and everything seems to be working with some small changes to the local deployment that shouldn't impact cloud deployments. I think we should target 1.29 support.
