### ISSUE TITLE
[BUG] - Scheduler does not work when argo workflows are disabled

### ISSUE THREAD

**Issue by krassowski** [nebari-dev/nebari#2256]
### Describe the bug

When `argo_workflows` are disabled running notebooks with jupyter scheduler errors out.

### Expected behavior

If argo-workflows are disabled either:
- fall back to the single user jupyter-server based scheduler backend 
- disable jupyter scheduler extension dynamically

### OS and architecture in which you are running Nebari

-

### How to Reproduce the problem?

1. Set:

```yaml
argo_workflows:
  enabled: false
```

2. Open a notebook
3. Click on scheduler
4. Try to run the notebook
5. See "Failed" status

### Compute environment

None

**Comment by dharhas** [comment]
@krassowski 

Currently, Jupyter-Scheduler is the only feature in Nebari that requires Argo. 

The scheduler functionality is one that I would like to include in Nebari even without Argo. I'm not sure that is possible. 

> fall back to the single user jupyter-server based scheduler backend

My understanding is that the regular Jupyter-Scheduler requires your single user server to be running at all times (i.e. it is designed for a desktop usecase) and not the k8s use case.

Currently the Argo implementation does the following.

- It launches a pod on a schedule to run the notebook
- it mounts your home folder and the conda env folder to the pod so you have access files and python environments. This is done via the argo-workflow-controller extension that we wrote
- it destroys your pod after the task is completed

The question is if there is a native way to do this on k8s without Argo, i.e. using k8s-cron or similar.

**Comment by krassowski** [comment]
> My understanding is that the regular Jupyter-Scheduler requires your single user server to be running at all times

Yes, my thinking was: if an administrator does not enable Argo, users get a scheduler with a limited functionality, but in principle working (as long as the server is running); we could call it a "demo mode" (we could document this and even add disclaimers in UI when Argo is disabled).

> The question is if there is a native way to do this on k8s without Argo, i.e. using k8s-cron or similar.

Right, this is tracked in https://github.com/nebari-dev/argo-jupyter-scheduler/issues/1 - my understanding is that it is possible.
