### ISSUE TITLE
[BUG] -  EntityAlreadyExists  errors when upgrading from 2023.11.1 to 2024.1.1

### ISSUE THREAD

**Issue by rsignell** [nebari-dev/nebari#2271]
### Describe the bug

I upgraded my nebari config file from 2023.11.1 to nebari 2024.1.1 using `nebari upgrade` which went smoothly. 

When I ran `nebari deploy`, however, I got these terraform errors  complaining that resources already exist:
```
[terraform]: │ Error: error creating IAM Role (osc-training-dev-eks-cluster-role): EntityAlreadyExists: Role with name osc-training-dev-eks-cluster-role already exists.
[terraform]: │  status code: 409, request id: 7f06518f-7857-497c-9e82-1e9530c2eb38
[terraform]: │
[terraform]: │   with module.kubernetes.aws_iam_role.cluster,
[terraform]: │   on modules/kubernetes/policy.tf line 10, in resource "aws_iam_role" "cluster":
[terraform]: │   10: resource "aws_iam_role" "cluster" {
[terraform]: │
[terraform]: ╵
[terraform]: ╷
[terraform]: │ Error: error creating IAM Role (osc-training-dev-eks-node-group-role): EntityAlreadyExists: Role with name osc-training-dev-eks-node-group-role already exists.
[terraform]: │  status code: 409, request id: dffd675a-6907-473f-a011-ff78d633ac13
[terraform]: │
[terraform]: │   with module.kubernetes.aws_iam_role.node-group,
[terraform]: │   on modules/kubernetes/policy.tf line 39, in resource "aws_iam_role" "node-group":
[terraform]: │   39: resource "aws_iam_role" "node-group" {
[terraform]: │
[terraform]: ╵
[terraform]: ╷
[terraform]: │ Error: error creating ECR repository: RepositoryAlreadyExistsException: The repository with name 'osc-training-dev-jupyterlab' already exists in the registry with id '153379367922'
[terraform]: │
[terraform]: │   with module.registry-jupyterlab.aws_ecr_repository.main,
[terraform]: │   on modules/registry/main.tf line 1, in resource "aws_ecr_repository" "main":
[terraform]: │    1: resource "aws_ecr_repository" "main" {
```

### Expected behavior

I would expect the deployment to work, or tell me what I need to do.

### OS and architecture in which you are running Nebari

Deploy command on WSL, deployment on AWS

### How to Reproduce the problem?

see above!

### Versions and dependencies used.

conda 23.3.1
Client Version: v1.28.3
nebari 2024.1.1

### Compute environment

AWS

**Comment by rsignell** [comment]
I was able to work around this problem by going into the AWS console and manually deleting the resources, then retrying the deployment.    I had previously tried both `nebari destroy` and running the script `aws-force-destroy.sh`.    

 I see now that the [docs suggest running the python code `aws-force-destroy.py`](https://www.nebari.dev/docs/how-tos/nebari-destroy/#destroy-aws-resources-using-a-dev-tool-script), which I did not try.     Would that be preferred to the bash script?

**Comment by dcmcand** [comment]
@rsignell it sounds like you were using local state for terraform, is that correct? I think what happened here is when you removed the `stages/` folder to do the upgrade, it wiped out your terraform state. That makes terraform think it needs to deploy everything new, and it complains when there are already resources named the same.

**Comment by dcmcand** [comment]
I think that we should not be recommending that folks remove the `stages` folder on upgrade, especially if they are using local tf state.

**Comment by marcelovilla** [comment]
I am closing this issue as we're no longer recommending users to remove their `stages` folder when upgrading and that should get rid of the problem. @rsignell feel free to reopen it if you experience this again.
