### ISSUE TITLE
[BUG] - Shiny Apps don't seem to render correctly

### ISSUE THREAD

**Issue by Adam-D-Lewis** [nebari-dev/nebari#2273]
### Describe the bug

I created an R environment with r-irkernel and r-essentials dependencies.  I then tried running 
```
library(shiny)
library(ggplot2)

datasets <- c("economics", "faithfuld", "seals")
ui <- fluidPage(
  selectInput("dataset", "Dataset", choices = datasets),
  verbatimTextOutput("summary"),
  tableOutput("plot")
)

server <- function(input, output, session) {
  dataset <- reactive({
    get(input$dataset, "package:ggplot2")
  })
  output$summmry <- renderPrint({
    summary(dataset())
  })
  output$plot <- renderPlot({
    plot(dataset)
  }, res = 96)
}

shinyApp(ui, server)
```
from https://www.oreilly.com/library/view/mastering-shiny/9781492047377/ch01.html which should look like 
![image](https://github.com/nebari-dev/nebari/assets/23342526/97ec3372-a630-4e3c-8737-6bdee5c2df87).

![image](https://github.com/nebari-dev/nebari/assets/23342526/f10d8dd6-df8c-45a9-9f2f-951793c5cf91)

However upon visiting `https://nebari.mydomain.com/user/alewisqs@mydomain.com/proxy/4153` I only see 
![image](https://github.com/nebari-dev/nebari/assets/23342526/86a13c71-0e30-41bb-80f4-b79de2dd8c46)

### Expected behavior

Should render as expected

### OS and architecture in which you are running Nebari

Linux - Azure

### How to Reproduce the problem?

see above

### Compute environment

None

**Comment by Adam-D-Lewis** [comment]
That worked great.  I do think this is something that will trip up a lot of users.  Perhaps we could set up a rule in traefik to add the last forward slash if missing for endpoints that end with `/proxy/*`.

**Comment by krassowski** [comment]
This may be a simple change in `jupyter-server-proxy` (it already has an `AddSlashHandler`). But it _might_ have some unintended consequences so would require some thorough testing internally before we propose it upstream.

**Comment by dharhas** [comment]
The `/` vs `no /` has tripped me up on other packages as well, panel etc.

**Comment by Adam-D-Lewis** [comment]
Closing in favor of https://github.com/nebari-dev/nebari-docs/issues/240
