### ISSUE TITLE
[BUG] - Public app sharing with jhub-apps failing

### ISSUE THREAD

**Issue by rsignell** [nebari-dev/nebari#2274]
### Describe the bug

I  upgraded to Nebari 2024.1.1 to check out the new feature of publishing apps publically, which is super exciting.  Thanks to help from @dharhas, I modified my `nebari-config.yml` to include:
```
jhub_apps:
  enabled: true
```
and then deployed.    

Also thanks to a tip from @dharhas , I did *not* include `jhub-apps` package in my environment, but instead added these for my Panel app:
```
jhsingle-native-proxy>=0.8.2
bokeh-root-cmd>=0.1.2
```

This those changes in place, I was able to get a private app to work.  Yay!  

When I tried to flip the "public" switch to "on", however, I got:
```
Spawn failed: Server at http://10.10.113.195:8888/user/rsignell/hrrr-6eed58b/ didn't respond in 30 seconds

Event log
Server requested
2024-02-22T16:30:26.377695Z [Normal] Successfully assigned dev/jupyter-rsignell--hrrr-2d6eed58b to ip-10-10-105-151.us-west-2.compute.internal
2024-02-22T16:30:26Z [Normal] Container image "busybox:1.31" already present on machine
2024-02-22T16:30:26Z [Normal] Created container initialize-home-mount
2024-02-22T16:30:26Z [Normal] Started container initialize-home-mount
2024-02-22T16:30:27Z [Normal] Container image "busybox:1.31" already present on machine
2024-02-22T16:30:27Z [Normal] Created container initialize-shared-mounts
2024-02-22T16:30:27Z [Normal] Started container initialize-shared-mounts
2024-02-22T16:30:28Z [Normal] Container image "busybox:1.31" already present on machine
2024-02-22T16:30:28Z [Normal] Created container initialize-conda-store-mounts
2024-02-22T16:30:28Z [Normal] Started container initialize-conda-store-mounts
2024-02-22T16:30:29Z [Normal] Container image "quay.io/nebari/nebari-jupyterlab:2024.1.1" already present on machine
2024-02-22T16:30:29Z [Normal] Created container notebook
2024-02-22T16:30:29Z [Normal] Started container notebook
Spawn failed: Server at http://10.10.113.195:8888/user/rsignell/hrrr-6eed58b/ didn't respond in 30 seconds
```
@aktech , were there other things you needed to do to get this to work?

### Expected behavior

public deployment works

### OS and architecture in which you are running Nebari

WSL ubuntu

### How to Reproduce the problem?

try switching deploy public button to "on"

### Versions and dependencies used.

conda 23.3.1
Client Version: v1.28.3
nebari 2024.1.1

### Compute environment

AWS

**Comment by aktech** [comment]
So, if I understand from what's reported: the app works when not clicking on the allow public access and doesn't work other when allowed public access, then this is a bug I have not seen, can you share the pod logs of app?

**Comment by dharhas** [comment]
btw. I can confirm this on our quansight deployment.

**Comment by rsignell** [comment]
@aktech not  sure how to share the pod logs of app, since the app isn't running?

**Comment by aktech** [comment]
I just tried, it worked fine on the quansight deployment: https://nebari.quansight.dev/user/akumar@quansight.com/panel-f3fd7c0/ (will put this down in a bit, the link may not work when you see it)

@rsignell Did you create a new public app or edited the private one? Either ways it will kill the old pod and create a new one, I am looking for the logs for that pod. Can you try again and capture logs from k9s for that pod?

**Comment by rsignell** [comment]
@aktech I created a private app, then I tried creating another  (separate) public app.   I dont' know how to capture the logs of a pod that isn't running.

**Comment by aktech** [comment]
So, do you get a new app icon then after creating a public app, like this?

<img width="309" alt="Screenshot 2024-02-22 at 9 59 14 pm" src="https://github.com/nebari-dev/nebari/assets/5647941/0782bb03-ce5a-4276-a694-8f9ea71118aa">

**Comment by rsignell** [comment]
@aktech
* when I do "create app" and don't choose public, I get a dashboard appearing and everything is fine
* when I do "create app" and choose public, it starts spinning up jupyterlab and then fails.   I do then get a new app icon but it gives a 404:

![Screenshot 2024-02-23 063137](https://github.com/nebari-dev/nebari/assets/125569335/5ba69b4c-7197-4ced-b5c4-a5530eebeef2)

![Screenshot 2024-02-23 063214](https://github.com/nebari-dev/nebari/assets/125569335/bf1cc1e3-afb0-46c4-b115-28d4b15f145a)
![Screenshot 2024-02-23 063243](https://github.com/nebari-dev/nebari/assets/125569335/4983fb83-6af6-41c4-987b-57133f3e5c5a)
![Screenshot 2024-02-23 063426](https://github.com/nebari-dev/nebari/assets/125569335/c8f440c6-0843-48f3-8fdc-05d4f14493c1)
![Screenshot 2024-02-23 063413](https://github.com/nebari-dev/nebari/assets/125569335/8fcca128-d91b-4155-a972-e3cc18ec4d9a)

**Comment by rsignell** [comment]
@aktech and I did a live screenshare session using my deployment and confirmed that **his** simple public panel app worked, but **app** (which worked fine when not public) did not work as public.

The logs seemly showed everything working okay until it suddenly closed the stream and the pod died:

│ Setting debug                                                                                                                                                          ││ Starting jhsingle-native-proxy server on address 0.0.0.0 port 8888, proxying to port 0                                                                                 ││ URL Prefix: /user/rsignell/hrrr-public-6632ad8                                                                                                                         ││ Auth Type: none                                                                                                                                                        ││ Command: ('python', '{-}m', 'bokeh_root_cmd.main', '/shared/users/rsignell/repos/Holoviz-Demos/HRRR-Explorer.ipynb', '{--}port={port}', '{--}debug', '{--}allow-websoc ││ ket-origin=nebari.openscicomp.io', '{--}server=panel', '{--}prefix=https://nebari.openscicomp.io')                                                                     ││ Stream closed EOF for dev/jupyter-rsignell--hrrr-2dpublic-2d6632ad8 (notebook)   

The app I'm trying to run is this one:
 https://github.com/reproducible-notebooks/Holoviz-Demos/blob/master/HRRR-Explorer.ipynb

**Comment by marcelovilla** [comment]
@aktech @rsignell can we close this or is there some work that needs to be done to address it?

**Comment by kcpevey** [comment]
We've discovered a bug in the jhub-apps "Create App" form where the user may not have permission to share, but the UI lets them select those options anyway (including make public). Not sure if this is related.

**Comment by rsignell** [comment]
Ah, that may be it! We can close anyway as we've been able to publish public apps with recent versions
