### ISSUE TITLE
[ENH] - Expose configuration to specify existing VPC (without subnets)

### ISSUE THREAD

**Issue by aktech** [nebari-dev/nebari#2278]
### Feature description

Expose option to specify just the vpc to deploy Nebari into and additional configuration to specify deploying in private network.

### Value and/or benefit

There is an option to specify subnets in a VPC to deploy Nebari, but sometimes, people already have a vpc they would like to deploy Nebari into, it would be great to specify an option to deploy Nebari into.

**Comment by aktech** [comment]
@viniciusdc This needs to be done on Azure on priority, we can handle other clouds after that.

**Comment by viniciusdc** [comment]
@aktech this is not required anymore correct?

**Comment by aktech** [comment]
Correct, not required.
