### ISSUE TITLE
[ENH] - Scheduled Nebari Backups

### ISSUE THREAD

**Issue by pt247** [nebari-dev/nebari#2297]
### Feature description

We want to expand the existing configuration to allow it to specify backup parameters. 
Backing up Nebari includes the following:
1. KeyCloak user details.
2. User data
3. Conda environments

### Interface

```
backup
  location: <BACKUP LOCATION>>
  schedule: <CRON EXPRESSION>
  retention_period: <NUMBER OF DAYS>
```

### Implementation
There are several ways this can be achieved: 
1. Kubernetes  [CronJob](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/)
    1. Pros:
        1. Native to K8
        2. Good for simple disconnected tasks
    2. Cons:
        2. Will need to custom build and maintain status, monitoring, and alerting.  
2. Argo [Workflows](https://argoproj.github.io/workflows/)
    1. Pros:
        1. Fully featured UI
        2. Native artifact support
        3. Workflow archive
        4. Rest API
    2. Cons:
        1. Argo becomes a core component in Nebari.
        2. Most of our workflows might not be DAGs; it's possible that all the tasks can be independently executed. 
        

### Value and/or benefit

1. It will save the state from accidental deletes.

```[tasklist]
### Tasks
- [x] Add the pros and cons of each of the available options.
- [ ] Discuss available options
```

**Comment by Adam-D-Lewis** [comment]
BTW, I think you would use k8s Jobs instead of k8S Cronjobs
