### ISSUE TITLE
[BUG] - Conda store shows up in two places in menu bar

### ISSUE THREAD

**Issue by krassowski** [nebari-dev/nebari#2326]
### Describe the bug

In 2024.3.2 we have `jupyterlab-conda-store` extension back. However, now we have two (three) menu items allowing to open conda store:
- "Services > Environment Management" coming from nebari and opening conda-store in a new tab:
  ![image](https://github.com/nebari-dev/nebari/assets/5832902/6cb1722c-05b0-4051-90ed-0df7a48c0f84)
- "Conda-Store > Conda Store Package Manager" coming from `jupyterlab-conda-store`:
   ![image](https://github.com/nebari-dev/nebari/assets/5832902/fc67933d-010a-46e0-bedf-cfb655ae7d4b)

I don't think there is enough value in having the separate `Conda-Store` menu with just one item, and it might be confusing for users.

### Expected behavior

 Should we replace action associated with `Services > Environment Management` to open conda-store within JupyterLab? Or should we have both in a single menu (in that case how should we distinguish them?)

### OS and architecture in which you are running Nebari

2024.3.2

### How to Reproduce the problem?

Open JupyterLab

### Compute environment

None

### Anything else?

This is a follow-up to
- https://github.com/nebari-dev/nebari/issues/2182
- https://github.com/nebari-dev/nebari/issues/2216
- https://github.com/nebari-dev/nebari/issues/2302

**Comment by dharhas** [comment]
I see no reason to have both in the menu bar. I think we should use the jlab extension version here and not the standalone version link. I also think it makes more sense to call it "Environment Management" and not "Conda-Store".
