### ISSUE TITLE
Remove files related to cypress

### ISSUE THREAD

**Issue by dcmcand** [nebari-dev/nebari#2337]

**Comment by marcelovilla** [comment]
See #2075 for progress done in the past regarding the migration of Cypress to Playwright.

**Comment by marcelovilla** [comment]
I went over our Cypress tests and they perform the following actions:

1. Login to Nebari
2. Run a notebook
3. Visit different services URLs (i.e., keycloak, conda-store, and grafana); there's no interaction with these, however.

Our Playwright tests already take care of (1) and (2). Regarding (3):

* We're already implicitly testing keycloak's availability when logging in.
* We have a [test for Grafana](https://github.com/nebari-dev/nebari/blob/0f954204ac54a8223895ce3b28b39bf4929324c9/tests/tests_deployment/test_grafana_api.py) which implicitly tests the existence of the service (by accessing the API).
* We don't have anything that tests conda-store's availability for local tests as far as I am aware. We do have a [health check for cloud tests](https://github.com/nebari-dev/nebari/blob/0f954204ac54a8223895ce3b28b39bf4929324c9/tests/tests_integration/test_all_clouds.py#L21-#L26), though.

While #2075 takes care of removing all cypress-related files, it is only migrating (1) to Playwright. I could migrate (3) to Playwright (it's not too much effort) but I don't think it will be beneficial, except from maybe catching conda-store not being available in the local integration tests.

Eventually, I'd like to incorporate different user journeys regarding these services, whether that involves UI testing or not.

Happy to hear your opinions here.

I am including @Adam-D-Lewis in the conversation.
