### ISSUE TITLE
[BUG] - JupyterHub navbar items not redirecting correctly after visiting Admin Dashboard

### ISSUE THREAD

**Issue by marcelovilla** [nebari-dev/nebari#2359]
### Describe the bug

Nebari borrows some navbar items from JupyterHub, such as the Home, Token and Admin tabs. These work fine until one goes to the Admin tab. After visiting the Admin Dashboard, trying to go back to any of the Home, Token, and even the Admin tabs result in a `404 page not found error`. Here is an example of the Token tab, before and after visiting the Admin Dashboard:

https://github.com/nebari-dev/nebari/assets/36754005/df30e9cb-0f35-457f-864e-580aa49c15cd

As you can see, the Token tab URL is `/hub/token` before visiting the Admin Dashboard, but becomes `/token` after that.

I can reproduce this behavior (i.e. URLs changing after visiting the Admin Dashboard; see lower left corner in the video) locally using vanilla JupyterHub, with the difference that redirection works fine:

https://github.com/nebari-dev/nebari/assets/36754005/f5039655-ef57-4205-9c96-a257d43002ed

I guess we can have Nebari redirect `/token` to `/hub/token` but we would need to make sure that's not a general rule, as other services don't have the `/hub` prefix. For example: `/conda-store`.

### Expected behavior

I would expect for users to be able to go to the Admin Dashboard and then navigate back successfully to other sections of JupyterHub (e.g., the Home or Token tabs).

### OS and architecture in which you are running Nebari

AWS

### How to Reproduce the problem?

1. Visit the Admin Dashboard at `/hub/admin`
2. Try to navigate to one of the Home, Token or Admin tabs.

### Versions and dependencies used.

Nebari `2024.3.2`

### Compute environment

None

### Anything else?

This issue was originally identified by @kalpanachinnappan.

**Comment by dharhas** [comment]
@aktech @jbouder could this be related to the UI changes y'all have been working on.

**Comment by aktech** [comment]
> @aktech @jbouder could this be related to the UI changes y'all have been working on.

I would not expect that, since this happens without jhub-apps enabled as well. This is most likely a jupyterhub issue or maybe not exactly be an issue on JupyterHub as every url on jupyterhub is redirected to `/hub/<url>` by default, but in our case the ingress is most likely setup in a way to not do that redirect automatically.

**Comment by marcelovilla** [comment]
I agree; this does not seem to have any relation to UI changes. I can reproduce the same behavior (but with proper redirection) when running JupyterHub locally.

As @aktech mentioned, a way to fix this from our end is to redirect the `spawner`, `home`, `admin` and `token` URLs and have traefik add the `/hub` prefix.

I'm thinking of reporting this upstream as I don't think that should be the expected behavior in JupyterHub.
