### ISSUE TITLE
Make the "test-provider" Github Actions Test Conditional

### ISSUE THREAD

**Issue by tylergraff** [nebari-dev/nebari#2379]
### Feature description

The "test-provider" Github Actions test fails when run from forks of this repo which do not have credentials set up to access the cloud providers used by the test. This situation generates CI/CD pipeline failure messages every time the test is run from such a fork.

I propose an "opt-out" repo-level configuration mechanism which instructs the Github Actions pipeline to skip this test.

### Value and/or benefit

Being able to skip the "test-providers" (cloud platforms) test would allow maintainers of forks of this repo to avoid the CI/CD failure messages and emails which result from not having credentials set up. This would be especially useful for forks which do not have a budget to run these tests.

**Comment by viniciusdc** [comment]
Hi @tylergraff, This looks good. We can have the associated change merged, but I also think that maybe just skipping this whole test suite when not running from the upstream repository might be a good condition. These tests only attest that the CLI can be executed for our different providers, which for the forked repos can't be executed unless that maintainer adds cloud credentials.

Though, this discussion will be more fitting for #2382
