### ISSUE TITLE
[ENH] - Explore concurrency config for integration tests

### ISSUE THREAD

**Issue by viniciusdc** [nebari-dev/nebari#2386]
### Context

- Our current integration tests have been queued for a long time and should be updated according to only the most recent commit. 

### Value and/or benefit

- Helps with a faster feedback loop for the user
- Address stuck runs of our tests

**Comment by viniciusdc** [comment]
@aktech is this something you want to have a look? otherwise I can work on this

**Comment by marcelovilla** [comment]
@viniciusdc I assume we can close this after having merged https://github.com/nebari-dev/nebari/pull/2393, right?
