### ISSUE TITLE
[BUG] - User Scheduler pods run on user nodes preventing scale down on Azure

### ISSUE THREAD

**Issue by Adam-D-Lewis** [nebari-dev/nebari#2406]
### Describe the bug

User Scheduler pods run on user nodes preventing scale down on Azure

### Expected behavior

User nodes should be able to scale down to 0

### OS and architecture in which you are running Nebari

Linux x86-64

### How to Reproduce the problem?

See above

### Compute environment

None

**Comment by viniciusdc** [comment]
@Adam-D-Lewis can we include this as a subtask of https://github.com/nebari-dev/nebari/issues/2414

**Comment by Adam-D-Lewis** [comment]
@viniciusdc good catch.  I'll close this in favor of https://github.com/nebari-dev/nebari/issues/2414
