### ISSUE TITLE
[BUG] - User scheduler pods run on user node groups on GCP, Azure, DO deployments

### ISSUE THREAD

**Issue by Adam-D-Lewis** [nebari-dev/nebari#2414]
### Describe the bug

These pods prevent scale down of user node group and should be run on general node group ideally.

### Expected behavior

Run on general node group

### OS and architecture in which you are running Nebari

Linux x86-64

### How to Reproduce the problem?

Do a GCP, Azure, or DO deployment and see that 1 user node never scales down

### Compute environment

None

**Comment by viniciusdc** [comment]
I agree, as this is bothersome. However, I was under the impression we needed the user scheduler to exist in the same node as where we plan the pods to be scaled in.
