### ISSUE TITLE
Change VS Code launcher icon for the code-server icon

### ISSUE THREAD

**Issue by marcelovilla** [nebari-dev/nebari#2417]
### Context

Currently, it seems that the only reason we're using the `vscode-binder` package is to add the VS Code icon to the Jupyterlab launcher: 

https://github.com/nebari-dev/nebari-docker-images/blob/25697f163e296a7f03a513d0140b2b31ac109029/jupyterlab/environment.yaml#L61

**If this is the only use for it**, we should probably remove it and find a way of adding the code-server icon instead.

### Value and/or benefit

Besides getting rid of an extra dependency, it seems there are [some issues](https://github.com/betatim/vscode-binder/issues/38) in `vscode-binder` for newer versions of code-server.

**Comment by krassowski** [comment]
I'm on it as a sub-task in JupyterLab launcher redesign. I had opened https://github.com/betatim/vscode-binder/issues/60 yesterday.

**Comment by viniciusdc** [comment]
@krassowski can we assign this issue to you? you seem to have a better understanding of what needs to be addressed in both places already

**Comment by krassowski** [comment]
Upstream PR https://github.com/betatim/vscode-binder/pull/61 was merged. The icon should update next time the docker images are regenerated. There is still some follow-up work in JupyterLab because the icon currently is invisible in dark mode.

**Comment by krassowski** [comment]
Closing - in addition to upstream providing the updated icon, we are also shipping `jupyterlab-new-launcher` which also has the updated icon (which works better with dark mode):

![image](https://github.com/nebari-dev/nebari/assets/5832902/32cbdce7-3f50-4646-918b-892a868fd696)
