### ISSUE TITLE
[ENH] - Parse and load keycloak roles into conda-store

### ISSUE THREAD

**Issue by aktech** [nebari-dev/nebari#2433]
### Feature description

After the issue https://github.com/nebari-dev/nebari/issues/2308 is implemented, we will have access to groups and roles from keycloak in JupyterHub. Next we need to parse the role attributes and load them into Conda-Store, so that they are in affect.

Consider the following keycloak role:

Role: **write-access-conda-pycon-namespace-role**

| Key      | Value                       |
|----------|-----------------------------|
| resource | conda-store                 |
| scopes   | `write:conda-store!namespace=pycon` |

The scopes should be parsed and the equivalent should be added into conda-store such that when this role is attached to a user or group, they should have write access to pycon (for instance) namespace.

This feature is part implementation of RFD: https://github.com/nebari-dev/governance/issues/47

### Value and/or benefit

This will allow us to do fine-grained permissions on Conda-Store, which can be controlled from keycloak.

**Comment by viniciusdc** [comment]
@aktech just to double check, now that the parent issue is solved, this can be worked on right?
