### ISSUE TITLE
[BUG] - Broken Integration Tests (probably due to keycloak upgrade)

### ISSUE THREAD

**Issue by aktech** [nebari-dev/nebari#2434]
### Describe the bug

The integration tests are failing: https://github.com/nebari-dev/nebari/actions/runs/8880203375/job/24379721296
It was Passing before: https://github.com/nebari-dev/nebari/actions/runs/8839114418/job/24271736654

The difference I see is in the keycloak version: `3.12.0` -> `4.0.0` (Released: Apr 27, 2024)

### Expected behavior

CI test passing

### OS and architecture in which you are running Nebari

CI

### How to Reproduce the problem?

Looking at the CI

### Compute environment

None

**Comment by viniciusdc** [comment]
Thanks @aktech, as you suggested we should just pin to `< 4.0.0` to have the tests running again and consider their breaking changes https://github.com/marcospereirampj/python-keycloak/blob/master/CHANGELOG.md as a separated task
