### ISSUE TITLE
[BUG] - ARGO_TOKEN doesn't work for ARGO CLI

### ISSUE THREAD

**Issue by Adam-D-Lewis** [nebari-dev/nebari#2437]
### Describe the bug

See the comments on https://github.com/orgs/nebari-dev/discussions/2183#discussioncomment-8182829
The value currently set for ARGO_TOKEN is really meant for Hera, and HERA doesn't read the env var automatically anyway, it's just that our examples tell users to use ARGO_TOKEN when using HERA.

### Expected behavior

ARGO_TOKEN should work for use by the ARGO CLI.  Perhaps we can have a separate env var for HERA.

argo list should work

### OS and architecture in which you are running Nebari

Linux x86-64

### How to Reproduce the problem?

Download argo workflows cli.  Run argo list.  It won't work until 'Bearer ' prefix is added to the ARGO_TOKEN env var.

### Compute environment

None

**Comment by kcpevey** [comment]
@Adam-D-Lewis does this need a follow-on PR to update the docs?

**Comment by Adam-D-Lewis** [comment]
> @Adam-D-Lewis does this need a follow-on PR to update the docs?

Here it is - https://github.com/nebari-dev/nebari-docs/pull/444
