### ISSUE TITLE
[BUG] - Jupyter scheduler doesn't run successfully unless users are in developer group.

### ISSUE THREAD

**Issue by Adam-D-Lewis** [nebari-dev/nebari#2444]
### Describe the bug

https://www.nebari.dev/docs/tutorials/jupyter-scheduler/ states
`Only users in the admin or developer groups will have access to create notebook jobs. For more information regarding users and groups, please visit [How to configure Keycloak](https://www.nebari.dev/docs/how-tos/configuring-keycloak)`
but I had a user that was a member of /users, /analyst, and /admin groups, but Jupyter scheduler would fail for him.  After I added him to `developer` group, things worked as expected for him.

### Expected behavior

Update docs or fix bug

### OS and architecture in which you are running Nebari

Linux x86-64

### How to Reproduce the problem?

See above

### Compute environment

None

### Anything else?
v2024.4.1 of Nebari

**Comment by kcpevey** [comment]
@nkaretnikov can you confirm that `admin` is required? If so, I will likely open up a new issue to fix that.

**Comment by nkaretnikov** [comment]
@kcpevey I apologize for not being clear. It's _either_ `admin` or `developer` as the current docs say.
