### ISSUE TITLE
[BUG] - Setting env vars in conda store doesn't work in 2024.4.1 Nebari

### ISSUE THREAD

**Issue by Adam-D-Lewis** [nebari-dev/nebari#2445]
### Describe the bug

I created this `scratch` environment
![image](https://github.com/nebari-dev/nebari/assets/23342526/acd9d7e5-a01f-4364-bd6c-1fb8d67a61b2)

I tried seeing if `PYTHONUSERBASE` was set after activating scratch and it wasn't set.
![image](https://github.com/nebari-dev/nebari/assets/23342526/6fcaecbc-6db0-4fc8-a88a-0d9fe518208f)

I'm not sure if the issue is in conda store config in Nebari or upstream in conda store.

### Expected behavior

Env var should be set

### OS and architecture in which you are running Nebari

Linux x86-64

### How to Reproduce the problem?

see above
Nebari version - 2024.4.1 

### Compute environment

None

**Comment by kcpevey** [comment]
@Adam-D-Lewis just to confirm - the same process works on your local machine with just `conda`?

**Comment by kcpevey** [comment]
@Adam-D-Lewis the only environment variable available to users is the GPU-specific variable, `CONDA_OVERRIDE_CUDA`. 

I've opened [an issue on conda-store](https://github.com/conda-incubator/conda-store/issues/826) to allow *any* environment variable to be passed (feature parity with conda). I'll close this as it will need to be fixed at the conda-store level.

**Comment by gabalafou** [comment]
Cross-reference: 

- https://github.com/conda-incubator/conda-store-ui/pull/354
