### ISSUE TITLE
[ENH] - Build docker images for arm based machines

### ISSUE THREAD

**Issue by aktech** [nebari-dev/nebari#2454]
### Feature description

Build docker images for arm based machines.

### Value and/or benefit

Currently we're building docker images only for x86_64, which would not work for aarch64. Implementing this issue will have the following benefits:

- Users will be able to chose arm based images in their cloud provider to run Nebari on.
- It will help developers run local deployment of Nebari on Mac M1 (https://github.com/nebari-dev/nebari/issues/1405) or any arm based machines.

**Comment by marcelovilla** [comment]
This was closed by https://github.com/nebari-dev/nebari-docker-images/pull/141. Thanks @aktech 🚀 !
