### ISSUE TITLE
[BUG] - Failing Cypress tests in main

### ISSUE THREAD

**Issue by aktech** [nebari-dev/nebari#2463]
### Describe the bug

The cypress tests are failing in main:
https://github.com/nebari-dev/nebari/actions/runs/9067624675/job/24914178045#step:17:159

### Expected behavior

Testing passing

### OS and architecture in which you are running Nebari

Linux

### How to Reproduce the problem?

Run integration tests in the CI

### Compute environment

None

**Comment by krassowski** [comment]
>        Check Nebari login and start JupyterLab:
>      AssertionError: Timed out retrying after 4000ms: Expected to find element: `input.btn.btn-jupyter`, but never found it.

It is getting stuck on server selection screen:

![image](https://github.com/nebari-dev/nebari/assets/5832902/7b39c65b-f48c-4a43-abf3-916ad42a1c80)

Sounds like this could be related to Bootstrap 5 changes in JupyterHub 5. Maybe changing it to `button.btn.btn-jupyter` would be sufficient.

**Comment by aktech** [comment]
>Sounds like this could be related to Bootstrap 5 changes in JupyterHub 5

Yeah, my hunch was that too.
