### ISSUE TITLE
[BUG] - Playwright tests are currently failing due to change in jupyter

### ISSUE THREAD

**Issue by Adam-D-Lewis** [nebari-dev/nebari#2473]
### Describe the bug

Fix the tests so they pass.

### Expected behavior

tests should pass

### OS and architecture in which you are running Nebari

Linux x86-64

### How to Reproduce the problem?

See above

### Compute environment

None

**Comment by krassowski** [comment]
For reference https://github.com/nebari-dev/nebari/pull/2468#issuecomment-2116987239 and https://github.com/nebari-dev/nebari-docker-images/pull/146. The underlying issue is that CI does not run on PRs to docker images repo so we cannot verify changes.

**Comment by krassowski** [comment]
So PR https://github.com/nebari-dev/nebari-docker-images/pull/146 did resolve the problem with VS Code tile not having `title` attribute, but there is another issue due to the use of the new launcher:

```
playwright._impl._errors.Error: Locator.click: Error: strict mode violation: get_by_text("Kernel", exact=True) resolved to 3 elements:
    1) <div class="lm-MenuBar-itemLabel">Kernel</div> aka get_by_label("main menu").get_by_text("Kernel")
    2) <label>Kernel</label> aka get_by_role("cell", name="Kernel").locator("label")
    3) <label>Kernel</label> aka get_by_text("Kernel", exact=True).nth(2)

Call log:
waiting for get_by_text("Kernel", exact=True)
```

again, if the docker images were in monorepo, it would be caught earlier.

**Comment by Adam-D-Lewis** [comment]
I agree with you @krassowski that CICD needs to change to prevent issues like this.  As we discussed in the meeting, someone will need to draft an RFD to move the nebari images repo back into this repo.
