### ISSUE TITLE
Conda store worker scaling issues

### ISSUE THREAD

**Issue by Adam-D-Lewis** [nebari-dev/nebari#2505]
### Context

We'd like to scale conda store workers up to allow many solves at the same time.  See [here](https://github.com/nebari-dev/nebari/issues/2284) for more info.  However, the conda store worker pod also acts as a NFS server.  I believe this is b/c writing the environment files after the solve would be slow over the network (to an NFS drive) so we just co-locate the NFS server with the conda-store worker so files aren't going over the network when saving.  However, this limits the conda store worker scalability beyond a single node (the node the NFS server is on).

Options:
1. We could separate the conda store workers from NFS server, but the conda store workers become NFS clients and then have to write many small files (~40k to ~150k files for each env) over the network which is slow and likely adds 10 minutes (I want to benchmark this, but haven't yet) to the conda store env creation process which is not ideal and also likely won't scale with many concurrent conda solves anyway.  With this option, we'd likely want to also try to improve NFS performance. [This guide](https://www.redhat.com/sysadmin/using-nfsstat-nfsiostat#:~:text=High%20latency%20also%20affects%20the,client%20to%20ensure%20high%20throughput) or [this guide](https://cromwell-intl.com/open-source/performance-tuning/nfs.html) may have some useful tips.

2. We could try a distributed file system like CephFS, but it may require a learning curve and dealing with that additional complexity.
3. We could tar the environments and write to object storage and have some logic to pull them from object storage when a user boots up a pod, but this would require significant change to our current process, and so would be a lot of work, and may have additional issues we haven't considered yet (making sure users get new envs without restarting their pod, etc).
4. We could try EFS, Google File Store, and Azure Files, (not sure if DO has an NFS equivalent), but requires more maintenance since it's a separate solution for each cloud provider.  Those are also NFS or SMB drives anyway, so unless the cloud providers have optimized them somehow (very possible), they may not be any better than what we currently have.
5. I'm really not sure if this is a good idea, but I'll throw it out there anyway.  We could [mount object storage as a filesystem](https://bluexp.netapp.com/blog/amazon-s3-as-a-file-system).  Store the conda envs in object storage (not zipped or tarred) and use object storage like a local file storage.  Again, I'm not sure what drawbacks this might have.  Latency is high on object storage, but maybe it's okay if it's just loading the python binary and intalled libraries from there.  Not sure.  Because latency is high, we may have the same problems as the NFS drive though (slow writing of environment files after solve).  FYI, I see that the AWS s3 latency is [~100-200 milliseconds](https://docs.aws.amazon.com/AmazonS3/latest/userguide/optimizing-performance.html#:~:text=These%20applications%20can%20achieve%20consistent,performance%20for%20different%20application%20architectures.) if we want to compare with our NFS performance later.

### Anything else?

I looked at how large envs were and how many files they consisted of on a Nebari delpoyment, and found the following.
![image](https://github.com/nebari-dev/nebari/assets/23342526/15f81cab-2947-49dd-80ec-ff538ba52b46)
You can see that many envs have ~10k files, but it's not uncommon to have ~100k and some even have ~140k files.
***
![image](https://github.com/nebari-dev/nebari/assets/23342526/b40ed4d4-2945-4866-a8da-0f796ce1ded5)
Many envs are <1GiB in total size, most envs are <10GiB, but some are >20GiB in total size.
***
![image](https://github.com/nebari-dev/nebari/assets/23342526/d6852291-ecd1-4576-8e74-03f5f7ed33db)
The 10, 20, and 30 on the x axis represent 1KiB, 1MiB, and 1GiB.
This graph is individual number of files vs file sizes. The distribution is roughly lognormal with the min at 1KiB and few files > 1 MiB in size.

**Comment by dharhas** [comment]
We used to use EFS including the high performance EFS. This still had the same r/w slowdown issues.

CephFS might be worth looking into. We have had clients that have used it before and it is a mature solution.

**Comment by Adam-D-Lewis** [comment]
Older discussion on the topic: https://github.com/orgs/nebari-dev/discussions/1150

**Comment by dcmcand** [comment]
It also allows object store mounting with an s3 compatible api, so we could replace minio here

**Comment by Adam-D-Lewis** [comment]
I'm looking into Ceph a bit in [this issue](https://github.com/nebari-dev/nebari/issues/2534)

**Comment by Adam-D-Lewis** [comment]
PR using adding Ceph storage optionally replacing NFS - https://github.com/nebari-dev/nebari/pull/2541

**Comment by dharhas** [comment]
Some comments.

1. QHub (i.e. before Nebari) used to use EFS on AWS and we tried both the default and high performance (extra IOPs) versions of EFS. It had performance issues similar to our current NFS system
2. mounting block storage as a filesystem is likely to not work. S3 is not a POSIX compliant filesystem and certain file actions just don't work. i.e. sqlite databases cannot be read directly from s3 etc.
3. docker / extracting from tarball on the fly isn't a great option. It exchanges painful build time for a painful startup time.

Going into 3 in more detail. Jupyterhub orginally was based on pulling docker images. This works fine but at the cost of longer startup times and environment switching times. Many complex ML environments are 10-15GB and pulling a pod that large takes a very long time. Additionally, adding new environments requires creating new containers and paying the cost of shutting down and starting the new containers. Adding the environments to a shared folder that is then mounted to the pod, reduces startup time of pods and also makes switching environments painless and instant. The tarball idea seems like if would take significant time to generate envs on startup - `the conda-store worker would need to download all the tarballs from conda store and unpack them in the appropriate locations.`.

**Comment by Adam-D-Lewis** [comment]
> 2. mounting block storage as a filesystem is likely to not work. S3 is not a POSIX compliant filesystem and certain file actions just don't work. i.e. sqlite databases cannot be read directly from s3 etc.

I agree with the above.

> 3. docker / extracting from tarball on the fly isn't a great option. It exchanges painful build time for a painful startup time.
> 
> Going into 3 in more detail. Jupyterhub orginally was based on pulling docker images. This works fine but at the cost of longer startup times and environment switching times. Many complex ML environments are 10-15GB and pulling a pod that large takes a very long time. Additionally, adding new environments requires creating new containers and paying the cost of shutting down and starting the new containers. Adding the environments to a shared folder that is then mounted to the pod, reduces startup time of pods and also makes switching environments painless and instant. 

I want to clarify a few points about the idea. Think of the idea as moving the conda store worker pod to a container that runs along side each users pod.  There is only a single conda store worker for all the envs so we don't need to start up and shut down containers as new envs are created.

As I benchmarked above, some of our current envs are up to 20 GB in size so I agree we need to consider large envs in any solution.  I'm not sure how large the envs are compressed though.  I ran a test on an 8.6G env locally and it was 3.2GB compressed as a tar.zst file.

> The tarball idea seems like if would take significant time to generate envs on startup - `the conda-store worker would need to download all the tarballs from conda store and unpack them in the appropriate locations.`.

I think a strategy where you only download the last few used environments at startup would likely be good enough rather than downloading all of them on startup.  We would also download all the jupyter kernel spec files so that jupyterlab can identify which envs are available.  We could then download the environment if not present and untar it when the user tries to use the env in a notebook or tries to activate the env in the terminal.  This would cause a delay as the tarball is downloaded and uncompressed.  Assume a 20GB env becomes a 10GB tarball and a network speed of 10 Gbps would take 8 seconds (as a floor) but decompressing the tarball would take some time as well  (~7 seconds in my test of .tar.zst file).  Not ideal, but that doesn't seem like a deal breaker necessarily.  I think this is more scalable than a shared filesystem, but there are some drawbacks.

**Comment by dharhas** [comment]
The issue is that it isn't just a case of unzipping a folder. conda-pack does a bunch of link rewriting inside binaries to make everything work.

**Comment by Adam-D-Lewis** [comment]
I'll close this issue since we expect Ceph to address it for now.
