### ISSUE TITLE
[BUG] - Idle culler doesn't seem to be working on v2024.6.1rc3

### ISSUE THREAD

**Issue by Adam-D-Lewis** [nebari-dev/nebari#2506]
### Describe the bug

I ran a notebook.  I closed the browser tab.  I saw that my pod was up for 3h and 6m and is still up.  I don't think the idle culler extension is working on the v2024.6.1rc3 version of Nebari.

### Expected behavior

pod should die after a few (15?) minutes idle

### OS and architecture in which you are running Nebari

Linux x86-64

### How to Reproduce the problem?

see above

### Compute environment

GCP

**Comment by Adam-D-Lewis** [comment]
I just tested again and my pod was killed after ~30 minutes so I'll close since I can't reproduce.

**Comment by Adam-D-Lewis** [comment]
I saw this again with Mike's pod so I'll reopen. Perhaps, [this issue](https://github.com/jupyterhub/jupyterhub-idle-culler/issues/77 is related.

**Comment by viniciusdc** [comment]
I am adding the comment here, as I don't know if there is another one... the idle culler runs as an internal service of Jupyter, thus we might be able to inspect the metrics manually and inspect what might be keeping the kernel alive
