### ISSUE TITLE
[META] Nebari backup and restore

### ISSUE THREAD

**Issue by pt247** [nebari-dev/nebari#2518]
### Context

This is a meta issue that tracks the progress of backup and restore.
 
# Nebari Backup and Restore
Option 3 in [RDF](https://github.com/nebari-dev/governance/issues/49) for backup and restore describes the overall design.

## High-level architecture: 

```mermaid
flowchart LR
    subgraph Backup and restore library
        Client
    end
    Client-->I
    subgraph Nebari
        I
    I[Backup and restore interface API]-->K[Keycloak API]
    I-->C[Conda store API]
    I-->N[User data API]
    end
```

Related tasks:
1. Create Nebari REST API using FastAPI to expose the existing Keycloak API. 
2. Conda store API
3. User data API

**Comment by viniciusdc** [comment]
superseded by #2648
