### ISSUE TITLE
[BUG] - Keycloak does not start on the first try

### ISSUE THREAD

**Issue by krassowski** [nebari-dev/nebari#2579]
### Describe the bug

Locally I always have to restart keycloak after reboot. I see the following:

```
Connecting to github.com (20.26.156.215:443)
wget: note: TLS certificate validation not implemented      
Connecting to objects.githubusercontent.com (185.199.109.133:443)   
wget: can't open '/data/keycloak-metrics-spi-2.5.3.jar': File exists       
Stream closed EOF for dev/keycloak-0 (initialize-spi-metrics-jar) 
```

https://github.com/nebari-dev/nebari/blob/200099631c2f25e9d0eaa0a23b62df4cf6597651/src/_nebari/stages/kubernetes_keycloak/template/modules/kubernetes/keycloak-helm/values.yaml#L26-L40

This code was most recently modified in https://github.com/nebari-dev/nebari/pull/1810 (CC @Adam-D-Lewis)

It also means that the jupyterhub pod does not start up: https://github.com/nebari-dev/nebari/issues/2547

### Expected behavior

Keycloak starts on the first try

### OS and architecture in which you are running Nebari

Ubuntu

### How to Reproduce the problem?

1. Deploy locally on Ubuntu
2. Reboot
3. See that keycloak is not up

### Compute environment

None

**Comment by Adam-D-Lewis** [comment]
> Locally I always have to restart keycloak after reboot.

I'm trying to understand the issue.  I guess when you reboot, the k8s pods restart and run the init containers again, but somehow the file system of the keycloak pod is from the prior run?  I'll test and see if it happens to me.

**Comment by viniciusdc** [comment]
I am also not entirely sure; in theory, unless the keycloak metadata for the Kubernetes resource has changed, it should not restart. @krassowski why do you need it to restart? Also, because the helm provider handles this, some changes made to the values.yaml, do not trigger a change in the pod. This is a bug with the provider itself, as it can be seen in some other cases (I think this is related to how the provider calculates the diff)

**Comment by krassowski** [comment]
I need to restart it because when I boot my laptop it is always dead, I do not recall if it stuck in a restart loop or not but simply put nebari does not work until I get to k9s and restart it manually. I applied @Adam-D-Lewis's patch and will let you know if this helped or not as soon as I restart my laptop (but I think that patch is useful anyways because even if it is not the root cause, the logs will now be cleaner).

**Comment by krassowski** [comment]
> Also, because the helm provider handles this, some changes made to the values.yaml, do not trigger a change in the pod. This is a bug with the provider itself, as it can be seen in some other cases (I think this is related to how the provider calculates the diff)

I am not sure if I follow you here @viniciusdc, my problem is not during redeployment but after rebooting.

**Comment by krassowski** [comment]
This is my k9s when it fails:

![image](https://github.com/user-attachments/assets/bbbe70ad-d54e-4055-bd18-e782a62fc7d6)

![image](https://github.com/user-attachments/assets/41e4ea34-9c43-416b-ba36-6342b62f3110)
