### ISSUE TITLE
Handle cluster_ca_certifiate typo in upgrade step

### ISSUE THREAD

**Issue by Adam-D-Lewis** [nebari-dev/nebari#2597]
### Context

Typos is added to the repo in https://github.com/nebari-dev/nebari/pull/2568.  This issue is to correct cluster_ca_certifiate typo in `nebari/src/_nebari/stages/infrastructure/__init__.py` which will require updating the nebari config during the nebari upgrade step.

### Value and/or benefit

Fix a typo

**Comment by blakerosenthal** [comment]
I am noticing that when I generate the `stages/` directory without fixing the typo, both `stages/02-infrastructure/local/main.tf` and `stages/02-infrastructure/local/outputs.tf` contain the correctly spelled string: `cluster_ca_certificate`. The typo'd string doesn't appear in my nebari-config.yaml. Is there an init option that will put this string in the config?

**Comment by Adam-D-Lewis** [comment]
You're right.  It looks like this pydantic model is only used as an output and won't show up in the nebari config file.  I think you can just correct it without having to do anything else.
