### ISSUE TITLE
Enable file typo checking in typos

### ISSUE THREAD

**Issue by Adam-D-Lewis** [nebari-dev/nebari#2598]
### Context

In https://github.com/nebari-dev/nebari/pull/2568 I set default.check-filename = false.  We should enable it.  This will then rename src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/dask-gateway/controler.tf (missing l in controler.tf) to src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/dask-gateway/controller.tf.  We need to make sure we delete the extra file in a Nebari upgrade (or test and make sure the file would be deleted in an upgrade and not left around inappropriately).

### Value and/or benefit

Fix typo.

**Comment by blakerosenthal** [comment]
@Adam-D-Lewis I've verified that running `nebari deploy` after fixing the typo and running `nebari upgrade` does _not_ delete the old `controler.tf` file. Can you point me to the right place in the codebase where that cleanup needs to happen?
