### ISSUE TITLE
[BUG] - AWS Deployment tests getting skipped because of conditional variable

### ISSUE THREAD

**Issue by marcelovilla** [nebari-dev/nebari#2622]
### Describe the bug

Since a couple weeks ago, our AWS Deployment tests are getting skipped. See:
* https://github.com/nebari-dev/nebari/actions/runs/10240771812
* https://github.com/nebari-dev/nebari/actions/runs/10344230388
* https://github.com/nebari-dev/nebari/actions/runs/10371249794
* https://github.com/nebari-dev/nebari/actions/runs/10372048378

The issue seems to be with [the way we're checking for credentials in order to decide whether we skip the job or not](https://github.com/nebari-dev/nebari/blob/843453daf9d440be00ba74402a8607870adcf373/.github/workflows/test_aws_integration.yaml#L36-L60). I believe this behavior was introduced in https://github.com/nebari-dev/nebari/pull/2569

### Expected behavior

The AWS Deployment tests should not be skipped.

### OS and architecture in which you are running Nebari

Not relevant

### How to Reproduce the problem?

Run the [AWS Deployment workflow](https://github.com/nebari-dev/nebari/actions/workflows/test_aws_integration.yaml) manually.

### Compute environment

None

**Comment by BrianCashProf** [comment]
This PR will replace the env variable with an action variable set at the repo level.
https://github.com/nebari-dev/nebari/pull/2632
To allow for the tests, the following action variables need to be set:
NO_PROVIDER_CREDENTIALS_AWS: 0
NO_PROVIDER_CREDENTIALS_AZURE: 0
NO_PROVIDER_CREDENTIALS_GCP: 0
NO_PROVIDER_CREDENTIALS_DO: 0

**Comment by marcelovilla** [comment]
Thanks @BrianCashProf! In the near-term future, we'll refactor the cloud provider integration tests so they don't run on a schedule basis but rather after every PR has been merged or before cutting a release. Hopefully this will make it easier for forks to work with that.

**Comment by marcelovilla** [comment]
I'm closing this issue as https://github.com/nebari-dev/nebari/pull/2632 was merged. Thanks @BrianCashProf !
