### ISSUE TITLE
Remove references to Digital Ocean in code base

### ISSUE THREAD

**Issue by Adam-D-Lewis** [nebari-dev/nebari#2749]
### Context

Digital Ocean has been deprecated for several releases now with a warning.  No one has protested this change.  We should remove Digital Ocean functionality from the code base now.

Related RFD - https://github.com/nebari-dev/governance/issues/50

### Value and/or benefit

Less maintenance, Focus on other improvments

**Comment by viniciusdc** [comment]
- Remove digital ocean integration tests: 
	- #2765  	
- Remove digital ocean from unit tests parameters

**Comment by marcelovilla** [comment]
> * Remove digital ocean from unit tests parameters

Seems this is being taken care of in https://github.com/nebari-dev/nebari/pull/2813

**Comment by Adam-D-Lewis** [comment]
> Seems this is being taken care of in https://github.com/nebari-dev/nebari/pull/2813

This removes the tests, but not the many references to Digital Ocean in the code base (or the docs).

**Comment by marcelovilla** [comment]
> That PR removes the tests, but not the many references to Digital Ocean in the code base (or the docs).

Correct, I meant the reference in the tests.

I've opened https://github.com/nebari-dev/nebari/pull/2838 to remove all the references. It's still a draft PR and it likely needs more work.
