### ISSUE TITLE
Modify pre-commit hook for codespell

### ISSUE THREAD

**Issue by kcpevey** [nebari-dev/nebari#70]
### Context

The [codespell](https://github.com/codespell-project/codespell) hook is set up to fix the misspellings. I think this is too dangerous in a codebase. Codespell is written such that it will try not to fix unique words it doesn't know, but I would much rather not rely on that and instead, just let it give us a list of misspellings that we can choose to fix (or not). 

Also, we need to add files to skip (node_modules, etc). Running the pre-commit as-is just modified a ton of files unnecessarily. 

### Value and/or benefit

* we get "suggested" spelling errors instead of "forced" spelling fixes (which may not be valid)
* fewer false positives by removing non-project files

**Comment by trallard** [comment]
> Also, we need to add files to skip (node_modules, etc). Running the pre-commit as-is just modified a ton of files unnecessarily.

What pre-commit hook is doing this? AFAIK the current ones should not be dealing with anything js related

**Comment by kcpevey** [comment]
> What pre-commit hook is doing this? AFAIK the current ones should not be dealing with anything js related 

The codespell one is run on everything.
https://github.com/nebari-dev/nebari/blob/main/.pre-commit-config.yaml#L35
