### ISSUE TITLE
Make jupyterlab default environment part of managed nebari-config.yaml environments

### ISSUE THREAD

**Issue by tylerpotts** [nebari-dev/nebari#785]
## Summary

Currently the environment that jupyterlab launches with is built into the docker container that qhub launches with. This becomes an issue when users would like to modify the jupyterlab environment e.g. [like PR #730](https://github.com/Quansight/qhub/pull/730). This would also reduce the size of the docker image speeding up the jupyterlab image launching.

## Proposed implementation

The `default` jupyterlab environment will now be specified in [DEFAULT_ENVIRONMENTS](https://github.com/Quansight/qhub/blob/1fe386d412ca154b933696b8e43a6e30e16cca01/qhub/initialize.py#L209) and the environment.yaml will be removed from the jupyterlab qhub image. There additionally needs to be a validation check to ensure that the default environment exists in the default environments. 

## Acceptance Criteria

 - [ ] jupyterlab profile should launch normally

## Related to

Closes https://github.com/Quansight/qhub/issues/715

**Comment by iameskild** [comment]
Another related feature to consider is allowing users to install linux packages via `qhub-config.yaml`. Currently this handled in the Jupyterlab docker images (in `apt.txt`).

**Comment by trallard** [comment]
@iameskild  does this need to remain open? seems this issue is now stale

**Comment by iameskild** [comment]
I would say that if we go with the RFD I proposed [here](https://github.com/nebari-dev/governance/issues/22#issuecomment-1325113646) (or some other variant), we won't need this since the user will be able to customize their jupyterlab image how they see fit.

**Comment by trallard** [comment]
Ok marking as blocked until we decide on the RFD

**Comment by dcmcand** [comment]
Closing because this is now possible using jhub-apps
