### ISSUE TITLE
Add K8s logging in the CI when nebari deploy fails

### ISSUE THREAD

**Issue by aktech** [nebari-dev/nebari#793]
At the moment when the K8s deploy fails, there is not much information for the user in the CI logs for the user to figure out the root cause of the problem.

A nice approach would be to have a step run on failure, which logs everything from the minikube kubernetes cluster.
I have done something similar in  https://github.com/dask/dask-gateway

**Comment by Adam-D-Lewis** [comment]
@tylerpotts This could be affect our debugging of the monitoring PR where the kubernetes tests are failing.

**Comment by costrouc** [comment]
@aktech I was thinking that we could tie in https://github.com/Quansight/qhub/issues/771 to this issue. The idea would be to run `qhub support`  on failure or something similar to create an artifact on failure that could be used for inspection.

**Comment by aktech** [comment]
@costrouc sounds great, would be great if we can print that in the CI step itself instead of an artifact.

**Comment by iameskild** [comment]
If CI fails, run the `qhub support` tool and save the output.

**Comment by iameskild** [comment]
I think for now we can consider this closed. The `nebari support` grabs a bunch of k8s logs and saves them to the user's local machine in case they want to review them or share them with us over an issue.
