### ISSUE TITLE
Remove local helm chart from prefect and follow model as in jupyterhub service

### ISSUE THREAD

**Issue by viniciusdc** [nebari-dev/nebari#819]

**Comment by viniciusdc** [comment]
Hi @costrouc I've separated this into another issue because I wanted to have some directions about this in particular. Right now the current helm chart we are deploying within QHub only creates the Prerfect-agent, and unfortunately, Prefect does not have any specific helm chart to deploy only that (see [here](https://github.com/PrefectHQ/prefect/issues/4406)). But, there is a helm chart, not from Prefect that deploys exactly as ours, [this one](https://github.com/dojeda/prefect-helm), but I don't see much gain swithing to that one.

Then I've come with two options:

- Deploy the prefect server helm chart, [provided by Prefect](https://github.com/PrefectHQ/server/tree/master/helm/prefect-server/templates), it's possible to deploy the agent in that too, but it will also install the other dependencies.
- The other option is to maintain the local chart, currently in use, and just update the variables as needed.

**Comment by Adam-D-Lewis** [comment]
One option would be to open an issue on the Prefect Server helm chart repo and propose to add an option to disable all the other services besides the agent.  They would remain enabled by default in their repo, but we would disable them when used in our repo.  That PR should be straight forward.

That would give us the benefit of any future improvements made by others in the Prefect Agent template part of the Prefect Server helm chart.

One issue is we'd be dependent on the Prefect Server community to merge our future PR's on the Prefect Agent and it's possible they may not agree with us on change we want to make.

**Comment by trallard** [comment]
@viniciusdc  @Adam-D-Lewis  what is the status of this issue - I know Prefect is now fully integrated but can we close this issue?

**Comment by Adam-D-Lewis** [comment]
The helm chart for prefect is still inside the qhub repo (https://github.com/Quansight/qhub/tree/main/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/infrastructure/modules/kubernetes/services/prefect/chart).  I know we wanted to move the `chart` directory outside the repo into it's own repo at some point and that hasn't been done.

**Comment by iameskild** [comment]
Superceeded by https://github.com/nebari-dev/nebari/issues/1217
