### ISSUE TITLE
DEVEX - Improve first time user deployment experience

### ISSUE THREAD

**Issue by Adam-D-Lewis** [nebari-dev/nebari#826]
I remember some gotchas as I was deploying on various cloud providers such as needing to enable certain settings on the cloud provider.  We've recently had an issue submitted which claimed that using the default instance size did not work for them when deploying Qhub.

I want to make sure that when users try to deploy for the first time that things go flawlessly.  This may entail reviewing/updating download and deployment documentation.  This may involve expanding test coverage.  This might include creating videos guiding users through the installation process on each of the cloud providers which are updated as needed.  The first thing I would do is create a cloud deployment from scratch following the documentation and make improvements to the documentation based on that.

**Comment by Adam-D-Lewis** [comment]
Some ideas
- Create a video walking through a fresh deployment on each of the cloud providers.
	- Post the videos at the top of the Step-by-Step Qhub Deployment pages
- Create videos demo'ing the selling points of Qhub, and put them in the documentation somewhere (similar to Databricks and Domino Data Labs).
- Have a "Try Now!" option, where users can play around on a small qhub cluster without having to deploy it themselves?
- Have a demo deployment option for trying out qhub
	- `pip install qhub && qhub --local-demo`
		- works on Linux, MacOS?, Windows?
		- downloads minikube, docker, launches a local qhub, opens to an instruction notebook
		- Try to get feedback for ease of deployment somehow.
- Create a gif and video of the demo deployment option for qhub. 
			- Include notebooks in the demo that explain the features of qhub.
			  - We have users pre-configured with linux file permissioning.
			  - Prefect (not included here, but go to our full install to enable it)
			  - Dask
	- then go ahead and show the config file afterwards
- https://docs.qhub.dev/en/stable/source/04_how_to_guides/8_login_qhub_training.html doesn't seem to belong with the rest of the qhub documentation.  It would be better as a link accessible from the qhub training page.

**Comment by viniciusdc** [comment]
c.c @magsol

**Comment by trallard** [comment]
@pavithraes  I am tagging you here for visibility - once you are more familiarised with nebari I would like to discuss how we can further improve newcomers experience

**Comment by trallard** [comment]
@pavithraes seems we made plenty progress in this front recently, do we want to close this issue and work on future tasks separately?

**Comment by pavithraes** [comment]
@trallard Yes that sounds good to me, closing!
