### ISSUE TITLE
Explore switching to Calico CNI for AWS deployments

### ISSUE THREAD

**Issue by iameskild** [nebari-dev/nebari#836]
This is related to issue #828. 

As a starting point:
https://saturncloud.io/blog/practical-issues-setting-up-kubernetes-for-data-science-on-aws/

**Comment by viniciusdc** [comment]
@iameskild could you update this with the latest status?

**Comment by trallard** [comment]
@viniciusdc @iameskild  is this still relevant or can we close?

**Comment by iameskild** [comment]
We can close this.
