### ISSUE TITLE
[enhancement]  Add the black labextension

### ISSUE THREAD

**Issue by rsignell-usgs** [nebari-dev/nebari#858]
## Description
Would be cool to have the Black labextension available to Qhub users:
https://coiled.io/blog/code-formatting-jupyter-notebooks-with-black/

**Comment by iameskild** [comment]
Hi @rsignell-usgs, could you try adding it to one of your conda environments (in the `qhub-config.yaml`) and redeploying? Although I haven't tried this with a qhub deployment yet, testing it in local `jupyter lab` session seemed to work :)

**Comment by trallard** [comment]
@iameskild or @viniciusdc  I think this should be easy to add to the new Docker images now that they are in `nebari-dev` can either of you take this on?

**Comment by iameskild** [comment]
@trallard @rsignell-usgs I've raised a PR to add `jupyterlab_code_formatter` :)
https://github.com/nebari-dev/nebari-docker-images/pull/26
