### ISSUE TITLE
[enhancement] Display nebari's internal parameters : version number, project name, ...

### ISSUE THREAD

**Issue by pierrotsmnrd** [nebari-dev/nebari#869]
## Description
Our internal Qhub has been automatically deployed via GitHub Actions after a PR to upgrade to version 0.3.13.
If I rely on the logs, it worked. But how can I be sure ?  

## Suggestion
By showing Qhub's version number on the web interface, as well as version numbers and informations about the other tools, the user would be sure of what he has deployed.  
**Bonus** : we could make it in such a way that, when a user opens an issue, he simply has to copy/past a chunk of text containing all the necessary informations (project name, version numbers, cloud provider, number of Dask workers ...)

**Comment by iameskild** [comment]
Hey @pierrotsmnrd, I think this is a great idea! In the future, it might not just be admins who open tickets and having this information readily available to end-users would make it easier for them to open issues with the appropriate detail.

I'm happy to take a stab at implementing this :)

**Comment by iameskild** [comment]
We currently display the Nebari version on the homepage (bottom-left of the screen). The theme description also prints the cloud provider and name of the cluster by default so I think we can consider this complete for now. @pierrotsmnrd if you have other thoughts, feel free to let us know :)
