### ISSUE TITLE
[enhancement] - add DEvSecOps to QHub CI

### ISSUE THREAD

**Issue by trallard** [nebari-dev/nebari#891]
## Description

We want to ensure that the QHub deployments are secure and that we can identify any potential vulnerabilities ASAP.

## Suggestion
- Use a tool like [kubescape](https://github.com/armosec/kubescape) within the CI 
- Add documentation for folks deploying their own QHub instances on how to use / add kubescape

## Context
DevSecOps benefits everyone - from the team developing QHub to the end-users and folks deploying QHub for their own use

**Comment by viniciusdc** [comment]
c.c @magsol
