### ISSUE TITLE
[enhancement] Add R-Studio and xfce (desktop enviroment) profiles

### ISSUE THREAD

**Issue by iameskild** [nebari-dev/nebari#896]
## Description

Currently users are able to launch Jupyterlab instances (Ubuntu only, with CentOS to come). From my discussion with @costrouc, it would be great to have the ability to launch R-Studio and even a desktop environment like [xfce](https://www.xfce.org/). 

## Value/benefit

This would enhance the the user-experience and potentially attract a large pool of users.

**Comment by danlester** [comment]
@tonyfast Please add to an umbrella UX tracker issue
