### ISSUE TITLE
[enhancement]  Consider using All-contributors bot

### ISSUE THREAD

**Issue by trallard** [nebari-dev/nebari#899]
## Description

Contributions to os projects are valuable and they all deserve recognition. Can we adopt the usage of the all contributors bot? <https://allcontributors.org/docs/en/bot/overview>

## Value/benefit

- Helps to recognise all types of contributions
- A nice way to thank folks for spending time in the project
- Build community

**Comment by dharhas** [comment]
Great Idea!
