### ISSUE TITLE
[enhancement] Development and production user interfaces

### ISSUE THREAD

**Issue by tonyfast** [nebari-dev/nebari#924]
## Description

Currently the user interface uses some tools that improve the user experience, but there are more we can add. it would be nice to try different lab extensions before putting the into production. I am proposing at least two user interface images: the current prod version and a work in progress environment that we can use to add new features and test.

## Value/benefit

currently, we can't change the user experience without impacting everyone. another development image would give us the freedom to provide an enhanced user interface without effecting the current services. i'd like to experiment with some of the collaborative tools we serve with [hourhaus](https://github.com/deathbeds/hourhaus/blob/main/requirements.txt)

this request builds off of ideas in #903 with adding different user interfaces to the qhub experience.

**Comment by pierrotsmnrd** [comment]
The fastest and easiest way I see to do so, is forking and deploying your own forks, as I did for some of my PRs. By having a personal deployment, we're free to experiment and research without any limitation. The drawback is that it implies a cost for the cloud provider.

Alternatively, we could imagine a `dev.qhub.dev` or `alpha.qhub.dev` or whatever, with its specific deploy repo, that we could use as a sandbox. The drawback here is the risk of collision if too much of us experiment at the same time.

I hope I understood the question right :)

**Comment by tonyfast** [comment]
yea. i'm not going to find the time to setup my own qhub.

i am thinking that there qhub.dev/alpha or qhub.dev/sandbox. these endpoints would deploy a different on a different endpoint that allows for experimentation on production data. in this conformation, early adopters can try out new features and fall back the blessed user interface when problems arise.

**Comment by danlester** [comment]
This can be part of a move to having JupyterLab images as more plug-and-play so you can easily switch in different images. Perhaps some of these ideas will help with this #1174 #1145 
Ideally, people can work on JupyterLab config without understanding Docker at all.

**Comment by pavithraes** [comment]
We'll need to open an [RFD](https://github.com/nebari-dev/governance/issues/new?assignees=&labels=type%3A+RFD&projects=&template=RFD.md&title=RFD+-+Title) to discuss the staging/production workflow.

**Comment by dcmcand** [comment]
JLab 4 allows users to install extensions by conda environments and with the addition of jhub-apps this is now possible in Nebari.
